### ISSUE TITLE
跨平台编译

### ISSUE THREAD

**Issue by hh-kai** [ithewei/libhv#1]
按照Uasge提示的，使用 make all TARGET=libhv CROSS_COMPILE=arm-hisiv400-linux- 跨平台编译
编译失败
[编译日志.txt](https://github.com/ithewei/libhv/files/4062938/default.txt)

**Comment by hh-kai** [comment]
后来又编译了一下 需要这样 make libhv CROSS_COMPILE=arm-hisiv400-linux-  就能编译成功了 其他的测试例子 需要单独编译

**Comment by ithewei** [comment]
htime.c:(.text+0x10): undefined reference to `clock_gettime'
miss -lrt

感谢反馈，已更新加上-rt
see BUILD.md
export CROSS_COMPILE=arm-hisiv400-linux-
./configure
make libhv
