### ISSUE TITLE
handle multipart file upload use large memory，传大文件没有使用磁盘缓存机制

### ISSUE THREAD

**Issue by mosxuqian** [ithewei/libhv#10]
其他框架的做法是：
1、用户自定义数据接收。
2、使用/tmp磁盘空间作为缓存。

**Comment by ithewei** [comment]
libhv的目标是简单易用高性能，不是大而全，没有考虑大文件上传下载，一般的图片几M测试过是OK的
1、用户自定义数据收发，就失去了便利性，大多用户都希望给一个文件名就能调用；
2、使用/tmp，不了解这种方案，实现也会增加源码复杂性吧，还要考虑跨平台；

**Comment by mosxuqian** [comment]
@ithewei 额外又发现一个问题，现在是接收http整个(尤其是大数据量)请求完成后，再去判断路由存不存在。会有几个问题：
1、占用过多带宽。
2、应答不及时，如果网速慢可能好多秒之后才给client回应。
3、短时间内占用内存。

要是能将路由判断稍微前置一下更好。

**Comment by ithewei** [comment]
大数据http请求场景很少，提前判断路由返回响应，也需要客户端支持这种边发请求边收响应，所以暂无支持判断路由前置计划
