### ISSUE TITLE
不能调试 希望可以解决

### ISSUE THREAD

**Issue by zb353027** [ithewei/libhv#100]
http 回调处理 handle的时候不能调试，只能输出打印，希望可以解决

**Comment by ithewei** [comment]
使用何种IDE，如何调试，不在本项目讨论范畴，首先确保编译的是Debug库吧

**Comment by ithewei** [comment]
你是否是将断点打在`handler.h`，我想有的IDE是不支持打在头文件的，你可以将handler.h实现移到handler.cpp再下断点试试

**Comment by ithewei** [comment]
httpd示例在linux下是多进程模式，所以无法调试，可以修改`etc/httpd.conf`里的`worker_processes=0`，关闭多进程模式以方便调试
