### ISSUE TITLE
postman作为测试客户端因收不到post请求的应答数据卡住

### ISSUE THREAD

**Issue by dzh592204** [ithewei/libhv#101]
测试过程：
编译并运行http_server_test工程； 测试如下接口时，postman第一次发送请求，正常获取应答数据；但是第二次请求时，postman就因收不到应答数据卡住；通过wiresharp抓包，确实没有抓到应答数据。
ps1: 采用老接口的方式（httprequest httpresponse）则没这个问题；	

router.POST("/echo", [](const HttpContextPtr& ctx) {
		return ctx->send(ctx->body(), ctx->type());
});

**Comment by ithewei** [comment]
感谢反馈，已修，原因是keepalive请求，writer状态未重置导致
