### ISSUE TITLE
[feature]: Support custom unpack method.

### ISSUE THREAD

**Issue by Hconk** [ithewei/libhv#102]
Currently `unpack_setting_t` can't custom define unpack method, so if i want processes like this TCP package data: 
```
// The first 1 byte 0x30 is package data bit length  ( very special case, only for Example. )
0x30 0x01 0x02 0x03 0x04 0x05 0x06 
```
I try add `unpack_coding_e` type and change `hio_unpack_by_length_field` process this case. 
So, It will be very useful if provide some way to customize the unpack method.

**Comment by ithewei** [comment]
Yes, only three common unpacking mode are provided currently: that is fixed packet length, delimiter, and header length field. The implementation is directly operated on the internal readbuf, this is very efficient, avoid memcpy again on the upper layer, but it's also uncontrollable, so not provide custom unpack method. 
Anyway, you can do your own unpacking and grouping on read callback, such as complex protocol http_parser that used state mechine.
