### ISSUE TITLE
http server 不支持 options 方法

### ISSUE THREAD

**Issue by yulunyue** [ithewei/libhv#118]

**Comment by ithewei** [comment]
HttpService::Handle("OPTIONS", ...)
或者在preprocessor里拦截都可以，参考[examples/httpd](https://github.com/ithewei/libhv/blob/master/examples/httpd/handler.cpp)

**Comment by yulunyue** [comment]
但是只要注册一个 * 的路由，右面的路由都会匹配到这个 * ，即使我再最后再注册 *。在路由匹配遍历时，他依然是第一个

**Comment by ithewei** [comment]
*是通配符匹配，单独一个*就是表示匹配所有路径，你如果还有其它路径要区分匹配，可细分下，比如/a/，/b/*，/c，
当然你可以在preprocessor完全自主控制，通过获取到的method和path

**Comment by yulunyue** [comment]
有一点我比较困惑，比如说我先注册 一个路由 a，再注册一个路由 *。然后我用一个a的请求去测试，打断点调试发现。在遍历数组路由时他会先匹配 *。 
也发现其它的路由的顺序 和我注册的先后顺序也不一样。所以我想问下这是什么原因呢。 还有就是一个请求，多个路由可以匹配正确 该怎么办呢

**Comment by ithewei** [comment]
这是因为用了std::map，底层是rbtree是有序的，如果想要遍历时和注册顺序一样，估计得用std::unordered_map
