### ISSUE TITLE
About echo benchmark

### ISSUE THREAD

**Issue by ktprime** [ithewei/libhv#119]
```
void read_cb(struct bufferevent* bev, void* userdata) {
#if 1
    bufferevent_write_buffer(bev, bufferevent_get_input(bev)); //ok or not?
#else
    /* This callback is invoked when there is data to read on bev. */
    struct evbuffer *input = bufferevent_get_input(bev);
    struct evbuffer *output = bufferevent_get_output(bev);
    
    /* Copy all the data from the input buffer to the output buffer. */
    int ret = evbuffer_add_buffer(output, input);
    if (ret == 0) {
        bufferevent_write_buffer(bev, output);
    }
#endif
}
```

**Comment by ithewei** [comment]
It should be ok, but does not affect the benchmark result：
libev ~= libhv > libuv > libevent ~= asio ~= poco
see [Actions](https://github.com/ithewei/libhv/actions/workflows/benchmark.yml)

**Comment by ktprime** [comment]
> It should be ok, but does not affect the benchmark result： libev ~= libhv > libuv > libevent ~= asio ~= poco see [Actions](https://github.com/ithewei/libhv/actions/workflows/benchmark.yml)

if libevent not use eventbuffer(slow echo test), only raw event as libev, what's difference ?

**Comment by ithewei** [comment]
There is no need to pay too much attention to the performance gap. The maximum performance gap between these libraries does not exceed 2 times. The performance of other languages is far inferior to c/c++, but it does not prevent them from making good products. Ease of use and development efficiency are more worthy of our consideration.
