### ISSUE TITLE
解决nlog，linux PC使用bash telnet访问log，按ctrl+c无法退出问题

### ISSUE THREAD

**Issue by mosxuqian** [ithewei/libhv#12]
https://github.com/ithewei/libhv/blob/01a0b90215a81828ca6141f3d7b3d363a4267209/event/nlog.c#L41

代码修改成即可

static void on_read(hio_t* io, void* buf, int readbytes) {
    printd("on_read fd=%d readbytes=%d\n", hio_fd(io), readbytes);
    printd("< %s\n", (char*)buf);
    uint8_t* tmp = buf;
    if (readbytes > 4 && tmp[0] == 255 && tmp[1] == 244 && tmp[2] == 255 && tmp[3] == 253 && tmp[4] == 6)
    {
        hio_close(io);
    }
}

**Comment by ithewei** [comment]
quit telent:
try "Control-]"
telent > quit
