### ISSUE TITLE
http客户端异步方式连接一个错误的地址，没有触发回调函数

### ISSUE THREAD

**Issue by windflowerly** [ithewei/libhv#120]
测试过程中，http客户端异步方式连接一个错误的地址（该地址不能联通），没有触发异步的回调方法。
设置了超时时间为2秒。
也没有找到设置timeout的回调方法。
请问这种情况怎么处理

**Comment by ithewei** [comment]
感谢反馈，这里是因为内部自动失败重试超时错误没有被捕获导致，上面commit已修复
此外建议timeout不要设置的太短，容易导致超时，一般至少设置10s
