### ISSUE TITLE
WebSocket 不支持接收Binary数据？ 

### ISSUE THREAD

**Issue by wenchao-cui** [ithewei/libhv#122]
WebSocket的消息，有Text 字符串 和Binary二进制数据，但是看libhv中
WebSocketClient 和 WebSocketService 的定义中接收数据函数，只有
std::function<void(const std::string& msg)> onmessage;
不支持接收Binary数据？

**Comment by ithewei** [comment]
支持的，都是走的onmessage回调，只是没有给出消息数据类型，通过msg.data()，msg.size()拿到二进制数据即可

**Comment by wenchao-cui** [comment]
好的，测试了，可以拿到二进制数据

**Comment by zhaokaixs** [comment]
没有给出消息类型是怎么考虑的~   是不是标识出来，能让调用者更明白当前是文本消息，还是二进制消息（直接走自定义协议解析）

**Comment by wenchao-cui** [comment]
邮件已收到，这是自动回复

**Comment by ithewei** [comment]
新版的在WebSocketChannel里加了个成员变量记录当前opcode，可以通过接口获取到，具体使用见示例代码
https://github.com/ithewei/libhv/blob/6f584c514269ba16c4f1737b4fe3ee2d1b046132/examples/websocket_server_test.cpp#L76
