### ISSUE TITLE
建议：base和event单独搞一个仓库

### ISSUE THREAD

**Issue by jwcpp** [ithewei/libhv#123]
base和event单独搞一个core仓库，不要和c++、http放一起。
可以参考libuv，弄一个干净的，否则显得杂乱无章，就比较混乱

**Comment by ithewei** [comment]
Good suggestion！

`base、event`等c模块和`evpp、http`等c++模块放在一起是因为库起步阶段相对于`libevent、libuv`等老牌网络库没有竞争力，想多增加些看点；

如果只想编译base、event等c模块，可通过如下方式:
```
./configure --without-evpp
make clean && make
```
或者
```
cmake -DWIHT_EVPP=OFF
```
