### ISSUE TITLE
相同会话的请求中使用同一个 http_client_t 对象会报 ssl 异常

### ISSUE THREAD

**Issue by MewTyrant** [ithewei/libhv#124]
我在官方提供的HTTP测试例子中（http_client_test） 将执行次数从1次修改到10次。则执行的时候会抛异常，经过测试，如果将http_client_t 在每次请求后释放，重新分配一个对象，则可以正常执行。
`
cnt = 10;
 for (int i = 0; i < cnt; ++i) {

        //test_http_async_client(async_client, &finished);
        http_client_t* sync_client = http_client_new();

        test_http_sync_client(sync_client);

        http_client_del(sync_client);
        continue;
        test_requests();

        test_axios();
    }
`
以前的代码是公用一个 http_client_t 对象的。
`http_client_t* sync_client = http_client_new();

    for (int i = 0; i < cnt; ++i) {

        //test_http_async_client(async_client, &finished);

        test_http_sync_client(sync_client);
        continue;
        test_requests();

        test_axios();
    }

    http_client_del(sync_client);`

异常：
0x00007FF8508DF72D (libssl-1_1-x64.dll)处(位于 http_client_test.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000000000030 时发生访问冲突。

**Comment by ithewei** [comment]
判断https有误导致，已修复，感谢反馈
