### ISSUE TITLE
Suggestion: enrich the document of basic timer functions and eventloops

### ISSUE THREAD

**Issue by DCZYewen** [ithewei/libhv#125]
I tried to use libhv as a library that provides a timer, which could be used as a heartbeat request driver.
But reading `examples/htimer_test.c` does not provide enough information on htimer.h's usage.
e.g.
```
htimer_add() function is declared as 
htimer_t* htimer_add(hloop_t* loop, htimer_cb cb, uint32_t timeout, uint32_t repeat DEFAULT(INFINITE));

htimer_cb is declared as 
typedef void (*htimer_cb)   (htimer_t* timer);
```

since the callback function only receives 1 parameter: htimer_t* timer. so how can I send information without using inter-process communication like:

```
std::string info;
void sendToServer(std::string info);
void callback(htimer_t *timer){
    // sendToServer(info); ????
}
```

Thank you for your great project.

**Comment by ithewei** [comment]
```c
void on_timer(htimer_t* timer) {
    void* userdata = hevent_userdata(timer);
    ...
}

htimer_t* timer = htimer_add(...)
hevent_set_userdata(timer,  userdata)
```

htimer_t, hio_t, hidle_t are all subclasses of hevent_t, inheriting the member variables and member functions of hevent_t, such as hevent_userdata/hevent_set_userdata, so hevent_cb, htimer_cb, hread_cb and other callbacks have no userdata parameter, which is easier.

In addition, I found that you are from China, you can read [README-CN.md](https://github.com/ithewei/libhv/blob/master/README-CN.md), chinese tutorial is very detailed.

**Comment by DCZYewen** [comment]
谢谢你的认真回复，并祝`libhv`的发展越来越好
