### ISSUE TITLE
Request new release

### ISSUE THREAD

**Issue by DCZYewen** [ithewei/libhv#126]
https://github.com/ithewei/libhv/blob/3a6b5f30ed22cea0054590591c5ebe37a1543505/examples/http_client_test.cpp#L86

您好，我看到了在 examples/http_client_test.cpp 的示例代码，其中在Release 1.2.2的版本中的request.h中HttpRequest派生于HttpMessage，这两个类中都没有SetForm的定义， 查看history看到它是在oct 26加入master的，所以请求您发布一个新的release
谢谢！

**Comment by ithewei** [comment]
这个只是一个封装接口，老版本你可以这么写：
```
req->form["username"] = FormData("admin");
```

libhv会节制性的发版，除非有核心功能bug或者新feature才会发版的，敬请谅解！

**Comment by DCZYewen** [comment]
谢谢您的耐心回复。 
libhv让C++的网编编程变得容易，是一个很好的项目，我也想参与其中。
我的能力有限，想着重丰富一下libhv的文档和示例程序，你看这个方向可以吗

**Comment by ithewei** [comment]
当然可以，欢迎加入
