### ISSUE TITLE
关于连接池问题

### ISSUE THREAD

**Issue by windflowerly** [ithewei/libhv#128]
我在进行AsyncHttpClient进行压力测试过程中发现一个现象。
我自始至终只申请了一个AsyncHttpClient实例。通过该实例对一个地址进行压力测试。大概是每秒中发起8000个请求。持续10分钟。在此期间，发现其对同一个地址，一共建立了200个http长连接。

我看了代码，似乎只有对不同的地址才会发起不同的连接。
请问AsyncHttpClient的连接池是如何管理这些连接的。

**Comment by ithewei** [comment]
有请求任务过来就会从连接池里借出连接，获取到响应后才会放回（因为HTTP1并不支持多路复用连续请求），所以即使是同一地址，在高并发情况下也是可能产生多个连接的

**Comment by windflowerly** [comment]
如何控制连接的总数量，如果压力过大，会导致大量的连接。

**Comment by ithewei** [comment]
客户端不至于太大的并发吧，如果你想控制每个地址的连接池数量可以在ConnPool里加限制，不过超过限制的并发请求就可能需要排队等待了，这个逻辑代码里也是没有的

**Comment by windflowerly** [comment]
我的场景比较特殊，所以碰到了这个问题。

**Comment by ithewei** [comment]
那你应该在上层控制并发数，不然要么导致大量连接，要么导致请求超时

**Comment by windflowerly** [comment]
嗯。多谢建议。
