### ISSUE TITLE
how to read form-data

### ISSUE THREAD

**Issue by yaowhncoeus** [ithewei/libhv#13]

**Comment by ithewei** [comment]
HttpMessage have a member form which type is MultiPart,
typedef std::map<std::string, FormData>          MultiPart;
you can use it as a map, however, you may like HttpMessage::GetString GetBool GetInt GetFloat.
Examples see examples/httpd/

**Comment by dongrixinyu** [comment]
> HttpMessage have a member form which type is MultiPart,
> typedef std::map<std::string, FormData> MultiPart;
> you can use it as a map, however, you may like HttpMessage::GetString GetBool GetInt GetFloat.
> Examples see examples/httpd/

httpd 里没样例呀，如果form 是个复杂的格式呢?
