### ISSUE TITLE
static library, undefined reference to `http_server_run'

### ISSUE THREAD

**Issue by ryuukk** [ithewei/libhv#134]
Hello

I am trying to use this library, compiled as static library in D

I get the following error whenever i try to port the web socket sample

``undefined reference to `http_server_run'``

```
mkdir build
cd build
cmake -DBUILD_SHARED=OFF -DBUILD_STATIC=ON ../
```

nm show no symbol exported

``nm: HttpServer.cpp.o: no symbols``

Is there something i am missing?

**Comment by ryuukk** [comment]
Now i get the symbols, but it's C++

```
➜  build git:(dev) ✗ nm -C lib/libhv_static.a | grep http_server_run                                                                                                                                            
0000000000000062 r .L__FUNCTION__._Z15http_server_runP13http_server_si                                                                                                                                         
0000000000000000 T http_server_run(http_server_s*, int)   
```

Is it possible to export C symbols?

Thanks!

**Comment by ryuukk** [comment]
Oh i see the issue

Compiling without EVPP doesn't export HTTP symbols

**Comment by ithewei** [comment]
NO, http module is written by c++, refer to examples/tinyhttpd.c if you want to implement http protocol by c.

**Comment by ryuukk** [comment]
i will take a look, thanks @ithewei

**Comment by ryuukk** [comment]
@ithewei would you accept a PR that add a small shim for C for websocket?

**Comment by ithewei** [comment]
> @ithewei would you accept a PR that add a small shim for C for websocket?

Of course！Looking forward to your PR！
