### ISSUE TITLE
HttpRequest::Dump 不是const 函数，会引发很多问题

### ISSUE THREAD

**Issue by f20500909** [ithewei/libhv#135]
- 测试代码：

``` cpp
#include "requests.h"
#include "axios.h"
#include "hlog.h"

using namespace hv;

#define DEBUG_MODE 1;

void mylogger(int loglevel, const char* buf, int len) {
    stdout_logger(loglevel, buf, len);
}

void test_code() {
    HttpRequest req;
    req.headers["Host"] = "220.181.38.251:80";

    hlogi("req.host: %s req.port: %d ", req.host.c_str(), req.port);

#ifdef DEBUG_MODE
    const char* msg = req.Dump(true,true).c_str();
    // printf(msg);
#endif

    hlogi("req.host: %s req.port: %d ", req.host.c_str(), req.port);
}

int main(int argc, char* argv[]) {
    logger_set_handler(hlog, mylogger);

    HttpClient sync_client;

    test_code();

    return 0;
}

```

- 输出：
- 
![image](https://user-images.githubusercontent.com/33808231/146664542-8d10017e-fc2c-403d-8221-ff79170371b6.png)

## 问题如下：
有两次相同的hlogi日志输出，但是中间使用了HttpRequest::Dump函数来进行debug以输出日志，奇怪的是前后两次的输出不一致。

我预期的是Dump函数不会改变成员变量的值，但是实际上Dump改变了host和port。我认为Dump函数中更改成员变量的值的设计并不合理，会引发一系列问题。

---

在公司里，日志的输出是这样的：
`LOG(DEBUG)<<req.Dump(true,true)`
但是这种输出会导致debug模式和release模式下，产生不同的行为。
公司工作时，http relay服务端因为滥用HttpRequest::Dump，导致host和port设置错误，又因为开启了http错误重试，导致无限重试。结果就是一次http处理错误，让服务端雪崩式重试，服务就挂掉了。

等我有时间，把这个问题解决了，就提pr代码，想问下大佬有什么更好的思路或想法吗？

**Comment by ithewei** [comment]
看了你的测试代码，第一次host输出`127.0.0.1`，这是host变量初始化的值，执行`Dump`时，内部做了很多解析工作的，包括从`Host`头解析出实际的值赋值给host变量，所以第二次打印是你Host头里的值，这个是符合预期的；
另外Dump这个函数没法做成const类型，因为函数里会自动填充`Content-Length`等头部，需要写`headers`成员变量；

**Comment by ithewei** [comment]
如果你想设置`Host`头部后，马上打印的host变量就是设置后的指，可以通过`HttpRequest::SetHost`这个接口，而不是直接
`req.headers["Host"] = "220.181.38.251:80";`，因为这样是直接写headers变量，而host变量是尚未设置的
