### ISSUE TITLE
How to determine whether the received PACKET is binary or text?

### ISSUE THREAD

**Issue by torukskywalker** [ithewei/libhv#136]
1.	如何在客户端及服务端判断收到的PACKET是binary或text ?
2.	C++客户端试着用binary mode传送arraybuffer, 每一次最大似乎不能超过4MB? 
3.	C++客户端传送更大数据量时切成每笔4MB, 但每笔似乎要间隔(sleep(1) ),否则会错误.( 服务端会断线再重连)

**Comment by ithewei** [comment]
你的这些问题是指websocket协议吗，不然我很难对号入座，如果是，请看下面解答：

1、websocket回调里确实没有给出帧类型，因为不提倡通过websocket协议的opcode来区分binary或text，而是应该通过url；
2、3：明显是大数据没做发送流量控制，过快的发会导致内部写队列堆积，当超过一定量，为了避免内存暴涨所以自动close掉了，这点你可以通过查看日志里是否有`high water`字样（写队列高水位报警）来确认；

建议阅读：
- https://hewei.blog.csdn.net/article/details/121313149 第四条：大数据没考虑分片和流量控制
- https://hewei.blog.csdn.net/article/details/113737580 里面有关于`hio_write`写队列的介绍；

**Comment by trunglebka** [comment]
Hi, sorry for re-open closed issue.
I have to use translation to read you all comment, please correct me if any misunderstood. 
In the previous comment you say that "Websocket callback does not give the frame type" and the recommended way is via URL. But with complicated applications that require control message (Ex. Json) to control the server and binary to send data, what is your recommended way to overcome this limit?  Create new endpoint to control the same service is complicating client code, isn't it?
