### ISSUE TITLE
libhv curl POST application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by Clownsw** [ithewei/libhv#138]
> 问题说明:

 libhv POST 数据请求有问题

> 详细问题

**curl代码**
`curl "https://gitee.com/oauth/token?grant_type=authorization_code" -X POST -d "code=7d772b2a30ab871d6f7e4b477eb366bf57d244c1027d9da36890693dd2c902af&redirect_uri=http://localhost:8080/callback&client_secret=b038e2291b15a17020b1990dc7968cc3242cbe7866847bdda76955bbb4dd3157&client_id=da8d35d19146a05d8c797c7a5e9929eb770059874af5c32aa1f0141365076c9b"`

**libhv_curl代码**

`curl -X POST https://gitee.com/oauth/token?grant_type=authorization_code -d "code=7d772b2a30ab871d6f7e4b477eb366bf57d244c1027d9da36890693dd2c902af&redirect_uri=http://localhost:8080/callback&client_secret=b038e2291b15a17020b1990dc7968cc3242cbe7866847bdda76955bbb4dd3157&client_id=da8d35d19146a05d8c797c7a5e9929eb770059874af5c32aa1f0141365076c9b"`

> 响应结果分别是

**curl:** {"error":"invalid_grant","error_description":"授权方式无效，或者登录回调地址无效、过期或已被撤销"}
**libcurl:**  {"error":"invalid_request","error_description":"这个请求缺少必要的参数，或者参数值、格式不正确"}

似乎libhv的post数据未正确发送

**Comment by ithewei** [comment]
libhv examples/curl 和 原始的curl还是有些细节差异的，原始的curl -d 默认就是`Content-Type: application/x-www-form-urlencoded`，libhv里需要显示说明下，
```
bin/curl -v localhost:8080/kv   -H 'Content-Type:application/x-www-form-urlencoded' -d 'user=admin&pswd=123456'
```
另外-d里的内容需要urlencoded编码下，如上面的redirect_uri里就包含`://`这些特殊字符需要转换，如果你是通过libhv编程，可通过`HttpMessage::SetUrlEncoded`接口添加，内部会帮你编码的

**Comment by ithewei** [comment]
@Clownsw 最新examples/curl已对齐curl，已能识别-d数据格式，并自动设置Content-Type头，编码urlencoded
