### ISSUE TITLE
windows mingw 编译hsocke.c 错误

### ISSUE THREAD

**Issue by yulunyue** [ithewei/libhv#14]
#hscoket.h
static inline const char* sockaddr_ip(sockaddr_u* addr, char* ip, int len) {
    if (addr->sa.sa_family == AF_INET) {
        return inet_ntop(AF_INET, &addr->sin.sin_addr, ip, len);
    }
    else if (addr->sa.sa_family == AF_INET6) {
        return inet_ntop(AF_INET6, &addr->sin6.sin6_addr, ip, len);
    }
    return ip;
}

#hsocket.c
int Resolver(const char* host, sockaddr_u* addr) {
    if (inet_pton(AF_INET, host, &addr->sin.sin_addr) == 1) {
        addr->sa.sa_family = AF_INET; // host is ipv4, so easy ;)
        return 0;
    }

inet_ntop 返回值是 char 还是 int 呢

**Comment by ithewei** [comment]
const char *inet_ntop(int af, const void *src, char *dst, socklen_t size);
如编译报错请贴出编译错误

**Comment by yulunyue** [comment]
不好意思，我搞错了，问题已经解决了，就是 inet_ntop undefined 。我是用的qt的mingw编译的 。加上 这个宏就可以了 -D_WIN32_WINNT=0x0600
