### ISSUE TITLE
How to get multiple cookies?

### ISSUE THREAD

**Issue by githubchry** [ithewei/libhv#147]
![image](https://user-images.githubusercontent.com/15260796/152786098-d909a431-e929-496e-aecd-be14d97da3f0.png)

示例
Cookie: Clion-edb1cd6f=d6308536-768a-46b3-bcee-336d0f5bdb12; Webstorm-404865a5=61eb7ce3-6ac9-4649-8438-01b269efdff1; Authorization=2ffdeae0c6e36b9ba911f16a25ee32f3

HttpCookie cookie;
req->GetCookie(cookie);
cookie.dump() => Clion-edb1cd6f=d6308536-768a-46b3-bcee-336d0f5bdb12

**Comment by ithewei** [comment]
HttpMessage::headers的类型是std::map<std::string, std::string>，不是multimap，所以GetCookie这个接口只能获取到一个Cookie，想获取多个cookie，可以遍历HttpMessage::cookies
