### ISSUE TITLE
hv_rand

### ISSUE THREAD

**Issue by wujin1989** [ithewei/libhv#148]
hv_rand 使用的是标准 c rand函数实现，但是rand函数在不同平台的随机范围是不一样的。

建议：
#include <stdlib.h>
#include <stdint.h>

static uint64_t seed;

void srand(unsigned s)
{
	seed = s-1;
}

int rand(void)
{
	seed = 6364136223846793005ULL*seed + 1;
	return seed>>33;
}
从musl c 移植过来。

**Comment by ithewei** [comment]
rand的范围是0到RAND_MAX，hv_rand的范围是min到max，没有错的

**Comment by wujin1989** [comment]
可以 RAND_MAX 在不同平台是不一样的值， RAND_MAX在linux下是INT_MAX但是在win下不是。

如果hv_rand(min, max) 这里max 大于win的RAND_MAX，那hv_rand在linux可能是好的，但是在win上可以不正常。

**Comment by wujin1989** [comment]
其实我想说的不是hv_rand, 而是 标准库的rand不能作为跨平台实现。因为不同平台下的rand_max是不一样的。
目前的实现会导致hv_rand(1, 32767 + 1), 在win下这个永远不会随机到32768这个值。

**Comment by wujin1989** [comment]
> rand的范围是0到RAND_MAX，hv_rand的范围是min到max，没有错的

其实我想说的不是hv_rand, 而是 标准库的rand不能作为跨平台实现。因为不同平台下的rand_max是不一样的。
目前的实现会导致hv_rand(1, 32767 + 1), 在win下这个永远不会随机到32768这个值。
