### ISSUE TITLE
log file path

### ISSUE THREAD

**Issue by liuzhuan23** [ithewei/libhv#149]
When running http, a log file similar to libhv.20220211.log will be generated, how can I modify the directory where this file is generated? 

thk u.

**Comment by spiderpigpig** [comment]
I had the same problem, it seems you can change base/hlog.h DEFAULT_LOG_FILE before compiling, but setting logger_set_file after compiling has no effect, wait for ithewei's explanation

**Comment by ithewei** [comment]
`hlog_set_file("/path/to/filename.log")`
