### ISSUE TITLE
Some functions in libhv will execute exit when encountering errors. Does this have parameters to adjust the behavior?

### ISSUE THREAD

**Issue by liuzhuan23** [ithewei/libhv#152]
Some functions in libhv will execute exit when encountering errors. Does this have parameters to adjust the behavior?

**Comment by liuzhuan23** [comment]
for example, the http_server_run function uses an already bound port, and it will force exit here, but I hope that after an error occurs, it can exit gracefully. Can this be done?

thk u.

**Comment by ithewei** [comment]
exit() only exists in base/hbase.c, which is an unrecoverable error when malloc failed.
