### ISSUE TITLE
多线程情况下，gethostbyname引发的崩溃问题

### ISSUE THREAD

**Issue by windflowerly** [ithewei/libhv#153]
我使用http异步客户端进行测试时发现，Resolver函数中，使用了gethostbyname函数，该函数是不安全的。在多线程的情况下，时候用会引起崩溃。在我的代码中已经多次出现。
![image](https://user-images.githubusercontent.com/3378243/155287672-3c7678da-f036-4eb7-b67d-0d16f0b3af60.png)

**Comment by ithewei** [comment]
gethostbyname man手册里介绍此函数是线程安全的，你是怎么判断崩溃在gethostbyname里的？

**Comment by windflowerly** [comment]
这个函数单独执行没有问题。问题在于多线程的情况下，这个返回的指针的内容可能会被后执行的覆盖掉。
比如A、B两个线程调用该函数，A首先获取到phe的指针，如果在使用过程中，B也调用该函数。此时A拿到的这个指针的内容就会被改变。

因为gethostbyname函数里定义的是静态变量，返回的是这个静态变量的指针。

我在崩溃的堆栈中，就发现我拿到的phe指针，指向的内容是错误的。

**Comment by windflowerly** [comment]
可能是我给的图误导你了

**Comment by windflowerly** [comment]
为啥不舍弃gethostbyname,  直接使用getaddrinfo。

**Comment by iGwkang** [comment]
> gethostbyname man手册里介绍此函数是线程安全的，你是怎么判断崩溃在gethostbyname里的？ 如果你觉得这里线程不安全，可以开启ENABLE_IPV6，这样就使用了getaddrinfo

@ithewei gethostbyname 在man page中写的是非线程安全，内部使用了静态变量，多线程同时调用gethostbyname大概率崩溃，hostent中的链表被释放，man page中这个函数已经标记为弃用，使用getaddrinfo才是安全的。
https://man7.org/linux/man-pages/man3/gethostbyname.3.html
