### ISSUE TITLE
AsyncHttpClient::sendRequest函数中出现了智能指针过期的问题

### ISSUE THREAD

**Issue by windflowerly** [ithewei/libhv#154]
AsyncHttpClient::sendRequest函数中，ctx这个智能指针指向的parser对象过期了，也引发崩溃。
![image](https://user-images.githubusercontent.com/3378243/155438175-aef4f7d9-3e01-484b-a805-5ad0edcabbae.png)

调试信息如下：
$3 = {task = std::shared_ptr (count 3, weak 0) 0x0, resp = std::shared_ptr (expired, weak 0) 0x7fdc7ac32430, parser = std::shared_ptr (expired, weak 0) 0x7fdc7ac66fc0, timerID = 18446744073709551615}

**Comment by ithewei** [comment]
上面不是有判断`ctx->parser == NULL` 就会 `HttpParser::New`的

**Comment by windflowerly** [comment]
我看到了，不知道为啥运行到151行的时候，还是出现了parser这个指针失效的问题。
开始怀疑是我内存写越界了，但是发现只有ctx这个指向的的对象有问题，其他地方都是正常的。
如果内存写越界，不太可能只写坏一处。
