### ISSUE TITLE
无法根据channel id 找到 channel

### ISSUE THREAD

**Issue by yuwenhaibo** [ithewei/libhv#155]
通常为了减少库的结构体依赖，我一般封装为
 virtual bool  OnRead(int id，void *buf ,unsigned int len)=0;
导致我想主动关闭channel 的时候 无法根据id 找到channel 从而执行close 方法

**Comment by ithewei** [comment]
有两种方法：
1、使用map保存id、channel的映射关系；
2、使用channel::setContext/getContext，设置/获取上下文；

**Comment by yuwenhaibo** [comment]
目前只能用map来在建立一个映射了，context 也必须得找到channel 才能使用context 吧
std::map<int, TSocketChannelPtr> channels; // GUAREDE_BY(mutex_) 这个map 使用fd 作为key 不使用 id 有什么考虑吗？

**Comment by ithewei** [comment]
没什么特别考量，你使用id作为客户端标示，不代表其他人也使用id作为客户端标示，客户端标示和channel的映射关系是需要应用层自己保存的

**Comment by yuwenhaibo** [comment]
好感谢你的回复
