### ISSUE TITLE
Please add libhv-config.cmake for complete vcpkg tools chain. 

### ISSUE THREAD

**Issue by endingly** [ithewei/libhv#156]
能不能找时间添加一下libhv-config.cmake文件，vcpkg用起来很麻烦啊

**Comment by ithewei** [comment]
默认不打开SSL选项是因为，如果打开，会导致新手因为不会安装openssl反复提编译问题。
如果需要开启SSL功能，建议还是自行`./configure --with-openssl`或者`cmake . -DWITH_OPENSSL=on`
