### ISSUE TITLE
ConnectFDTimeout函数有个隐藏的问题

### ISSUE THREAD

**Issue by windflowerly** [ithewei/libhv#165]
![image](https://user-images.githubusercontent.com/3378243/159673397-065e36ad-e870-40ba-9f04-cdf25c9bfc58.png)
select能够控制的socket的最大值是1024，当大于connfd > 1024时，是会出现问题的。换句话说，如果使用你的库，是没法打开超过1024个客户端。

**Comment by ithewei** [comment]
select局限数是指个数，不是指fd大小，这里的select就只添加了一个fd，不会有问题的

**Comment by jiuyuan-light** [comment]
> select局限数是指个数，不是指fd大小，这里的select就只添加了一个fd，不会有问题的

select的代码是使用数组实现的位图，（如果socket或open返回值）fd大于等于1024（FD_SETSIZE）就会导致FD_SET数组越界的问题。
除了采用poll，epoll外还有好的解决方法吗，

**Comment by lichuangcheng** [comment]
进程打开了超过1024个文件，这里确实就会崩溃
![image](https://github.com/user-attachments/assets/df1b4360-19c8-4ff9-b661-5569a4a01dbe)
