### ISSUE TITLE
这一段代码是否有问题

### ISSUE THREAD

**Issue by ruanwenfeng** [ithewei/libhv#167]
https://github.com/ithewei/libhv/blob/e4090c146e29e598838efeeaf2cc44ad5f8eb08c/examples/hloop_test.c#L106-L113

**ev** 是分配在栈上的变量，生命周期应该在循环体内。

**Comment by ithewei** [comment]
没有问题的，hloop_post_event内部会深拷贝hevent_t到custom_events队列里的，sizeof(hevent_t)只有64字节，也不用担心性能和内存问题

**Comment by ruanwenfeng** [comment]
> 没有问题的，hloop_post_event内部会深拷贝hevent_t到custom_events队列里的，sizeof(hevent_t)只有64字节，也不用担心性能和内存问题

理解了，看了一下 **QUEUE_DECL**  这个宏的实现，的确是的，内部有深拷贝
