### ISSUE TITLE
Help, I'm new!

### ISSUE THREAD

**Issue by aryaman-a** [ithewei/libhv#17]
Hi, I'm new to GitHub and I want to start helping out in some project. Could someone be kind enough to just let me know how the code is compiled into one URL and how are they connected here in Github. I understand how the pull requests, branches, issues section, and a little bit of markdown work ( because I took the intro course from the lab ), but I don't get how all this code thrown in the code tab compiles/connects as one and contributes to building the software. Final question: is github only for building websites? Or *how and where is the software built here used and applied elsewhere.*
**If this is not a project/server that encourages new guys then I deeply apologise and appreciate your time.**
*also, what is the main purpose of this project?*
Thanks

**Comment by ithewei** [comment]
Welcome,
First of all, there are many programming languages in this world. Each programming language has its own compiler and build tools. You can find the language you are interested in to learn first. For example, if you want to build a website, you need to understand the front-end（html+css+js） knowledge.
Finally, libhv is a c/c++ network library, I hope you find your interest soon.

**Comment by xiaowenxia** [comment]
🤣

**Comment by aryaman-a** [comment]
Hi
Thanks for responding! I do know java and have written many programs in VSC before. I can learn HTML and CSS from youtube though. I've looked it up and found some videos for the basics. For, C, I did know it a couple of years back but I've forgotten it now. 
What I wanted to know is how all the code in the code tab is interconnected, and where can we find the software we build here in use.

**Comment by aryaman-a** [comment]
So what is libhv and what is being built here? What kind of IO does it deal with?

**Comment by ithewei** [comment]
We download the code from github, and then compile it locally to obtain the product, an application, a website, or a library. Each language has its own build method, such as c/c++ through Makefile or cmake, Android through gradle, nodejs through npm or yarn, etc. 
The compilation product of libhv is a library and some command-line demos. See BUILD.md for specific compilation steps.

**Comment by aryaman-a** [comment]
ahhhh 
thanks a lot, I really appreciate it. I've been scratching my head over how all this works for a couple of days now. Thanks again.
So in this project and others, that are operational (is this one operational right now?), we just fix bugs, make new versions and add new features, right?

**Comment by ithewei** [comment]
Right！Add new features and fix bug.

**Comment by aryaman-a** [comment]
all right, thanks again for helping. I'll be around
