### ISSUE TITLE
请问如何只编译http/https客户端

### ISSUE THREAD

**Issue by fxqy** [ithewei/libhv#173]
如果是mingw纯c环境，能否只编译http/https客户端
在你的博客中看到下图中的提示，是不是纯c不能用
![图片](https://user-images.githubusercontent.com/42601163/162710978-7b179de2-f9af-4204-b9a6-5f5f8d0bf889.png)

**Comment by ithewei** [comment]
http模块使用了c++，纯c是无法编译的

**Comment by fxqy** [comment]
我刚才在mingw下make成功了，纯c代码中无法使用吗？
![图片](https://user-images.githubusercontent.com/42601163/162723008-447d463d-023e-44f7-a303-3e8c1ad795f2.png)

**Comment by ithewei** [comment]
不是说纯c无法编译和使用，是说纯c不能编译和使用http模块，纯c模块包括base、event模块，相当于把libhv当做libevent、libuv使用
