### ISSUE TITLE
Please delete hconfig.h from git

### ISSUE THREAD

**Issue by gyohng** [ithewei/libhv#175]
Please delete hconfig.h from the repository and add it to .gitignore, as it gets in the way of using git. This file gets recreated (and thus changed from its git version) every time a compile of the library is made, and git reverts to the 'has local changes' status.

**Comment by ithewei** [comment]
I know that regenerating hconfig.h will lead to `has local changes` when `git fetch`, but some users may not run configure or cmake to generate hconfig.h, so I provide a default hconfig.h to avoid `not found header file`.
You can `git checkout hconfig.h` before `git fetch`.
