### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [ithewei/libhv#18]
Would you like to add more error handling for return values from functions like the following?
- [fwrite](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fwrite.html "Binary output") ⇒ [create_pidfile](https://github.com/ithewei/libhv/blob/01a0b90215a81828ca6141f3d7b3d363a4267209/utils/hmain.cpp#L301)
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [dns_unpack](https://github.com/ithewei/libhv/blob/7c34c3a7798eccfe812448a406667181e0b5fbd4/protocol/dns.c#L178)

**Comment by ithewei** [comment]
Thanks for your attention and suggestions, it has been processed.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/ithewei/libhv/commit/4e6fdf477aa8e655c8a23b2c454c76cafa35ea6e "handle compile warnings").

I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
