### ISSUE TITLE
系统校时是否会有影响

### ISSUE THREAD

**Issue by Layty** [ithewei/libhv#180]
在条件变量超时的这些api上,没有使用 pthread_condattr_setclock CLOCK_MONOTONIC,互斥量用的也是绝对时间,系统发生校时会有问题吗

**Comment by ithewei** [comment]
会的，使用这些带超时的mutex和条件变量应该小心点

**Comment by Layty** [comment]
我们的测试会验证校时, libhv是不是在这些情况下不能很好的工作

**Comment by ithewei** [comment]
libhv里没有使用到带超时的mutex和条件变量
