### ISSUE TITLE
多线程模式下readbuf的字节数问题

### ISSUE THREAD

**Issue by liuzhuan23** [ithewei/libhv#184]
ithewei 你好：

首先这个readbuf问题也许是我这里逻辑引起的，现象是readbytes在测试端将多个数据并行发过来的时候，
readbytes在一些时刻读入的字节数并不是我期待的字节数，反复查阅了你提供的资料，并未发现相关问题。

在测试one-acceptor-multi-workers模式中，在两端交互read/write中使用的是自己定的协议，每一段value有自己的边界，在on_recv这个cb中，多线程下readbuf会产生字节数不是期望字节数量问题，这个首先我和你确认下：

1：每一个loop中在on_recv这种cb内是否使用同一个readbuf?  

2：如果是自定义协议（类似0x01, 0xA1，0xAB......#），没有办法用你的UNPACK，在cb中（on_recv）内使用readbuf是否是唯一渠道？

3：hio_fd可以返回实际loop内的套接字句柄吗？

感谢

**Comment by ithewei** [comment]
1、每个loop有一个readbuf，没有调用hio_set_unpack设置拆包规则，该loop下的所有io是共用这一个readbuf的，所以on_recv时要求把回调上来的数据都处理完，如果调用了hio_set_unpack，是会alloc独立的readbuf的，因为需要缓存起来，等收到一个完整的包才回调上去；
2、目前支持的拆包规则就是固定包长、分界符、头部长度字段三种常见方式，其它不满足的自定义协议只能自己在on_recv后拆包；
3、hio_fd返回的就是socket创建出的fd；

**Comment by ithewei** [comment]
event目录下的代码不多，2k行左右，是libhv最核心的模块，建议读下源码，上述问答都可以自己找到答案

**Comment by liuzhuan23** [comment]
好的，谢谢
