### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [ithewei/libhv#19]
[An extra null pointer check is not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in macros like “[`SAFE_FREE`](https://github.com/ithewei/libhv/blob/c174588c4c43f8593c5c52c63f85eca9146345c7/base/hdef.h#L216 "Update candidate")”.

**Comment by ithewei** [comment]
Adding an if judgment will not affect the performance. I think it is a good code habit.

**Comment by elfring** [comment]
I disagree to this view.

**Comment by Libunko** [comment]
Agree with @elfring ，I think it's redundant too.
