### ISSUE TITLE
[Question] http response prase header missing the default domain,path?

### ISSUE THREAD

**Issue by luciouskami** [ithewei/libhv#192]
For example,the server set a cookie  but **without domain and path**,like:

```http
cookie=cookie123
```

And the response will give us:

```http
cookie=cookie123
```

The header doesn't contain the domain and path without setting them,it is a normal response as  usual as we did.

But in many development scenarios,we need to getting the **default domain and path**.

I 've checked the source code in "Http1Parser.cpp":

```cpp
//line 26
if (stricmp(header_field.c_str(), "Set-CooKie") == 0 ||
    stricmp(header_field.c_str(), "Cookie") == 0) {
    HttpCookie cookie;
    if (cookie.parse(header_value)) {
        parsed->cookies.emplace_back(cookie);
    }
}
```

It told me that libhv just parse Cookie's domain and path from response header.

I think it isn't enough,I suggest that we need to save the domain and path form request,if the response header haven't contained them,we can use the saved values.

Looking forward to your reply,thank you.

**Comment by ithewei** [comment]
Why don't you get the host and path directly from the request? It's easy to call `req->Host()` and `req->Path()`.

**Comment by luciouskami** [comment]
> Why don't you get the host (主机) and path (路径) directly (直接) from the request (请求) ? It's easy to call `req->Host()` and `req->Path()`.

Because the request is volatile,if you process  the response in a different workflow,the last rquest maybe detroyed and if you get a new response and want to reuse the cookies how did you know its request. It isn't a efficient way to cache the old requests

**Comment by ithewei** [comment]
```    
router.GET("/ping", [](HttpRequest* req, HttpResponse* resp) {
        return resp->String("pong");
});
```
One response have one request, the request is not volatile before you send response.

**Comment by luciouskami** [comment]
> ```
> router.GET("/ping", [](HttpRequest* req, HttpResponse* resp) {
>         return resp->String("pong");
> });
> ```
> 
> Every response has own request, the request is not volatile before you send response.

Sorry for not being clear enough, I'm talking about http client.

my code like this:

```cpp
http_headers get_req_headers;
get_req_headers["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36";
std::string v_get_url{ "https://example.com/get?param1=2&param2=3&args1=1,2,3&args2=4,5,6" };
auto get_resp = requests::get(v_get_url.c_str(), get_req_headers);
printf("domain: %s\n", get_resp->GetCookie("cookie").domain); //missing the default vaule

```

**Comment by ithewei** [comment]
Since the request is built by yourself, you can get host and path from the url.

**Comment by PhoenixZeng** [comment]
status of your guys
1."Must be standardized"
2."It's not that it doesn't work"

**Comment by ithewei** [comment]
So why don't you add domain and path to the cookie that your server responds to?

**Comment by luciouskami** [comment]
> So why don't you add domain and path to the cookie that your server responds to?

![1](https://user-images.githubusercontent.com/10268785/169653284-711d399b-57d2-4aea-94e3-31bece91c249.jpg)
Because they are optional.
I think it's a fault tolerance mechanism, it isn't possible so that we can be sure that everyone will add domain and path to their response.

**Comment by PhoenixZeng** [comment]
because of gateway / multi domain / Reverse Proxy / others
the server dont know where they are
Of cause , server can get it from uri. but less one do this.
eg. Java servlet STD Cookie constructs with 2 args (name, value)
