### ISSUE TITLE
项目是否可以移植到yocto或者openembedded中

### ISSUE THREAD

**Issue by dubw** [ithewei/libhv#195]
直接使用autotools或者cmake，直接放在 poky中增加bb文件，会报错

**Comment by ithewei** [comment]
我没有接触过yocto或者openembedded，没有对应的编译工具链，能提供下编译环境，以及把报错贴出来看看？

**Comment by IricBing** [comment]
这个肯定是可以的，我目前的linux环境就是基于yocto构建的，我将libhv作为三方包编译动态库进去，是完全没有问题的。
