### ISSUE TITLE
Can I use this project to perform port scanning?

### ISSUE THREAD

**Issue by WorstCodeWay** [ithewei/libhv#197]
I'm using this great project. But I wonder if it can be used to scan port.(tcp or udp) for servers.

If cannot do this, this may be a new feature. Will and when do you support this new feature?

**Comment by ithewei** [comment]
refer to [examples/nmap](https://github.com/ithewei/libhv/tree/master/examples/nmap)

**Comment by WorstCodeWay** [comment]
> refer to [examples/nmap](https://github.com/ithewei/libhv/tree/master/examples/nmap)

Thank you @ithewei . This project supplies me a lot exciting functions, it is the most fantastic work among I've used.

By the way, what is the meaning of '24' or '16' in command `nmap 192.168.x.x/16`

**Comment by WorstCodeWay** [comment]
Sorry, I find header including problem when doing as examples/nmap. Cannot find `netinet.h`, but I find it resides within base directory. However, I cannot find that directory or that header after I built and install `libhv` into my environment

**Comment by ithewei** [comment]
> doing

netinet.h mainly defines iphdr, tcphdr, udphdr, icmphdr, which are relatively low-level and are not used much, so they are not exported during installation. If you need to use them, you can copy them by yourself.

**Comment by WorstCodeWay** [comment]
Finally, I made it by copying all needed header files into my project. Thank you, @ithewei
