### ISSUE TITLE
kcp

### ISSUE THREAD

**Issue by TonyBeen** [ithewei/libhv#200]
问一下，我看kcp使用的是skywind300开源的ikcp，我看过这部分代码，觉得使用定时器调用ikcp_update和人为主动调用ikcp_input，这两个不在相同的线程，但是从ikcp中又没有看到互斥锁或原子操作，请问这个是否会有线程安全问题？

**Comment by TonyBeen** [comment]
因为我看好多人说kcp相比于tcp在网络不好的情况下性能稍高，举的例子也都是skywind3000的ikcp，但是又没有人提存在线程安全问题，所以想问下？解决我的困惑

**Comment by ithewei** [comment]
ikcp是存在线程安全问题的，在同一个线程内收发就不会有这种担忧了

**Comment by TonyBeen** [comment]
> ikcp是存在线程安全问题的，在同一个线程内收发就不会有这种担忧了

首先感谢您的回复。看了您的代码并加了些日志，确实是在一个线程内收发。
从代码中看到，定时器，事件等的回调也在这一个线程中处理，当IO多了以后，会增大回调处理时间，是否可能会因为未及时发送ACK导致对端在发一遍数据呢？
目前我自己也在写满足多IO的安全的KCP，具体就是一个主线程只管处理读写，回调交予线程池来处理，这样的想法可能过于简单，如果您有更好的建议，希望不吝赐教！

**Comment by ithewei** [comment]
kcp因为是基于udp的，只使用一个fd，所以一个IO线程收发就够了，用消费者线程池处理业务逻辑也是很合理的方式。
另外我建议能直接使用kcptun就直接使用kcptun，你自己的客户端和服务端都不需要感知kcp
