### ISSUE TITLE
http链接是怎么维护的？

### ISSUE THREAD

**Issue by Bates0000** [ithewei/libhv#206]
我看到http示例代码中没有connect操作直接就send了，这个连接状态是内部维护的吗？连接的超时，断线重连怎么做呢？是长链接吗？

**Comment by ithewei** [comment]
连接状态是内部维护的，同步和异步对于连接的管理方式不同，同步每个HttpClient对象拥有一个fd，异步每个HttpClient对象拥有一个EventLoop线程和连接池。
HTTP keepalive长连接请求，不会close，从而复用连接，当读写失败时（断链了），内部默认会重新连接并重试一次。
