### ISSUE TITLE
qt项目中，windows平台，引入libhv崩溃

### ISSUE THREAD

**Issue by kevinhwu** [ithewei/libhv#21]
今天（2020/11/18）上午的master分支代码，编译成dll(release)，引入到qt项目中，启动服务后，访问/hello崩溃。

代码如下：

`
int http_api_hello(HttpRequest* req, HttpResponse* res)
{
res->body = "hello";
return 0;
}

HttpService service;
service.AddApi("/hello", HTTP_GET, http_api_hello);

http_server_t server;
server.port = 8082;
server.service = &service;
http_server_run(&server);
`

环境：
qt creator 4.11.0
qt 5.9.9 build Desktop_Qt_5_9_9_MSVC2015_32bit
windows 10

报错：
![C4_2 J$5P8T7UAH}N0BLHGI](https://user-images.githubusercontent.com/7721398/99552469-00fad980-29f8-11eb-9d92-8a62385dc264.png)

callstack
![TV_ 293 $NU%P3$EI TSN)9](https://user-images.githubusercontent.com/7721398/99552515-0d7f3200-29f8-11eb-8bd0-b50c184501ea.png)

**Comment by kevinhwu** [comment]
`
int http_api_hello(HttpRequest* /*req*/, HttpResponse* res)
{
    res->body = "hello";
    return 0;
}
`

`
    HttpService service;
    service.AddApi("/hello", HTTP_GET, http_api_hello);

    http_server_t server;
    server.port = 8082;
    server.service = &service;
    http_server_run(&server);
`

**Comment by ithewei** [comment]
这个堆栈打印的很诡异，http_server_stop、hloop_post_event不主动调代码中是没有调用到的
建议使用debug库重新定位下，或者基于examples/httpd测试或调试
