### ISSUE TITLE
MQTT 启用重连之后，设备断网，无法实现重连

### ISSUE THREAD

**Issue by Bb-iot** [ithewei/libhv#213]
MQTT 启用重连之后，设备断网，无法实现重连，这也许与底层tcp的原理有关，请问后续是否会有优化？
After the MQTT reconnection is enabled, the device is disconnected from the network and cannot be reconnected. This may be related to the underlying tcp principle. Will there be any optimization in the future?

**Comment by Bb-iot** [comment]
我进行了日志打印，发现设备断网之后，心跳包的write 是正常的，应该是这里导致不会触发重连机制

**Comment by Bb-iot** [comment]
想了一下，MQTT心跳机制， 客户端这边断网，无法发送心跳，broker可以认为这个设备离线，为什么客户端这边得不到broker回复不能自动启动重连机制呢？

**Comment by ithewei** [comment]
嗯，应该几次没收到pong回应就主动关闭的
