### ISSUE TITLE
MqttClient 支持多线程吗？

### ISSUE THREAD

**Issue by jiephe** [ithewei/libhv#214]
我看例子代码里MqttClient连接之后，调用run()之后就进去内部循环了。如果这时候我想利用MqttClient publish一个消息，在其他线程里直接调用MqttClient.publish可以吗，还是说有其他方式可以进入到内部循环，在内部循环里publish

**Comment by ithewei** [comment]
publish接口是多线程安全的，在其它线程调用建议通过isConnected判断连上以后再调用

**Comment by jiephe** [comment]
好的
