### ISSUE TITLE
如何配置对http响应体进行gzip压缩？

### ISSUE THREAD

**Issue by alienzhangyw** [ithewei/libhv#215]
没有找到相关文档介绍。

**Comment by ithewei** [comment]
还没有接入各种解压缩库，你可以自行在`postprocessor`里压缩body，设置正确的`Content-Encoding`和`Content-Length`头

**Comment by alienzhangyw** [comment]
好的

**Comment by alienzhangyw** [comment]
参照这里的postporcessor使用（去掉//），结果打印出来的body一直是null，调试过程中body也一直是空的，这是为什么？
https://github.com/ithewei/libhv/blob/af3179a51ec23e1ed89a959d83526d017da59000/examples/httpd/handler.cpp#L55-L58

**Comment by ithewei** [comment]
postporcessor只对同步handler有效，此时异步handler还没有填充resp，如果你使用的异步handler只能在每个handler里填充body时处理了

**Comment by alienzhangyw** [comment]
> postprocessor只对同步handler有效，此时异步handler还没有填充resp，如果你使用的异步handler只能在每个handler里填充body时处理了

我这边当前确实是这样在每个handler里处理body的
