### ISSUE TITLE
I use websocket(wss) with ssl, send request to server, no response from server

### ISSUE THREAD

**Issue by shuisheng** [ithewei/libhv#216]
1. I have tow clients(websocket), as is A and B
2. A send request to server, tell server notify B to do something
3. B can receive message from server, then send message do something, and wait for response from server
4. I can see server reply response, but B cannot receive anything from server
5. then I send request to server, can receive response of last time send request
6. how to handle this? what reason? is it a bug?

**Comment by ithewei** [comment]
Sorry, I can't help with business problems, maybe you should use [examples/websocket_server_test.cpp](https://github.com/ithewei/libhv/blob/master/examples/websocket_server_test.cpp) and [examples/websocket_client_test.cpp](https://github.com/ithewei/libhv/blob/master/examples/websocket_client_test.cpp) to test.
