### ISSUE TITLE
can it run on Android?

### ISSUE THREAD

**Issue by maxlv7** [ithewei/libhv#22]

**Comment by ithewei** [comment]
Yes，it can.
Android ndk cross-compile see [BUILD.md](https://github.com/ithewei/libhv/blob/master/BUILD.md)

**Comment by maxlv7** [comment]
> Yes，it can.
> Android ndk cross-compile see [BUILD.md](https://github.com/ithewei/libhv/blob/master/BUILD.md)

ok thanks!
