### ISSUE TITLE
UDP时使用KCP会导致内存泄漏

### ISSUE THREAD

**Issue by hh-kai** [ithewei/libhv#220]
我在测试使用UDP server和client的时候，发现设置了setKcp，发送端在使用sendto时，会出现内存泄漏的情况，该怎么去释放这块内存。还有在使用udp发送数据的时候，很大的数据包，是否要拆分成小包，再使用sendto发送

**Comment by ithewei** [comment]
libhv里集成的kcp功能是有投入使用的（c++版本改写的kcptun，目前暂时没有开源出来），没有发现内存泄露。
你可以使用valgrind跑示例代码，如果有内存泄露会打印出来的。
udp发送数据，最好将每包大小限制到MTU以内（一般是1500）

**Comment by ithewei** [comment]
examples/nc可以作为kcp客户端测试的
```
valgrind bin/nc -k 127.0.0.1 1234
hello
close
```

**Comment by hh-kai** [comment]
如果设置了kcp，在使用sendto发送数据的时候（已经分包了1456），如果没有udp client，就会出现内存一直在涨。
不加kcp的udp，sendto就不会
后来我又用udp调试工具来测试（udp client不带kcp），虽然有收到数据，但是内存还是会涨。
还是说需要带kcp的udp client来接收

**Comment by ithewei** [comment]
双方都需要使用kcp来测试，kcp是ARQ协议，如果没有正确的应答，是会不断重传的，你不断sendto，kcp内部重传的队列就会不断增大，引起内存增长。

**Comment by hh-kai** [comment]
我用nc来测试 收不到数据 kcp的conv需要一样吗
![image](https://user-images.githubusercontent.com/19390025/179437488-8a645aa5-3297-42a6-95c3-c6489d7d17df.png)

**Comment by ithewei** [comment]
hv里的kcp测试步骤：
```
# 打开examples/udp_echo_server.c里的 #define TEST_KCP 1
./configure --with-kcp && make clean && make

# 启动kcp服务端
valgrind bin/udp_echo_server 1234

# kcp客户端
valgrind bin/nc -k 127.0.0.1 1234
hello
close
```

**Comment by hh-kai** [comment]
这个例子是直接发送文本的，我发送的是视频数据，一帧可能要分几百个包来发送，用的nc客户端来测试，就收到几个包，后面就没有了
![image](https://user-images.githubusercontent.com/19390025/179442186-fd58320d-1e84-4259-a354-db0db0f610eb.png)

**Comment by ithewei** [comment]
c++也只是c版本的封装，没有其他处理的，你要排查下服务端/客户端两边使用的kcp设置一致吗，exmaples/nc里是用的kcp_setting_init_with_normal_mode

**Comment by ithewei** [comment]
kcp默认的mtu是1400（kcp自身协议头部占用，所以是1500减去一些），你的分包数据不应该超过1400

**Comment by hh-kai** [comment]
我把包大小改为1356 
![image](https://user-images.githubusercontent.com/19390025/179453279-efe3ccc1-24f1-4f93-90de-c34678d738e5.png)
用的udp_echo_server 
数据是能收到，看着收的也挺快，但是内存还是在涨
又把数据改小了，一帧10个包不到，内存还是在缓慢的增长
![image](https://user-images.githubusercontent.com/19390025/179453725-0274b1f9-6b28-4bc9-b36d-bbb65e3ccd22.png)
两边的配置都是这样的
![image](https://user-images.githubusercontent.com/19390025/179453952-7dd06369-37ec-43b5-baa6-4cfa4a71a20f.png)

**Comment by ithewei** [comment]
不断发送内存有增长是正常的，只要在`hio_close_rudp(即ikcp_release)`或者对方收完后能恢复就是OK的。
具体可以分析下kcp源码，`hio_write（即hio_write_kcp -> ikcp_send）`不会立即发送，而是`ikcp_segment_new（即malloc）-> memcpy`后放入`kcp->snd_queue`发送队列里，然后`ikcp_update -> ikcp_output -> sendto`才会去发送，在`hio_handle_read -> hio_read_kcp -> ikcp_recv`收到ACK包后才会调用`ikcp_segment_delete（即free）`删除对应的消息并释放内存（一段时间没收到就会自动重传这个消息，所以在收到ACK前都不会释放这块内存），所以在发送后到还没收到ACK的这段时间里内存就会表现出增长。

**Comment by ithewei** [comment]
ikcp_xxx接口不是线程安全的（内部有队列但无锁），所以要求收发都在一个线程，在启用kcp的情况下，在其它线程直接调用hio_write不是线程安全的，有可能破坏ikcp的发送队列，可以使用hloop_post_event（c++版本就是loop->runInLoop）去投递一个发送事件

**Comment by hh-kai** [comment]
我试了用定时器结果也是一样的

**Comment by hh-kai** [comment]
更新了thread-safe
1. hio_write 现在返回的一直是0，但是收发数据是正常的
2. 内存还是在增长

**Comment by hh-kai** [comment]
我做了个测试 无线网络的情况下
1. kcp fast模式下 180k/sec 的情况下 比较稳定 normal模式或者其它fast模式就不行 而且内存不会增涨
2. 1M/sec 以上时，什么情况下都不能正常收发，并且内存会一直增涨

**Comment by ithewei** [comment]
kcp协议是使用快速重传的带宽换取低延时，如果丢包严重或者带宽不够就会导致待发送队列积压，内存不断增长

**Comment by hh-kai** [comment]
看了这个https://github.com/skywind3000/kcp/wiki/Flow-Control-for-Users
需要调整参数 以适应不同环境下的不同视频质量
这个问题就关闭了
