### ISSUE TITLE
How can a TcpClient disconnect from a TcpServer manually?

### ISSUE THREAD

**Issue by WorstCodeWay** [ithewei/libhv#221]
Hi, I've create a TcpClient instance with `hv::TcpClient`. By default, it can connect to a desired server by `createsocket`, but I want to connect or disconnect manually.  How can I achieve this while keep the created socket open (without using `close` function)?

**Comment by ithewei** [comment]
TcpClient::closesocket

**Comment by WorstCodeWay** [comment]
> Use `TcpClient::start` to startConnect Use `TcpClient::closesocket` to disconnect
@ithewei 
I've tried, but start failed connecting server.
Following are my steps and codes:

1. create socket
```
std::shared_ptr<hv::TcpClient> _client(new hv::TcpClient);
_client->createsocket(port, ip.c_str());
_client->start();
```
2. disconnect
```
_client->closesocket();
```
3. connect
```
_client->start();
``` 
When step 3rd is called, the client cannot connect to server

**Comment by ithewei** [comment]
Yes

**Comment by ithewei** [comment]
see TcpClient::setReconnect
