### ISSUE TITLE
异步http client请求是否支持指定事件线程

### ISSUE THREAD

**Issue by q191201771** [ithewei/libhv#228]
我想要的效果是多个http client用一个线程。
我看代码里AsyncHttpClient是每个对象内部弄了个事件线程。

感谢作者提供这么好的开源项目，祝你今天开心。

**Comment by ithewei** [comment]
没有暴露出AsyncHttpClient类，所以不能指定传人EventLoop。
但是HttpClient的sendAsync接口是多线程安全的，所以你直接使用一个HttpClient对象，就是只使用了一个内部事件循环线程，同理，你想使用几个线程就创建几个HttpClient对象就行。

**Comment by q191201771** [comment]
好的，非常全面的回答，我再调研看看第一种方法。
只要我需要的设置都能通过HttpRequest独立设置（而非HttpClient），应该就可以满足需求。

**Comment by q191201771** [comment]
后续是否考虑开放出相关的接口，考虑以下场景，http和websocket的客户端连接以及其他自定义协议共用事件线程。

**Comment by ithewei** [comment]
感谢你的建议，现在TcpClient、WebSocketClient等类确实都支持传入EventLoop，AsyncHttpClient后面也会考虑能传入EventLoop并暴露出来吧
