### ISSUE TITLE
请问作者websocket_server 如何限制客户端的数据长度？

### ISSUE THREAD

**Issue by cpp-user** [ithewei/libhv#230]
websocket_server open的时候可以获取headers吗？
websocket_server 默认使用的是one acceptor + multi threads 吗？
希望作者可以解答一下。

**Comment by ithewei** [comment]
1、没有限制客户端的数据长度，如果需要的话可以在[WebSocketParser.cpp](https://github.com/ithewei/libhv/blob/master/http/WebSocketParser.cpp)的on_frame_body里做限制；
2、没有暴露出headers，可以自行修改下这里的回调格式`ws_service->onopen(ws_channel, req->url);`
3、设置worker_threads设置IO线程数量，不是`one acceptor + multi threads`模式，是`multi acceptor`模式，由操作系统提供负载均衡；
