### ISSUE TITLE
unresolved symbols when build in static

### ISSUE THREAD

**Issue by Chrys4lisfag** [ithewei/libhv#231]
LNK2001_declspec(dllimport) public: __cdecl HttpRequest::HttpRequest(void)" (__imp_??0HttpRequest@@QEAA@XZ).	
__declspec(dllimport) public: virtual __cdecl HttpRequest::~HttpRequest(void)" (__imp_??1HttpRequest@@UEAA@XZ).
"__declspec(dllimport) public: virtual void __cdecl HttpRequest::Reset(void)" (__imp_?Reset@HttpRequest@@UEAAXXZ).

I build using mvsc visual studio.

**Comment by ithewei** [comment]
Add `HV_STATICLIB ` to precompiled macros to avoid hexport.h dllimport.
