### ISSUE TITLE
svg图片无法正确解析

### ISSUE THREAD

**Issue by IricBing** [ithewei/libhv#232]
使用提供好的httpd工具来部署vue项目，发现svg均无法加载起来，与原版对比，发现vue自带的预览功能里面svg图片类型为：svg+xml，如下所示：
![2022-08-08_18-08](https://user-images.githubusercontent.com/22849596/183394646-b3c7aa61-d9c5-42dd-9c8c-14791f3aea19.png)
使用httpd运行的vue项目无法加载svg图片，经对比，发现svg图片类型为：svg，不带xml，如下所示：
![2022-08-08_18-10](https://user-images.githubusercontent.com/22849596/183395127-de001bf6-d4d5-49fa-a5a9-06bd93c132b9.png)
临时解决方案：
修改http/httpdef.h文件，将
```c
XX(IMAGE_SVG,               image/svg,                svg)          \
```
修改为如下内容
```c
XX(IMAGE_SVG,               image/svg+xml,                svg)          \
```
编译通过后可正常加载svg图片。

**Comment by ithewei** [comment]
感谢反馈，方便的话你提个PR修复下吧

**Comment by IricBing** [comment]
> 感谢反馈，方便的话你提个PR修复下吧

好的，我没有权限提交，是需要先将我加入项目吗？

**Comment by ithewei** [comment]
> > 感谢反馈，方便的话你提个PR修复下吧
> 
> 好的，我没有权限提交，是需要先将我加入项目吗？

提PR是不需要权限的，可以自行百度学习下如何提交一个PR吧
