### ISSUE TITLE
默认支持ipv6

### ISSUE THREAD

**Issue by IricBing** [ithewei/libhv#238]
我使用示例中的`tinyhttpd`和`httpd`来构建自己的服务器，发现默认是不支持`ipv6`协议的，目前我是将`host`默认值从`0.0.0.0`修改为`::`是可以支持`ipv6`访问的，我更希望得到像Nginx那样通用服务器的支持方式，可以**同时支持**ipv4和ipv6

```code
$ netstat -lnt | grep 80
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN       
tcp6       0      0 :::80                   :::*                    LISTEN   **
```

**Comment by ithewei** [comment]
创建两个服务socket（ipv4和ipv6各一个），使用一套逻辑就可以的
```
hloop_create_tcp_socket(loop, “0.0.0.0”, port, on_accept);
hloop_create_tcp_socket(loop, “::”, port, on_accept);
```

**Comment by IricBing** [comment]
> 创建两个服务socket（ipv4和ipv6各一个），使用一套逻辑就可以了
> 
> ```
> hloop_create_tcp_server(loop, “0.0.0.0”, port, on_accept);
> hloop_create_tcp_server(loop, “::”, port, on_accept);
> ```

嗯嗯，好的
