### ISSUE TITLE
How does http client receive chunk data blocks?

### ISSUE THREAD

**Issue by loveCatCoder** [ithewei/libhv#240]
请问使用http异步客户端发送http请求，服务器使用chunk方式返回数据，怎么能回调收到每一个chunk块的数据。之前有个issue是说有个chunked_cb的回调，但现在最新代码上没有这个属性了。

**Comment by loveCatCoder** [comment]
use http_cb

**Comment by troycheng** [comment]
同样遇到这个问题，比如上游通过http sse返回数据，需要解析chunk数据的同时处理并发送给下游，写完之后才看到这个issue，早点看到能节省点时间。示例参见作者的wget实现：https://github.com/ithewei/libhv/blob/master/examples/wget.cpp
