### ISSUE TITLE
在linux gcc 4.8.5下，HttpHandler数据回调的崩溃报告

### ISSUE THREAD

**Issue by xwb1966** [ithewei/libhv#247]
OS: CentOS 7 64bits
gcc版本：4.8.5
现象：Http Server启动后，收到任意一包数据（合法的），均崩溃。
经过调试，发现崩溃点位于HttpHandler::initRequest()里，req->http_cb指向的lambda函数的onHeadersComplete()，调用这个函数后，这个lambda函数失效，导致访问后面的api_handler变量异常。
再跟踪下来，发现是onHeadlersComplete()中的 req->http_cb = NULL；这句导致的。我们浓缩一下这个代码，相当于：
req->http_cb = [this](....) {
    req->http_cb = NULL;    <-- 自己把自己干掉了，导致this无效
    if (api_headler ....) {...}
};

也许这与gcc编译器版本有关，在windows中这样的做法没有问题，linux的其它gcc版本我没有试过。是否可以想个其它办法避免这样做法？

**Comment by ithewei** [comment]
我在其它linux版本上确实没有这个问题，可以试试吧req->http_cb = NULL;放到最后一行

**Comment by xwb1966** [comment]
应该是版本问题。这个版本下，把 req->http_cb = NULL放最后没有用，因为它是在 onHeadersComplete()里调用的。
一个最简单的办法是加上一个this != NULL的判断：
void HttpHandler::initRequest() {
   ....
   req->http_cb = ... {
        if (...) {
             onHeaderComplete();         <-- 这里面清了 http_cb
        }
        if (this != nullptr && api_handler && api_handler->state_handler) {   <-- 修改这里：加上对 this的判断即可
              ....
        }
  }

gcc版本高应该没问题，估计是gcc的一个BUG。
