### ISSUE TITLE
iowatcher_poll_events

### ISSUE THREAD

**Issue by 244916896** [ithewei/libhv#250]
int **iowatcher_poll_events**(hloop_t* loop, int timeout) {
    epoll_ctx_t* epoll_ctx = (epoll_ctx_t*)loop->iowatcher;
    if (epoll_ctx == NULL)  return 0;
    if (epoll_ctx->events.size == 0) return 0;
    **int nepoll = epoll_wait(epoll_ctx->epfd, epoll_ctx->events.ptr, epoll_ctx->events.size, timeout);**
    if (nepoll < 0) {
        if (errno == EINTR) {
            return 0;
        }
        perror("epoll");
        return nepoll;
    }

    //原始
    // if (nepoll == 0) return 0;
    // int nevents = 0;
    // for (int i = 0; i < epoll_ctx->events.size; ++i) {
    //     struct epoll_event* ee = epoll_ctx->events.ptr + i;
    //     int fd = ee->data.fd;
    //     uint32_t revents = ee->events;
    //     if (revents) {
    //         ++nevents;
    //         hio_t* io = loop->ios.ptr[fd];
    //         if (io) {
    //             if (revents & (EPOLLIN | EPOLLHUP | EPOLLERR)) {
    //                 io->revents |= HV_READ;
    //             }
    //             if (revents & (EPOLLOUT | EPOLLHUP | EPOLLERR)) {
    //                 io->revents |= HV_WRITE;
    //             }
    //             EVENT_PENDING(io);
    //         }
    //     }
    //     if (nevents == nepoll) break;
    // }
    // return nevents;
    
    //修改
    for (int i = 0; i < nepoll; ++i) {
        struct epoll_event* ee = events_at(epoll_ctx->events.ptr,i);
        hio_t* io = loop->ios.ptr[ee->data.fd];
        if (io) {
            if (ee->events & (EPOLLIN | EPOLLHUP | EPOLLERR)) {
                io->revents |= HV_READ;
            }
            if (ee->events & (EPOLLOUT | EPOLLHUP | EPOLLERR)) {
                io->revents |= HV_WRITE;
            }
            EVENT_PENDING(io);
        }
    }
    return nepoll;
}

亲，你原始的好像没有利用epoll_wait即没有充分利用epoll的优点，应该修改成如上。由于我是没有详细看你的代码，帮忙看看我的使用是否正确，希望对你有帮助。欢迎讨论。

**Comment by ithewei** [comment]
两种写法应该都是一样的得吧，epoll_wait的结果都是保存在epoll_ctx->events里，原始写法里，while里有break，遍历够了事件也会跳出循环的，不会遍历整个数组的

**Comment by 244916896** [comment]
嗯，谢谢
