### ISSUE TITLE
如果一个程序发起多个http和websocket连接, 会有多个loop_thread线程吗?

### ISSUE THREAD

**Issue by jayden5414** [ithewei/libhv#252]
各种Client好像并没有设置loop的地方, 如果是线程的, 效率会比较低啊...

**Comment by franktz** [comment]
> TcpClient 、WebSocketClient构造函数都可以选择传入EventLoop的，AsyncHttpClient一个对象就是一个事件循环线程，可以多个连接公用一个client对象就行

如果其中一个TcpClient实例关闭了连接，是否会把EventLoop关闭，从而导致公用EventLoop的其他TcpClient异常退出？
