### ISSUE TITLE
win10 wingw编译总是出错

### ISSUE THREAD

**Issue by suzaichuan** [ithewei/libhv#255]
In file included from D:/work/svn/SV_NET_SDK130b220225/libhv-master/base/hplatform.h:303,
                 from D:\work\svn\SV_NET_SDK130b220225\libhv-master\event\hloop.h:5,
                 from D:\work\svn\SV_NET_SDK130b220225\libhv-master\event\iowatcher.h:4,
                 from D:\work\svn\SV_NET_SDK130b220225\libhv-master\event\poll.c:1:
e:\minigw\include\sys\time.h:106:53: note: declared here
  106 | int __cdecl __MINGW_NOTHROW __POSIX_2008_DEPRECATED gettimeofday
      |                                                     ^~~~~~~~~~~~
In file included from D:\work\svn\SV_NET_SDK130b220225\libhv-master\event\hevent.h:11,
                 from D:\work\svn\SV_NET_SDK130b220225\libhv-master\event\poll.c:6:
D:\work\svn\SV_NET_SDK130b220225\libhv-master\event\poll.c: In function 'pollfds_at':
D:/work/svn/SV_NET_SDK130b220225/libhv-master/base/array.h:53:19: error: invalid use of undefined type 'struct pollfd'
   53 |     return p->ptr + pos;\
      |                   ^
D:\work\svn\SV_NET_SDK130b220225\libhv-master\event\poll.c:18:1: note: in expansion of macro 'ARRAY_DECL'
   18 | ARRAY_DECL(struct pollfd, pollfds);
      | ^~~~~~~~~~

**Comment by ithewei** [comment]
mingw环境我是编译过的，上面报错你看看你的环境里`struct pollfd`是在哪个头文件声明的

**Comment by suzaichuan** [comment]
非常感谢ithewei，是WSAPoll中的，应该不是struct  pollfd的问题，
#ifdef OS_WIN
#define poll        WSAPoll
#endif

问题出在array.h 中 ARRAY_DECL中的“+”，如果加了强制转换char* 【return (char*)p->ptr + pos; 】此处编译不报错。我使用的是gcc-9.2.0。 具体原因还没找到。
