### ISSUE TITLE
how to remove the libhv in the system direction after a make install command?

### ISSUE THREAD

**Issue by fengmao31** [ithewei/libhv#260]
I need to remove libhv. because I need debug the source code.

**Comment by ithewei** [comment]
What does it mean to remove libhv?
Build debug type: 

`make BUILD_TYPE=DEBUG`
or
`cmake -DCMAKE_BUILE_TYPE=Debug`

**Comment by fengmao31** [comment]
It is same problem in another issues. I install the libhv in the system direction. and it affect my debug process. The websocket_client_test defaultly use the libhv in the system direction.

**Comment by fengmao31** [comment]
And I cannot find the install_manifest.txt in the libhv.

**Comment by ithewei** [comment]
sudo make uninstall
