### ISSUE TITLE
异步方式下在centos编译运行无响应

### ISSUE THREAD

**Issue by cmoth150415** [ithewei/libhv#261]
使用你在csdn上给出的例子，以下异步方式，在windows下可以正常编译，接收请求，但centos编译运行，无法接收请求，即使在hv::async前面打上log也无输出。

```c
router.POST("/echo", [](const HttpContextPtr& ctx) {
        // demo演示丢到hv::async全局线程池处理，实际使用推荐丢到自己的消费者线程/线程池
        hv::async([ctx]() {
            ctx->send(ctx->body(), ctx->type());
        });
        return 0;
    });
```

服务是用以下方式启动的（多进程）
```c
	hv::async::startup(2,10, 60000);

	// pidfile
	create_pidfile();

	// http_server
	Router::Register(g_http_service);
	g_http_server.registerHttpService(&g_http_service);
	g_http_server.run();
```

**Comment by ithewei** [comment]
多线程方式启动呢，因为多进程fork时并不会fork子线程，也就是hv::async线程池不会被fork过去

**Comment by cmoth150415** [comment]
我用代码里给的httpd例子编译测试了下，把以下接口做了改动
```c
    router.GET("/www.*", [](const HttpContextPtr& ctx) {
        hv::async([ctx](){
            ctx->send("ok");
        });
        return 0;
});
```
centos运行可以正常响应，而且这个例程也是多进程的。

后来发现如果在main函数中增加这条语句
hv::async::startup(2, 10, 60000);

centos下异步方式就不会响应了，去掉就可以，我自己代码去掉这条语句后也可以正常响应，不知道是什么原因？

**Comment by ithewei** [comment]
原因上面已经说了，这是写多进程程序需要注意的点，子线程不会被fork过去，所以需要先开多进程，然后再创建子线程。
`hv::async::startup(2, 10, 60000);`这条语句会创建线程池，如果是多进程程序，应该放到fork后，也就是`http_server_run`后，你的示例里可以放到`hv::async`前就行了。

**Comment by ithewei** [comment]
添加了onWorkerStart、onWorkerStop钩子，你可以在这里面调用hv::async::startup等初始化工作、hv::async::cleanup等清理工作
