### ISSUE TITLE
The websockets use NULL to make ctx to retry connection in the pause stage make it unsafe.

### ISSUE THREAD

**Issue by fengmao31** [ithewei/libhv#262]
You can see if you give the bad crt or key or ca file. at first, it check the server and refuses the connect. However, when it is in the HLOOP_STATUS_PAUSE stage, it will try to use the null to make ctx to connect. It can connect to the unsafe server.
why it have the three process? what is the three ssl come from?
![image](https://user-images.githubusercontent.com/19343842/190847120-f1b169bc-0b30-40f4-a3d0-381db68fa4c2.png)
![image](https://user-images.githubusercontent.com/19343842/190141056-872588e7-e087-40a8-afff-2e53d5da9c9e.png)
![image](https://user-images.githubusercontent.com/19343842/190141771-3b8f288f-7cb8-434e-a5f1-de26b730235f.png)

![image](https://user-images.githubusercontent.com/19343842/190142455-f9ef99ed-9e64-4bf9-9cc8-6e43c008a4dd.png)

**Comment by ithewei** [comment]
three ssl means:
io->ssl_ctx used if you call hio_set_ssl_ctx/hio_new_ssl_ctx for this io.
global g_ssl_ctx used if you call hssl_ctx_init.
else hssl_ctx_new used to new a SSL_CTX.

**Comment by fengmao31** [comment]
If the SSL_CTX_set_verify funtion refuse the connection because the ca.cert cannot pass the certificate. The websocket will new a SSL_CTX(null) to buid a connection. It is not reasonable. The false server still can get the data from our client.

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/190304305-c55d1449-87fe-48b6-ab52-fc624415a23e.png)
In the picture, you can find the ca is not right and the client cannot check the server and refuse the connection. The server is illegal server. But our client still connect to the server and exchange the data in the websocket PAUSE stage.
The first ssl and the second ssl is empty. I use the websocket_server_test and websocket_client_test to test it. And add the opt file in the WebsocketClient.cpp file.

**Comment by ithewei** [comment]
You can call ws.withTLS(ssl_opt)，that is `TcpClient::withTLS` to set these options.

**Comment by ithewei** [comment]
Or use hssl_ctx_init to set global ssl options.

**Comment by fengmao31** [comment]
I set it and give the false Ca.crt. The program refuse the handshark because it is not safe server. but the websocket will start to build a new null ctx to build a set_verify_None connect the server and success to the unsafe server.

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/190367216-421524dd-07de-444a-8842-36582c089241.png)

I use this way to set global ssl options to stop the null ctx connect. the null connect will use the default SSL_VERIFY_NONE. And this way to set the withTLS(&opt) will not change libhv.so built from your source code .

**Comment by fengmao31** [comment]
Or I can stop the websocket conect in the first onclose function. But it is strange for websocket.

**Comment by ithewei** [comment]
Do you mean that not use your ssl_ctx_opt when reconnect?
Please break point at
https://github.com/ithewei/libhv/blob/c8e33fdc2b09c619f85cec8fd1f05289c30f016a/evpp/TcpClient.h#L88

**Comment by fengmao31** [comment]
I add the breakpoint  in the hssl_new_ctx function. 
I want the client to check the server's certification. and refuse the unsafe server. I give the peer mode and wrong ca file in the opt. the file is not exist.
at first, it cannot read the ca file and free the ctx. It should stop to connect. but it go to the some special status.
![image](https://user-images.githubusercontent.com/19343842/190845827-51ad77ea-adb1-4720-bd0c-c0fdd9313b6d.png)
then it looks like to go the PAUSE status. and try to check the three ctx to retry the ssl_connect. in this time, it use the NULL to build ctx and it success to use None mode to build the communication with the server. but maybe the server is a false server to Stealing data. 
![image](https://user-images.githubusercontent.com/19343842/190845810-db00bf53-2f66-46c6-96e6-27891555d468.png)
![image](https://user-images.githubusercontent.com/19343842/190846151-addbc1ae-6c16-4543-a39d-93bd68e5d8b6.png)

**Comment by fengmao31** [comment]
I am sorry for I updating the wrong picture to make you confuse at first.  It is the break point. It can arrive it in the first connect. 
![image](https://user-images.githubusercontent.com/19343842/190847239-20b98b67-3e6b-448c-b088-22e569fa7bce.png)

**Comment by fengmao31** [comment]
This issue did not solved.
