### ISSUE TITLE
The program use the TCPClient.h in the evvp file rather than the TCPClient in the include file when doing the debug in the source code.

### ISSUE THREAD

**Issue by fengmao31** [ithewei/libhv#263]
I try to change the source code in the CMake compile mothed.
And I find the the program use the TCPClient.h in the evvp file rather than the TCPClient in the include file. If someone changes the source code and try to make and make install, it maybe cause some problem.

**Comment by ithewei** [comment]
The include folder is copied by the installation and should not be modified. If you need to modify the source code, you should modify the original directory.

**Comment by fengmao31** [comment]
If I change some function in the .h file in the evvp direction, when I make and make install. It will install the old version in the include direction rather than the evvp direction.
