### ISSUE TITLE
通过vcpkg和xmake使用的话貌似缺失了部分头文件

### ISSUE THREAD

**Issue by heheda123123** [ithewei/libhv#267]
在用 xmake 的时候发现的
https://github.com/xmake-io/xmake-repo/issues/1492

然后本地看了下vcpkg ，发现也有同样的问题，在 本地的目录下
```
vcpkg\installed\x64-windows-static\include\hv
```
也没有`array.h` `list.h` `queue.h` 这类文件
他们都是调用libhv自身的CMakeLists.txt构建的。
这是有意不包含那几个数据结构还是漏掉了呢。
如果不算libhv的base头文件，那就不应该放在这个目录下把。比如只有例子用到，应该单独放例子目录下吧

**Comment by ithewei** [comment]
`array.h list.h queue.h`这几个头文件为内部使用的数据结构，有意没有导出，如果你在外部需要使用，可以自行拷贝过去。
