### ISSUE TITLE
下载文件大小超过2G抛异常

### ISSUE THREAD

**Issue by wsliangchen** [ithewei/libhv#271]
content-length 超过int最大值时
on_headers_complete函数中使用atoi导致int类型的中间变量溢出
对string revers一个负值，由此引申出来的问题，代码中一些结构体定义类型用size_t导致win平台下32/64位表现不一致
![PX@MHM_AW7IT))WFDVF$(D](https://user-images.githubusercontent.com/38786312/191159754-0b983b4b-4b6b-411a-a7b2-84ace34d13fe.jpg)

**Comment by ithewei** [comment]
https://github.com/ithewei/libhv/commit/08d6130162f21f3a4031ebfb573779d05aefee44

**Comment by ithewei** [comment]
统一用了size_t定义，不考虑32位下超过4G问题
