### ISSUE TITLE
文件下载中文文件名解析错误

### ISSUE THREAD

**Issue by movbx** [ithewei/libhv#274]
httpd服务端
文件地址：downloads/img/购买说明.jpg
资源地址：http://localhost:8080/downloads/img/购买说明.png
请求地址：http://localhost:8080/downloads/img/%E8%B4%AD%E4%B9%B0%E8%AF%B4%E6%98%8E.png
请求404错误，地址无效
HV给出地址：http://localhost:8080/downloads/img/%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%CB%B5%EF%BF%BD%EF%BF%BD.png
请求404错误，地址无效

请问下载中文文件名的文件应该如何处理？

**Comment by ithewei** [comment]
不同系统注意unicode和utf8编码问题，转成fopen能打开的系统编码，再进行url转义
