### ISSUE TITLE
vcpkg中的lihbv静态库用不了

### ISSUE THREAD

**Issue by heheda123123** [ithewei/libhv#276]
https://github.com/microsoft/vcpkg/issues/26777
看vcpkg那边挂了很久issue也没处理，这个当初是作者自己提交的吗？

**Comment by ithewei** [comment]
添加预编译宏HV_STATICLIB, 参考
https://github.com/ithewei/libhv/wiki/%E4%B8%AD%E6%96%87FAQ#2%E9%9D%99%E6%80%81%E5%BA%93%E5%A3%B0%E6%98%8E%E5%AE%8Fhv_staticlib--%E9%9D%99%E6%80%81%E5%BA%93hv_staticlib
