### ISSUE TITLE
Why not using new form of C compatibility headers ?

### ISSUE THREAD

**Issue by zhanyuzhang** [ithewei/libhv#28]
There are many C compatibility headers in the project ,  for example:
```
#include <assert.h> // for assert
#include <stddef.h> // for NULL
#include <stdlib.h> // for malloc,realloc,free
#include <string.h> // for memset,memmov
```

I'm confused why not using c prefix header, as follows : 
```
#include <cassert> // for assert
#include <cstddef> // for NULL
#include <cstdlib> // for malloc,realloc,free
#include <cstring> // for memset,memmov
```

I'm a new c++ beginer , and I learn that we should use the second form， beacuse the `xx.h` is deprecated:

![image](https://user-images.githubusercontent.com/12018876/100875915-a24a5b00-34e1-11eb-9973-627f6e4d4b55.png)

referece to: https://en.cppreference.com/w/cpp/header

**Comment by ithewei** [comment]
<string.h> is c header, <cstring> is c++ header of using namespace std.
libhv base,event modules writen by c. Use c header is more compatible.
