### ISSUE TITLE
Built under cygwin installed on Windows 10

### ISSUE THREAD

**Issue by westsuhanic** [ithewei/libhv#283]
Hello:

I built your work under cygwin which is installed on a completely updated Windows 10 machine.
I just got a bunch of warnings about building on an unsupported platform.
I also ran some of the examples and contacted them via some of my react apps.

thanks and good work.

west suhanic

**Comment by ithewei** [comment]
The warning comes from [hplatform.h](https://github.com/ithewei/libhv/blob/master/base/hplatform.h), can you add your platfrom macro to fix it？
