### ISSUE TITLE
some time http client will connect error

### ISSUE THREAD

**Issue by hgyxbll** [ithewei/libhv#286]
code like below:

```c++
  hv::HttpServer server;
  server.setPort(1234);
  server.setThreadNum(0);
  server.start();
//sleep(1ms) <-  if add sleep, it will ok
hv::HttpClient cl("127.0.0.1",1234);
cl.setTimeout(200);
cl.send(...)
```

sometime it will fail at below:
hsocket.c(ConnectFDTimeout):
    if (getsockopt(connfd, SOL_SOCKET, SO_ERROR, (char*)&err, &optlen) < 0 || err != 0) {
        goto error;   <- it will go to here, and the err is 61, the errno is 36(EINPROGRESS)
    }

if i add the sleep after server start, it will ok.

OS: MacOS 11.7 Intel

**Comment by ithewei** [comment]
server.start() is non-blocking, the thread will be started internally, and then start to listen and accept. 
If you access it immediately, the server may not work yet.

**Comment by hgyxbll** [comment]
> server.start() is non-blocking, the thread will be started internally, and then start to listen and accept. If you access it immediately, the server may not work yet.
got it. thanks.
