### ISSUE TITLE
conan package

### ISSUE THREAD

**Issue by youngday** [ithewei/libhv#287]
could not find it in conan.io packages ,waiting for it in conan.io

**Comment by franktz** [comment]
好像现在conan-center不能上传了，有谁知道地址说一下，我们可以自己编译推上去

**Comment by youngday** [comment]
https://github.com/conan-io/conan-center-index，是否是这个呢？

**Comment by franktz** [comment]
楼上是源代码不是公网库。以前可以通过注册为他们网站的用户，然后登录用户上传的，现在找不到上传入口。

**Comment by youngday** [comment]
改用xmake了，更方便，多谢!
