### ISSUE TITLE
ifconfig功能能否提供gateway得ip信息

### ISSUE THREAD

**Issue by opt-liang** [ithewei/libhv#290]
typedef struct ifconfig_s {
    char name[128];
    char ip[16];
    char mask[16];
    char broadcast[16];
    char gateway[16];
    char mac[20];
} ifconfig_t;
类似这样。

**Comment by opt-liang** [comment]
建议哈，刚好用到需要gateway信息

**Comment by ithewei** [comment]
ifconfig很久前写的了，不太记得如何获取gateway了，欢迎提PR加上

**Comment by opt-liang** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月29日(周六) 晚上11:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ithewei/libhv] ifconfig功能能否提供gateway得ip信息 (Issue #290)




 
ifconfig很久前写的了，不太记得如何获取gateway了，欢迎提PR加上
