### ISSUE TITLE
how to create a https server

### ISSUE THREAD

**Issue by MajidAbdelilah** [ithewei/libhv#291]
i am very new to server development and i want my server address to be https instead of http so how to do this
i dont know but i think this may need something to do with the ssl library 
i can see in the api this function ``` hloop_create_ssl_server ``` i have used it and nothing happened so can you show me what to do
ths is my code

```

static void on_accept(hio_t* io) {
    hio_detach(io);

    hloop_t* worker_loop = get_next_loop();
    hevent_t ev;
    memset(&ev, 0, sizeof(ev));
    ev.loop = worker_loop;
    ev.cb = new_conn_event;
    ev.userdata = io;
    hloop_post_event(worker_loop, &ev);
}

static HTHREAD_ROUTINE(worker_thread) {
    hloop_t* loop = (hloop_t*)userdata;
    hloop_run(loop);
    return 0;
}

static HTHREAD_ROUTINE(accept_thread) {
    hloop_t* loop = (hloop_t*)userdata;
    hio_t* listenio = hloop_create_tcp_server(loop, host, port, on_accept);
    if (listenio == NULL) {
        exit(1);
    }
    printf("tinyhttpd listening on %s:%d, listenfd=%d, thread_num=%d\n",
            host, port, hio_fd(listenio), thread_num);
    // NOTE: add timer to update date every 1s
    htimer_add(loop, update_date, 1000, INFINITE);
    hloop_run(loop);
    return 0;
}

int main(int argc, char** argv) {
	fp = fopen("./video.mp4", "w");
	
	if (argc < 2) {
        printf("Usage: %s port [thread_num]\n", argv[0]);
        return -10;
    }
    port = atoi(argv[1]);
    if (argc > 2) {
        thread_num = atoi(argv[2]);
    } else {
        thread_num = get_ncpu();
    }
    if (thread_num == 0) thread_num = 1;

    worker_loops = (hloop_t**)malloc(sizeof(hloop_t*) * thread_num);
    for (int i = 0; i < thread_num; ++i) {
        worker_loops[i] = hloop_new(HLOOP_FLAG_AUTO_FREE);
        hthread_create(worker_thread, worker_loops[i]);
    }
	
    accept_loop = hloop_new(HLOOP_FLAG_AUTO_FREE);
    accept_thread(accept_loop);
    return 0;
}

```
thank you in advance

**Comment by ithewei** [comment]
c++ refer to [examples/http_server_test.cpp](https://github.com/ithewei/libhv/blob/master/examples/http_server_test.cpp)
`hio_new_ssl_ctx(listenio, ssl_opt); ` for c

**Comment by MajidAbdelilah** [comment]
i am using c
so after creating the ssl certificate and calling  ```hio_new_ssl_ctx()``` should i call ``` hloop_create_tcp_server ``` or ``` hloop_create_ssl_server ```

**Comment by MajidAbdelilah** [comment]
also i added a new cert to the bin folder at libhv/bin/cert/ and i run the  [examples/http_server_test.cpp](https://github.com/ithewei/libhv/blob/master/examples/http_server_test.cpp) executable and it gives me this 
![Screenshot from 2022-10-29 17-50-35](https://user-images.githubusercontent.com/98910419/198843494-c74c3995-878f-43e3-ae92-c412630c8668.png)
connection is not secure 
and when i try to change http to https it give me this
![Screenshot from 2022-10-29 17-51-57](https://user-images.githubusercontent.com/98910419/198843542-5da542e3-fbd4-4c89-b6ca-66747022e617.png)
and when i try to access it through the port described in the cpp file for https(8443)
it give me this 
![Screenshot from 2022-10-29 17-53-33](https://user-images.githubusercontent.com/98910419/198843604-9786e3b1-11e3-486e-95f4-782897e15116.png)

**Comment by MajidAbdelilah** [comment]
also this with ```bin/curl -v https://127.0.0.1:8443/ping```
![Screenshot from 2022-10-29 18-05-30](https://user-images.githubusercontent.com/98910419/198844195-94aca388-947d-46da-ab07-e54277b00c81.png)

**Comment by MajidAbdelilah** [comment]
oh i am sorry sorry it was my fault
the cpp example is working now

**Comment by MajidAbdelilah** [comment]
now it is telling me this 
![Screenshot from 2022-10-29 18-19-02](https://user-images.githubusercontent.com/98910419/198844798-193a4319-fbb1-475a-a4e4-63d82b61b4d6.png)

although curl works fine

**Comment by MajidAbdelilah** [comment]
ah okay i need to buy a trusted cert okay its okay
