### ISSUE TITLE
how to set up sertbot with server

### ISSUE THREAD

**Issue by MajidAbdelilah** [ithewei/libhv#293]
i have a problem i want to use certbot for a free trusted ssl cert and i am getting errors
i have this domain `video2vid.tk` linked to my server address and when i run `sudo certbot certonly --webroot --preferred-challenges http -d www.video2vid.tk -d video2vid.tk` i am getting these errors 
```
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: video2vid.tk
  Type:   dns
  Detail: no valid A records found for video2vid.tk; no valid AAAA records found for video2vid.tk

  Domain: www.video2vid.tk
  Type:   dns
  Detail: no valid A records found for www.video2vid.tk; no valid AAAA records found for www.video2vid.tk

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

Some challenges have failed.

```
i am sorry for asking an unrelated subject to libhv but other freamworks like apache already have built in function to get up and running in certbot,
and i appreciate you help 
thanks in advance

**Comment by MajidAbdelilah** [comment]
![image](https://user-images.githubusercontent.com/98910419/199341850-f28d3b27-a31c-43d5-88cc-cd3d99350ba4.png)

**Comment by MajidAbdelilah** [comment]
oh i found the problem libhv is listening on a local ip, but it doesnt want to run on my public ip `Cannot assign requested address`
do you know how to fix this problem i am using linux

**Comment by ithewei** [comment]
`sudo netstat -tanp | grep LISTEN`
and to see if you are already listening on 0.0.0.0:port

**Comment by MajidAbdelilah** [comment]
when i try to listen for 0.0.0.0:80 is surly does but when i try to listen for my public ip(for example 103.50.2.233) libhv says `bind: Cannot assign requested address`
