### ISSUE TITLE
In file 'hmutex.h' about sem_timedwait function existence an error

### ISSUE THREAD

**Issue by liutt1312** [ithewei/libhv#295]
// true:  OK
// false: ETIMEDOUT
static inline int hsem_wait_for(hsem_t* sem, unsigned int ms) {
#if HAVE_SEM_TIMEDWAIT
    struct timespec ts;
    timespec_after(&ts, ms);
    return sem_timedwait(sem, &ts) != ETIMEDOUT;

if 'sem_timedwait' success, return value is 0;
if 'sem_timedwait' timeout, errno is set to ETIMEDOUT

**Comment by ithewei** [comment]
这里的int返回值可以看作bool，1表示成功，0表示失败
