### ISSUE TITLE
WebSocketClient.stop(true)偶发性陷入一直等待的状态

### ISSUE THREAD

**Issue by franktz** [ithewei/libhv#296]
在某种未知情况下（多线程但不一定是高并发），调用 WebSocketClient.stop(true)会陷入一直等待的状态。WebSocketClient并未共用EventLoop，每个WebSocketClient都会创建一个EventLoop。
查看源码发现hloop.c文件 481行
`int hloop_stop(hloop_t* loop) {
    if (hv_gettid() != loop->tid) {
        hloop_wakeup(loop);
    }
    loop->status = HLOOP_STATUS_STOP;
    return 0;
}`
是否需要把`loop->status = HLOOP_STATUS_STOP;`移到函数入口以保证唤醒后的线程可以立即退出？或者是其他什么原因会导致一直等待？

![Snipaste_2022-11-03_11-18-32](https://user-images.githubusercontent.com/6367123/199641549-f45bf745-c557-4068-b9a7-2eabe2e610f0.jpg)

**Comment by ithewei** [comment]
hloop_stop不会导致无法退出的，就算hloop_wake后，loop thread马上唤醒，错过了STOP状态，IO多路复用的阻塞时间设置的最大100ms，100ms后也会再次醒来，判断是否STOP的，而将loop->status = HLOOP_STATUS_STOP放到入口处，可能导致loop释放了，再调用hloop_wake就会野指针崩溃的。

**Comment by franktz** [comment]
那就奇怪了，实际使用过程中确实会陷入，堆栈如截图。还有哪些情况可能触发陷入吗？

**Comment by ithewei** [comment]
这个堆栈是调用者线程的，得看事件循环线程的
