### ISSUE TITLE
Untested platform message

### ISSUE THREAD

**Issue by westsuhanic** [ithewei/libhv#297]
Hello:

I just downloaded the code zip file and tried building the code again.
I still get the untested platform message. My platform is cygwin running under windows 10.
In order to detect if the platform is either Linux, Mac or Cygwin I suggest that you some how us the command "uname -s"
I know under cygwin, I can detect WIN32 in cmake

thank you for your work.

**Comment by ithewei** [comment]
You can try add OS platfrom marco to base/hplatform.h to fix it, then new PR if test ok.
