### ISSUE TITLE
hv::parse_multipart can't parse upload chunk file

### ISSUE THREAD

**Issue by JhonAir** [ithewei/libhv#299]
1、when upload big file need chunk , hv::parse_multipart function can't parse two parts (because body is not end whit boudary ), I add boundary when first chunk , it will be parse ok. is this need application to pack body to parse?

**Comment by ithewei** [comment]
You can use original multipart_parser to streaming parsing.

**Comment by JhonAir** [comment]
when receive big file the state is body, I used hv::parse_multipart function to parse data it happened. Is I use function error on wrong way  or to use anoher parse_part fuction to handle it?Jhon 在 2022年11月10日，19:55，ithewei ***@***.***> 写道：﻿
You can use original multipart_parser to streaming parsing.

**Comment by ithewei** [comment]
refer to https://github.com/iafonov/multipart-parser-c
