### ISSUE TITLE
window10+VS2017+cmake编译出错

### ISSUE THREAD

**Issue by litterCooker** [ithewei/libhv#30]
我在window10+VS2017+cmake平台上使用了
mkdir win64
cd win64
cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release
cmake --build .
编译，结果报错
fatal error C1083: Cannot open include file: 'stdatomic.h': No such file or directory 
我需要有什么额外设置嘛？

**Comment by ithewei** [comment]
vs用命令行编译需要初始化指定的命令行环境
建议cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release后，
直接使用VS打开hv.sln进行编译

**Comment by litterCooker** [comment]
cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release这句话就报错了

**Comment by litterCooker** [comment]
hv.sln都木有生成

**Comment by ithewei** [comment]
cmake如何生成vs工程可自行百度下
