### ISSUE TITLE
How to use libhv with wss (websockets secure)

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [ithewei/libhv#303]
I found no example considering websockets secure. How would I get a websockets client up and running using mbedtls for TLS encryption?

**Comment by ithewei** [comment]
`./configure --with-mbedtls && make clean && make`
refer to [examples/websocket_server_test.cpp](https://github.com/ithewei/libhv/blob/master/examples/websocket_server_test.cpp ) and [examples/websocket_client_test.cpp](https://github.com/ithewei/libhv/blob/master/examples/websocket_client_test.cpp)

**Comment by MartyMcFlyInTheSky** [comment]
Thanks I saw that but I can't see how I would load a trusted roots certificate bundle for example :)

**Comment by MartyMcFlyInTheSky** [comment]
Thank you. Is there any more documentation (in english) somewhere?

**Comment by ithewei** [comment]
Just https://github.com/ithewei/libhv/wiki/FAQ
