### ISSUE TITLE
vs2008不支持 怎么解决！

### ISSUE THREAD

**Issue by freedomcoming** [ithewei/libhv#305]
vs2008不支持 怎么解决！求助！

**Comment by ithewei** [comment]
需要支持c++11的编译器，除非你只编译使用c接口模块

**Comment by ithewei** [comment]
https://github.com/ithewei/libhv/wiki/%E4%B8%AD%E6%96%87FAQ#qwindows%E4%B8%8B%E7%BC%96%E8%AF%91%E4%B8%8D%E8%BF%87
