### ISSUE TITLE
Compilation error x86_64-w64-mingw32

### ISSUE THREAD

**Issue by alexiskhoury** [ithewei/libhv#309]
I have the following compilation error after issuing the ./configure and make clean followed by make libhv:

<base/hbase.c:263:17: error: storage size of 'st' isn't known
  263 |     struct stat st;>

Any idea how to solve it? Alternatively, do you have pre-complied binaries for x86_64-w64-mingw32?

Thanks.

**Comment by ithewei** [comment]
https://github.com/ithewei/libhv/blob/master/BUILD.md#mingw
Do you export CROSS_COMPILE then ./configure ?
Check `#define HAVE_SYS_STAT_H 1` in hconfig.h

**Comment by alexiskhoury** [comment]
Thanks for your prompt reply. Fllowing your comments, the compilation process did not succeed. However, the compilation was successful when I used cmake, but got the following warning:

`C:\Users\JV5599\Downloads\libhv-1.3.0\libhv-1.3.0\base\hsocket.c: In function 'Socketpair':
C:\Users\JV5599\Downloads\libhv-1.3.0\libhv-1.3.0\base\hsocket.c:344:36: warning: overflow in conversion from 'long long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Woverflow]
  344 |     listenfd = connfd = acceptfd = `INVALID_SOCKET;`

Moreover, some examples did not compile with the following errors (linked to multiple definitions of pthread):

`C:\w64devkit\bin/ld.exe:` c:/w64devkit/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x178): multiple definition of `pthread_mutex_lock'; ../lib/libhv.dll.a(libhv_dll_d006080.o):(.text+0x0): first defined here
C:\w64devkit\bin/ld.exe: c:/w64devkit/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x1cf): multiple definition of `pthread_mutex_unlock'; ../lib/libhv.dll.a(libhv_dll_d006083.o):(.text+0x0): first defined here
C:\w64devkit\bin/ld.exe: c:/w64devkit/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x2a0): multiple definition of `pthread_mutex_destroy'; ../lib/libhv.dll.a(libhv_dll_d006078.o):(.text+0x0): first defined here
C:\w64devkit\bin/ld.exe: c:/w64devkit/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x344): multiple definition of `pthread_mutex_init'; ../lib/libhv.dll.a(libhv_dll_d006079.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status`

**Comment by ithewei** [comment]
可能是你的mingw环境问题，libhv是在mingw下编译通过的，也有很多群友使用mingw编译过libhv的

**Comment by hlizard** [comment]
> Thanks for your prompt reply. Fllowing your comments, the compilation process did not succeed. However, the compilation was successful when I used cmake, but got the following warning:
> 
> `C:\Users\JV5599\Downloads\libhv-1.3.0\libhv-1.3.0\base\hsocket.c: In function 'Socketpair': C:\Users\JV5599\Downloads\libhv-1.3.0\libhv-1.3.0\base\hsocket.c:344:36: warning: overflow in conversion from 'long long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Woverflow] 344 | listenfd = connfd = acceptfd = `INVALID_SOCKET;`
> 
> Moreover, some examples did not compile with the following errors (linked to multiple definitions of pthread):
> 
> `C:\w64devkit\bin/ld.exe:` c:/w64devkit/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x178): multiple definition of `pthread_mutex_lock'; ../lib/libhv.dll.a(libhv_dll_d006080.o):(.text+0x0): first defined here C:\w64devkit\bin/ld.exe: c:/w64devkit/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x1cf): multiple definition of `pthread_mutex_unlock'; ../lib/libhv.dll.a(libhv_dll_d006083.o):(.text+0x0): first defined here C:\w64devkit\bin/ld.exe: c:/w64devkit/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x2a0): multiple definition of `pthread_mutex_destroy'; ../lib/libhv.dll.a(libhv_dll_d006078.o):(.text+0x0): first defined here C:\w64devkit\bin/ld.exe: c:/w64devkit/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x344): multiple definition of `pthread_mutex_init'; ../lib/libhv.dll.a(libhv_dll_d006079.o):(.text+0x0): first defined here collect2.exe: error: ld returned 1 exit status`

me too, also(and only) w64devkit:
```
:\raylib\w64devkit\bin>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
Target: i686-w64-mingw32
Configured with: /gcc-11.2.0/configure --prefix=/w64devkit --with-sysroot=/w64devkit --target=i686-w64-mingw32 --host=i686-w64-mingw32 --with-arch=pentium4 --enable-static --disable-shared --with-pic --with-gmp-include=/deps/include --with-gmp-lib=/deps/lib --with-mpc-include=/deps/include --with-mpc-lib=/deps/lib --with-mpfr-include=/deps/include --with-mpfr-lib=/deps/lib --enable-languages=c,c++ --enable-libgomp --enable-threads=posix --enable-version-specific-runtime-libs --disable-dependency-tracking --disable-multilib --disable-nls --enable-mingw-wildcard CFLAGS_FOR_TARGET=-Os CXXFLAGS_FOR_TARGET=-Os LDFLAGS_FOR_TARGET=-s CFLAGS=-Os CXXFLAGS=-Os LDFLAGS=-s
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (GCC)

```
