### ISSUE TITLE
How to pause/resume the read of hio?

### ISSUE THREAD

**Issue by clcarwin** [ithewei/libhv#31]
Sometimes we do not want to receive data too fast. If delete ```hio_done(io)``` in the funtion ```hio_del```, we can use ```hio_del(io,HV_READ)``` to pause, and use ```hio_read(io)``` to resume.

Can we pause/resume hio by this method?

Thanks.

**Comment by ithewei** [comment]
I almost forgot the original intention of hio_del interface, thanks for reminding.

**Comment by clcarwin** [comment]
Thanks for the excellent project!
