### ISSUE TITLE
WITH_OPENSSL 应该增加自动切换/MT库的切换

### ISSUE THREAD

**Issue by zhaokaixs** [ithewei/libhv#312]

**Comment by ithewei** [comment]
怎么个自动切换法，openssl需要你自己安装的

**Comment by zhaokaixs** [comment]
![image](https://user-images.githubusercontent.com/7833585/204137227-f3d855e3-70c6-45e7-b36c-d4cb090f2e99.png)

**Comment by ithewei** [comment]
这个是find_package(OpenSSL)自动找到的吧，所以这个值取决于你安装的openssl是用了什么，没法自动去切换，纵观其它使用了openssl的库的cmake里也没有自动切换的逻辑

**Comment by zhaokaixs** [comment]
嗯 我尝试了一下 如果使用/MT的话
可以这么写
if(WITH_OPENSSL)
    set(OPENSSL_USE_STATIC_LIBS TRUE)
    if(BUILD_FOR_MT)
    set(OPENSSL_MSVC_STATIC_RT true)
    endif()
    add_definitions(-DWITH_OPENSSL)
    find_package(OpenSSL)
    if(OpenSSL_FOUND)
        set(LIBS ${LIBS} OpenSSL::SSL OpenSSL::Crypto)
    else()
        set(LIBS ${LIBS} ssl crypto)
    endif()
endif()

**Comment by ithewei** [comment]
直接set(OPENSSL_USE_STATIC_LIBS TRUE)不好，不是所有人都希望使用openssl静态库，还是很多使用openssl动态库的

**Comment by zhaokaixs** [comment]
> 直接set(OPENSSL_USE_STATIC_LIBS TRUE)不好，不是所有人都希望使用openssl静态库，还是很多使用openssl动态库的

嗯嗯 明白，我只是正在使用纯静态库的，实际上我的初衷是希望 所有库的runtime 保持统一
