### ISSUE TITLE
默认库“MSVCRTD”与其他库的使用冲突；请使用 /NODEFAULTLIB:library

### ISSUE THREAD

**Issue by andyz168** [ithewei/libhv#313]
set(CMAKE_PREFIX_PATH "C:/Qt/Qt5.9.0/5.9/msvc2017_64")
set(INC_DIR D:/WorkSpace/cstudy/libhv/win64/include/hv)
set(LINK_DIR D:/WorkSpace/cstudy/libhv/win64/lib/Debug)

include_directories(${INC_DIR})
link_directories(${LINK_DIR})
#### 解决 error LNK2019: 无法解析的外部符号
add_compile_definitions(HV_STATICLIB)
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:MSVCRT ")
link_libraries(hv_static msvcrt)

出现了新的问题，
LINK : warning LNK4098: 默认库“MSVCRTD”与其他库的使用冲突；请使用 /NODEFAULTLIB:library
hv_static.lib(hdir.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter

**Comment by andyz168** [comment]
add_compile_definitions(HV_STATICLIB)
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:msvcrtd.lib ")
link_libraries(hv_static msvcrt)
换了个错误


hv_static.lib(hdir.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(Http1Parser.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(WebSocketParser.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(hurl.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(hasync.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(http_content.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(HttpHandler.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(HttpMessage.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(http_page.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(hstring.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
main.cpp.obj : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(HttpService.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(HttpServer.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(FileCache.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter
hv_static.lib(hdir.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(Http1Parser.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(WebSocketParser.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(hurl.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(hasync.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(http_content.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(HttpHandler.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(HttpMessage.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(http_page.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(hstring.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
main.cpp.obj : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(HttpService.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(HttpServer.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
hv_static.lib(FileCache.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport
untitled2.exe : fatal error LNK1120: 2 个无法解析的外部命令
ninja: build stopped: subcommand failed.

**Comment by ithewei** [comment]
```
add_definitions(-DHV_STATICLIB)
link_libraries(hv_static)
```
应该就行了，另外确保编译libhv的编译器，Debug/Release，/MD /MT这些和你的项目保持一致。
另外这都是基础的c/c++链库问题，不属于hv的讨论范畴。
