### ISSUE TITLE
关于event loop

### ISSUE THREAD

**Issue by zhaokaixs** [ithewei/libhv#314]
目前学习libhv替换现有的net框架, 
目前调用websocket_server创建服务端，在onmessage中接收 网络消息，原有的架构是创建了多线程的生产者消费者队列，来做消息解码以及业务处理
hv使用eventloop，我是否可以直接创建eventloop来代替原有的处理队列

**Comment by ithewei** [comment]
消息解码（一般是反序列化，如json解析、protobuf反序列化）这类比较轻的操作可以直接在onmessage里做了，然后将结构化的消息放入队列，使用消费者线程/线程池处理。
不推荐用EventLoop来替代生产者消费者队列，因为EventLoop底层是IO多路复用驱动的，成本还是比直接的生产者消费者队列高的。

**Comment by zhaokaixs** [comment]
> 消息解码（一般是反序列化，如json解析、protobuf反序列化）这类比较轻的操作可以直接在onmessage里做了，然后将结构化的消息放入队列，使用消费者线程/线程池处理。 不推荐用EventLoop来替代生产者消费者队列，因为EventLoop底层是IO多路复用驱动的，成本还是比直接的生产者消费者队列高的。

感谢
