### ISSUE TITLE
在OnWriteComplete里面多次发送会报栈溢出错误

### ISSUE THREAD

**Issue by hczhouu** [ithewei/libhv#315]
首次发送数据后OnWriteComplete会被处触发， 然后剩下的数据在写完成的回调里面继续发就会报栈溢出错误
![Uploading QQ图片20221129132411.png…]()

**Comment by hczhouu** [comment]
![QQ图片20221129132411](https://user-images.githubusercontent.com/39211209/204445971-e464c46a-a967-40ad-b329-2122f4c2723d.png)

**Comment by ithewei** [comment]
`hio_write -> onwrite -> hio_write -> onwrite`，如果一直可写是有可能形成递归调用的，所以不要在onwrite里多次调用hio_write，另外onwrite里应该避免char buf[1024]；这类比较大的栈开销，或者通过`currentThreadEventLoop->queueInLoop(write)`，去将写操作队列化，也可以避免形成递归调用。

**Comment by ithewei** [comment]
`onwrite`示例代码可参考 [examples/tinyhttpd.c](https://gitee.com/libhv/libhv/blob/master/examples/tinyhttpd.c) 中的 `http_serve_file`。
