### ISSUE TITLE
POST 传入 body 和 headers 为 json 的有样例不？

### ISSUE THREAD

**Issue by dongrixinyu** [ithewei/libhv#32]
POST 传入 body 和 headers 为 json 的有样例不？

**Comment by dongrixinyu** [comment]
包括，如何 和 rapidjson 做对接呢？

**Comment by ithewei** [comment]
json有两种使用方式：
1、使用libhv自使用的[nlohmann::json](https://github.com/nlohmann/json)，见HttpMessage::json字段
```
req->json["username"] = "admin";
```
2、使用其它三方json库，设置Content-Type，序列化后直接复制给body，见HttpMessage::body
```
req->content_type = APPLICATION_JSON;
req->body = json_string;
```

示例见https://github.com/ithewei/libhv/blob/master/examples/httpd/router.h

**Comment by dongrixinyu** [comment]
> json有两种使用方式：
> 1、使用libhv自使用的[nlohmann::json](https://github.com/nlohmann/json)，见HttpMessage::json字段
> 
> ```
> req->json["username"] = "admin";
> ```
> 
> 2、使用其它三方json库，设置Content-Type，序列化后直接复制给body，见HttpMessage::body
> 
> ```
> req->content_type = APPLICATION_JSON;
> req->body = json_string;
> ```
> 
> 示例见https://github.com/ithewei/libhv/blob/master/examples/httpd/router.h

我现在代码写好了，是调用一张图像的 json 数据，做 模型预测的服务
```
static void test_http_async_client(
    int* finished, std::string& body, const char* url) {
    printf("test_http_async_client request thread tid=%ld\n", hv_gettid());
    HttpRequestPtr req = HttpRequestPtr(new HttpRequest);
    HttpResponsePtr resp = HttpResponsePtr(new HttpResponse);

    req->method = HTTP_POST;
    req->url = url;
    req->body = body;
    req->timeout = 10;
    req->content_type = APPLICATION_JSON;

    int ret = http_client_send_async(req, resp, onResponse, (void*)finished);
    if (ret != 0) {
        printf("http_client_send_async error: %s:%d\n", http_client_strerror(ret), ret);
        *finished = 1;
    }
}
```
url 地址没错，body 是通过 rapidjson 序列化的一个图像的 string
然后在运行到 5 s 的时候，报错推出。报错信息如下：
```
{"Content-type":"application/json"}
test_http_async_client request thread tid=17828
test_http_async_client response thread tid=9564
onError: 系统试图将驱动器合并到合并驱动器上的目录。 :138:200
finished!

D:\VSProjects\ConsoleTest\x64\Release\ConsoleTest.exe (进程 8988)已退出，代码为 0。
```

**Comment by dongrixinyu** [comment]
上面 200 指的是 http 状态码，在报错时状态码为 200

**Comment by ithewei** [comment]
建议先使用同步接口测通，再尝试异步接口
