### ISSUE TITLE
端口已经被占用了，为什么bind还能成功

### ISSUE THREAD

**Issue by zhaokaixs** [ithewei/libhv#321]
使用ws server做测试

**Comment by zhaokaixs** [comment]
源码：1.3.0
操作系统版本:
![image](https://user-images.githubusercontent.com/7833585/206080189-1f3d1aa5-e586-43db-b0c2-c07bfaf4473c.png)

直接测试是这样
![image](https://user-images.githubusercontent.com/7833585/206079848-a9a1b9bf-36c3-427f-b757-b7d4d4b50b71.png)


如果把源码中的这一句注释掉
![image](https://user-images.githubusercontent.com/7833585/206080094-0d88f288-a72e-41d0-9828-695ae2e94403.png)

![image](https://user-images.githubusercontent.com/7833585/206080131-975c6f5e-2af8-48b7-a14c-0c5a1a10d5da.png)

**Comment by ithewei** [comment]
SO_REUSEADDR 选项在windows/linux平台上的意义不同，在windows平台不应该默认开启，稍后我修复下

**Comment by zhaokaixs** [comment]
或者说这个地址重用策略的设置 是否可以交给用户呢，

参考了一下hpsocket的设计
![image](https://user-images.githubusercontent.com/7833585/206112796-bb7a5ea7-8497-4adf-a5e2-719c4da73329.png)

**Comment by zhaokaixs** [comment]
bind: No Error， 这个错误提示是否可以更准确一些
