### ISSUE TITLE
关于http_async_client处理回调的一个问题

### ISSUE THREAD

**Issue by zedzhu** [ithewei/libhv#323]
阅读源码发现异步Http请求是通过HttpClient里的AsyncHttpClient来实现的，而AsyncHttpClient是在一个EventLoopThread里处理网络IO以及调用回调函数，也就是网络IO和回调都在一个线程里。这样如果回调函数比较耗时，是不是会阻塞同一个HttpClient发的其它请求？
不知道上述理解是否正确，谢谢。

**Comment by ithewei** [comment]
理解正确，所以回调里不适合做耗时操作，如果有应该抛给其它线程去做，
HttpResponsePtr是智能指针，可以很好的丢到生存者队列里去给消费者线程使用
