### ISSUE TITLE
使用中遇到的几个bug

### ISSUE THREAD

**Issue by oioitff** [ithewei/libhv#324]
**1. 服务端url解析错误。**
例如比较常见的跳转网址：https://account.example.com/login?next=https://www.example.com
会被错误的将完整的url解析为`/login?next=https://www.example.com`
同时导致一切基于完整url的解析出错，例如scheme变成了`/login?next=https`，host变为了`www.example.com`
经排查分析，是HttpRequest::DumpUrl()的逻辑出了一点小问题，误将包含`://`的path当成了完整路径：
```
 void HttpRequest::DumpUrl() {
     std::string str;
     if (url.size() != 0 && strstr(url.c_str(), "://") != NULL) {
         // have been complete url
         goto query;
     }
     ...
```
解决方案：修改为正确的逻辑判断。例如加入判断`url[0] != '/'`。

**2. http headers解析错误**
例如edge、chrome等浏览器自带的一些头部：
```
sec-ch-ua-model: 
sec-ch-ua-mobile: ?0
```
会被错误的解析成`sec-ch-ua-modelsec-ch-ua-mobile: ?0`。经排查分析，是Http1Parser::handle_header()的逻辑出了一点小问题，误将header_value为空的头部跳过，而且跳过后也没有将header_field和header_value清空，导致两个头部粘在一起了。
```
     void handle_header() {
         if (header_field.size() != 0 && header_value.size() != 0) {
             ...
         }
```
解决方案：header_value是可以为空的，因此应该去掉`header_value.size() != 0`的判断。

**3. http cookie错误**
服务端在通知客户端删除cookie时，会报assert错误。
经排查分析，是HttpCookie::dump()与HttpCookie::parse()的逻辑出了一点小问题，误将value为空当成错误。
cookie的value也是可以为空的，网站/服务器通常会发送一条`name=键值, value="", expires=过去日期`的set-cookie头部消息，来让浏览器/客户端删除对应的cookie。例如`Set-Cookie: PID=; expires=Mon, 01-Jan-1990 00:00:00 GMT; path=/; domain=.example.com`。
```
 std::string HttpCookie::dump() const {
     assert(!name.empty() && !value.empty());
     std::string res;
     res = name;
     res += "=";
     res += value;
     ...
```
解决方案：去掉HttpCookie::dump()与HttpCookie::parse()中关于`!value.empty()`的判断，并修改为正确的逻辑。

**Comment by oioitff** [comment]
关于cookie的bug还有一条忘记说了。HttpCookie::parse()是用来处理服务端的set-cookie消息头的，可是在Http1Parser::handle_header()中却也被用来处理客户端的cookie消息头了（cookie消息头是会同时包含多个cookie的，跟set-cookie是完全两回事），导致不停warning，而且request中携带的cookies也失去了实际意义（永远只返回第一个cookie，后面的cookie全部丢失）。

**Comment by ithewei** [comment]
感谢反馈

**Comment by oioitff** [comment]
前面三个关键bug已修复，只剩下后面提的一个小bug了。
HttpCookie::parse()是用来处理set-cookie消息头的，不应该用来处理cookie消息头。因为一个HttpCookie结构只对应一个cookie，而cookie消息头是由多个cookie的`key=value`对组成的。强行用HttpCookie::parse()来处理cookie消息头，会导致只返回第一个`key=value`对。
虽然是个小bug，对于知道的人来说不算什么，毕竟可以直接从headers中读取cookie消息头。但是对于不知道有这个bug的人来说，还是会被坑的。
作者如果暂时没时间修复的话，也可以先把Http1Parser::handle_header()中`stricmp(header_field.c_str(), "Cookie") == 0`这个判断去掉。这样，使用者会更容易发现问题，然后自行从headers中读取cookie消息头。

**Comment by oioitff** [comment]
emm，为啥非要把多个cookie强行塞入一个HttpCookie结构中？这样改无论从哪个角度看都非常不妙啊。而且这样改并没有实际解决bug吧？不知道的人还是会被坑，而知道的人自己从cookie消息头里读取出全部cookie其实也就3、4行代码的事。直接在问题的根本处`Http1Parser::handle_header()`中修改才是正确策略吧？也就几行代码，而且可以从根本上解决问题。
另外，作者应该是忘记对修改后的代码进行测试了。新修改的代码中有个异常显眼的bug，parse后再dump出来，结果都不对了（name、value在parse时被保存了两份，而dump时把两份都dump出来了）。

**Comment by ithewei** [comment]
自行解析cookie还是有点蛋疼的，之前没有考虑多个name的情况，所以只定义了一个name，现在加了个map类型的kv保存所有name=value，也算是给用户一个更多选择吧，如果确实有多个name的用户用的时候应该也会注意到这个成员存在的，至少在调试器里发现有值。

**Comment by oioitff** [comment]
你强行将多个cookie并入一个HttpCookie，并以这个方向进行修改代码的话，会导致Bug越来越多的啊，而且维护起来也会越来越困难，也破坏了HttpCookie的合理定义。哪怕是现在的代码，也又新增了新的关键Bug啊。例如cookie里面有一些未被当前代码包含的属性时（例如Priority属性），就会把这个属性当成了name，然后dump时，原本真正的name直接被忽略了。。。这还只是我一眼看出的bug，认真分析的话，或许还会有更多新增的Bug。原本只是个不影响使用的小bug，这样改下去会多出一堆关键bug的啊。

HttpCookie这个结构本来就是为了方便使用者使用的，这才是根本啊，把它整成四不像的话，这个结构就没有任何使用意义了。HttpMessage里的cookies本来就是一个HttpCookie数组，何必多此一举将多个cookie放入一个HttpCookie中？

在规范定义中，一条set-cookie消息头对应一个cookie，而cookie消息头则是由多个cookie的`name:value`对构成的，格式固定为`name1:value1;name2:value2;...`。至于解析cookie消息头，本来就是几行代码的事情。只需要用一个for循环查找';'号进行分割，把分割后的每个`name:value`对单独用一个HttpCookie进行parse，然后push_back进cookies数组里就行了。原本就几行代码的事情，为啥弄得那么复杂？那样改下去，无论从哪个角度看都非常不妙啊。
