### ISSUE TITLE
是否可以考虑gcc/g++增加pic参数？

### ISSUE THREAD

**Issue by CppBillyYan** [ithewei/libhv#328]
如果不增加pic参数，那么linux下编译出的静态库兼容性并不好，很多场景无法link

**Comment by ithewei** [comment]
https://github.com/ithewei/libhv/blob/2584ee10a2b72b3bdc1a3595d567c77b66d87f50/Makefile.in#L81
Makefile的方式是有添加-fPIC编译选项的

**Comment by CppBillyYan** [comment]
刚刚查到，通过cmake参数可以很方便解决这个问题，cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..

**Comment by CppBillyYan** [comment]
> https://github.com/ithewei/libhv/blob/2584ee10a2b72b3bdc1a3595d567c77b66d87f50/Makefile.in#L81
> 
> 
> Makefile的方式是有添加-fPIC编译选项的

主要cmake，makefile这些需要改文件，比较麻烦，cmake参数不改文件，还是比较好的
