### ISSUE TITLE
udp server无法接收信息

### ISSUE THREAD

**Issue by es12138** [ithewei/libhv#329]
环境：windows平台
1. 运行UdpServer_test.cpp例程
2. 启动UDP测试工具
3. 启动后命令行输入字符串，例如“123”，回车，触发srv.sendto(str);
4. 启动UDP测试工具，发送信息到UdpServer_test，udpserver 没有反应，没有触发onMessage
	netstat -aon|findstr "XXXX" 也没有进程监听端口了

在第2步之后进行	如下操作：
2.1 使用UDP测试工具向UdpServer发送消息，UdpServer的onMessage可以收到。
2.2 关闭UDP测试工具，然后再进行上面的后续步骤（3、4），也会产生相同的现象。即没有触发onMessage，也没有进程监听端口了。

UdpServer也没有退出。只是无法收到信息了。
经群内SeeWhy帮助，定位到原因是nio_read()中，socket报错10054错误。
给了解决方案：https://cloud.tencent.com/developer/article/1534370

**Comment by ithewei** [comment]
UDP协议本身是不区分服务端/客户端的，调用了bind的一端可以视为服务端，在对端没有发送消息前，sendto是没有目标地址的，所以sendto会报错，代码里已经做了容错处理，对于UDP socket不会去close掉，见提交https://github.com/ithewei/libhv/commit/644a78d082bde573605ce1a43da142499e9275d6，
你看看是不是你用的版本太老了，最新代码我是没有复现的。

**Comment by es12138** [comment]
确实，最新版已不存在这个问题了。
谢谢~👍
