### ISSUE TITLE
支持 webservice 么？

### ISSUE THREAD

**Issue by dongrixinyu** [ithewei/libhv#33]
如上？

**Comment by ithewei** [comment]
现在还不支持，计划中。。
见[plan.md](https://github.com/ithewei/libhv/blob/master/PLAN.md)

**Comment by dongrixinyu** [comment]
> 你是指websocket吧？现在还不支持，计划中。。
> 见[plan.md](https://github.com/ithewei/libhv/blob/master/PLAN.md)

对，长连接，服务器主动推送的那个。热切期待中……真的想急着用

**Comment by ithewei** [comment]
Done
