### ISSUE TITLE
[MacOS] Failed to compile for Android - ERROR: Failed to create toolchain.

### ISSUE THREAD

**Issue by bravepiper** [ithewei/libhv#331]
It failed when I tried to compile the Android library following the steps of BUILD.md, "ERROR: Failed to create toolchain." message will be shown. I also tried different NDK version like android-ndk-r21d etc. but it still failed

I'm not sure how to address that, can anyone point it out? thanks.

**1. configure the NDK in the .zshrc file**
```
export NDK_ROOT=~/Downloads/21.0.6113669
```
**2. run command in the Terminal**
```
MacBook-Pro build % sudo $NDK_ROOT/build/tools/make-standalone-toolchain.sh --arch=arm   --platform=android-21 --install-dir=/opt/ndk/arm
Password:
HOST_OS=darwin
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=darwin-x86_64
HOST_NUM_CPUS=4
BUILD_NUM_CPUS=8
ERROR: Failed to create toolchain.
```

**Comment by ithewei** [comment]
This is an ndk installation error, you should go to [stackoverflow](https://stackoverflow.com/) for a solution, not here.
