### ISSUE TITLE
Final Compilation objective file for Android 

### ISSUE THREAD

**Issue by bravepiper** [ithewei/libhv#333]
I'd like to compile Android Library, based on the BUILD.md,  I only get static library(libhv.a) and dynamic library(libhv.dylib) after run the command below successfully, I did not get libhv.so file, then how can I get libhv.so file after compilation? Thanks

**## Configured global variable in the .zshrc**
```
export NDK_ROOT=~/Downloads/android-ndk-r21d
```

**## run command in the teminal**
```
sudo $NDK_ROOT/build/tools/make-standalone-toolchain.sh --arch=arm   --platform=android-21 --install-dir=/opt/ndk/arm
sudo $NDK_ROOT/build/tools/make-standalone-toolchain.sh --arch=arm64 --platform=android-21 --install-dir=/opt/ndk/arm64
```

**## Configured global variable in the .zshrc**
```
export PATH=/opt/ndk/arm/bin:/opt/ndk/arm64/bin:$PATH
export CROSS_COMPILE=arm-linux-androideabi-
```

**## run command in the teminal**
```
./configure
make clean
make libhv
```

**## the result after compilation**
<img width="606" alt="image" src="https://user-images.githubusercontent.com/50685788/212266119-cefa8126-c538-4131-8e19-04ff901b1bd1.png">

**Comment by ithewei** [comment]
![image](https://user-images.githubusercontent.com/26049660/212316660-98fadc07-eaba-4874-814c-637d9f4c6a21.png)
Is there arm-linux-androideabi-gcc in your build log？

**Comment by bravepiper** [comment]
@ithewei Thanks for your reply. I looked through the log and found arm-linux-androideabi-gcc existed while using ./configure command, but it did not exist while using make libhv command, it should be different from yours. Maybe I missed something, could you help point it out? thanks

**## ./configure command**
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/50685788/212364562-f18c2d8e-7612-47df-898b-a334d51321c8.png">

**## make libhv command**
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/50685788/212364772-1aa68383-246f-4f26-8480-507e89aa5757.png">

**Comment by ithewei** [comment]
CROSS_COMPILE=arm-linux-androideabi- make libhv
No sudo

**Comment by bravepiper** [comment]
Thanks, maybe it is related to permission, I will try it again.
