### ISSUE TITLE
多个websocket服务器端如何分别与ssl证书关联

### ISSUE THREAD

**Issue by charlielven** [ithewei/libhv#338]
examples/websocket_server_test.cpp实例代码中，关于ssl使用都是调用了hssl_ctx_init方法就实现了wss版本，但是并未找到与websocket实例关联的地方。

如果在一个进程中，有2个websocket服务端，分别使用2个ssl证书，怎么使用？
例如
实例1的端口8443，使用A证书
实例2的地方9443，使用B证书
那么应该怎么关联？

**Comment by okman334** [comment]
同一个服务端有两个证书，还能这样玩的么？你是怎么处理的呀？

**Comment by charlielven** [comment]
> 同一个服务端有两个证书，还能这样玩的么？你是怎么处理的呀？

可以理解为一个端口给用户端连接的，另一个端口给业务后端或者第三方服务提供的。

**Comment by okman334** [comment]
> > 同一个服务端有两个证书，还能这样玩的么？你是怎么处理的呀？
> 
> 可以理解为一个端口给用户端连接的，另一个端口给业务后端或者第三方服务提供的。

那就不是两个服务么？起两个不同服务就行了吧。

**Comment by charlielven** [comment]
> > > 同一个服务端有两个证书，还能这样玩的么？你是怎么处理的呀？
> > 
> > 
> > 可以理解为一个端口给用户端连接的，另一个端口给业务后端或者第三方服务提供的。
> 
> 那就不是两个服务么？起两个不同服务就行了吧。

我目前就是想要启动一个，类似nginx的worker_processes=1的那种模式，可以配置多个服务端口和证书。

**Comment by okman334** [comment]
> > > > 同一个服务端有两个证书，还能这样玩的么？你是怎么处理的呀？
> > > 
> > > 
> > > 可以理解为一个端口给用户端连接的，另一个端口给业务后端或者第三方服务提供的。
> > 
> > 
> > 那就不是两个服务么？起两个不同服务就行了吧。
> 
> 我目前就是想要启动一个，类似nginx那样，可以配置多个服务端口和证书。

那在hv里能找到方法么？好像是不能多个证书。

**Comment by charlielven** [comment]
> 

没有找到，所以我觉得整个可能是libhv设计上的一个问题，都默认使用了全局的那一份证书了，没法特例化设置证书。

**Comment by charlielven** [comment]
> > > > > 同一个服务端有两个证书，还能这样玩的么？你是怎么处理的呀？
> > > > 
> > > > 
> > > > 可以理解为一个端口给用户端连接的，另一个端口给业务后端或者第三方服务提供的。
> > > 
> > > 
> > > 那就不是两个服务么？起两个不同服务就行了吧。
> > 
> > 
> > 我目前就是想要启动一个，类似nginx那样，可以配置多个服务端口和证书。
> 
> 那在hv里能找到方法么？好像是不能多个证书。

没有找到，所以我觉得整个可能是libhv设计上的一个问题，都默认使用了全局的那一份证书了，没法特例化设置证书。

**Comment by ithewei** [comment]
@charlielven 可以试试新增的HttpServer::newSslCtx接口单独为每个服务设置证书了

**Comment by charlielven** [comment]
> @charlielven 可以试试新增的HttpServer::newSslCtx接口单独为每个服务设置证书了

非常感谢，已经可以用了。
