### ISSUE TITLE
createsocket没有返回准确的errno

### ISSUE THREAD

**Issue by youyonyoumou** [ithewei/libhv#342]
问题一：
我使用TcpServer做服务时，测试发现端口被其余程序占用了，使用这个
```
TcpServer srv;
int listenfd = srv.createsocket(port);
```
的返回值listenfd 时，报的异常提示不对啊，理论上是可以提示到端口被占用了的，现在提示No error，UdpServer也有同样的问题

问题二：
```
TcpServer g_srv;    // 作为全局变量，
bool g_bContinue = true;
void fun() 
{
	int listenfd = g_srv.createsocket(5555);
	if (listenfd < 0) {
		return -1;
	}
	g_srv.onConnection = [](const SocketChannelPtr& channel) {
	};
	g_srv.onMessage = [](const SocketChannelPtr& channel, Buffer* buf) {
	};
	g_srv.onWriteComplete = [](const SocketChannelPtr& channel, Buffer* buf) {
	};
	g_srv.setThreadNum(1);
	g_srv.start();

	while (g_bContinue) {
		Sleep(500);
	}

	g_srv.stop(true);
	g_srv.closesocket();
}
```

反复调用fun函数，第二次调用时，会报错，这个问题其余几个类也有问题，如TcpClient

**Comment by ithewei** [comment]
1、windows上perror无法打印出socket error（后面可能适配下），可以先自己通过返回值查下具体错误；

**Comment by ithewei** [comment]
2、TcpServer/TcpClient这些类内部都是自带EventLoopThread的，stop后就没法再使用了，只能重新新建对象，不要复用；

**Comment by youyonyoumou** [comment]
TcpServer srv;
int listenfd = srv.createsocket(port);
if (listenfd < 0) {
	socket_strerror(listenfd);
}
通过socket_strerror获取返回错误码，也是获取不到的

**Comment by ithewei** [comment]
返回值listenfd值是多少？

**Comment by youyonyoumou** [comment]
我看了源码，也将源码拿到windows下跑了下，你使用的是goto，并且在goto之前使用close关闭失败句柄，然后使用socket_strerror去获取，此时获取的是0（因为调用的close是成功的），你可以自己跑下代码

**Comment by youyonyoumou** [comment]
static int sockaddr_bind(sockaddr_u* localaddr, int type) {
    // socket -> setsockopt -> bind
    int sockfd = socket(localaddr->sa.sa_family, type, 0);
    if (sockfd < 0) {
        perror("socket");
        return socket_errno_negative();
    }

    so_reuseaddr(sockfd, 1);
    // so_reuseport(sockfd, 1);

    if (bind(sockfd, &localaddr->sa, sockaddr_len(localaddr)) < 0) {
        perror("bind");
        goto error;
    }

    return sockfd;
error:
    closesocket(sockfd);
    return socket_errno_negative();
}

这个是你里面的TCP服务模式中的一段代码，当端口被其他程序占用时，你这个获取的错误码就是0，因为你在失败后，调用了close，之后再调用的socket_strerror，此时获取的是close成功的返回码，你可以自己使用源码跑下，绝对是有问题的
我看了源码中，有好几处都是类似的问题

这个是我截取的片段代码运行的结果：

**Comment by youyonyoumou** [comment]
![image](https://user-images.githubusercontent.com/54126113/230523183-e21c927a-34cc-445e-9be3-69e5571734be.png)

**Comment by youyonyoumou** [comment]
![image](https://user-images.githubusercontent.com/54126113/230523289-af1b1582-b5ea-41ae-85e7-18c83b536e55.png)

**Comment by youyonyoumou** [comment]
![image](https://user-images.githubusercontent.com/54126113/230523502-758afda1-cdd9-4862-814f-8b518fdf2cfc.png)
