### ISSUE TITLE
当宏 _ITERATOR_DEBUG_LEVEL 值定义为 ‘0’时出现方法参数出现null的情况

### ISSUE THREAD

**Issue by 80520997** [ithewei/libhv#343]
项目开发用到了 libcef_dll_wrapper 这个库。这个库要求将 _ITERATOR_DEBUG_LEVEL 设为 0 但是当设置为0时候就回出现调用
HttpRequest::SetHeader   时的第二个参数为null的情况。调用resp->String时也出现问题
resp->SetHeader("aaa", "bbbb"/*null*/);
![image](https://user-images.githubusercontent.com/5009715/222708567-36e0cb34-c5cd-41ab-9e4b-92a116b42bcc.png)

![image](https://user-images.githubusercontent.com/5009715/222708702-7ddafc91-8704-4f19-9591-8c871d0049f1.png)

**Comment by ithewei** [comment]
不太清楚`_ITERATOR_DEBUG_LEVE`这个宏的作用，如果是影响到了STL的行为，那应该是有问题的，你的项目里如果非要设置这个宏，就在编译hv库时也设置这个宏，确保编译你的项目和编译hv库的环境一致。

**Comment by 80520997** [comment]
好像是由于VC的编译参数 /MTd /MDd 导致的。遇到这个问题先考虑统一编译参数。我修改了libcef_dll_wrapper 的编译参数为 /MDd 问题被解决
