### ISSUE TITLE
http实现restfulAPI

### ISSUE THREAD

**Issue by lylyly6666** [ithewei/libhv#344]
作者的http功能相当齐全，给作者点一个大大的赞！
我的需求是实现仅仅实现http的GET和POST方法，进而实现RESTful API。请问作者我该看http中的哪些程序？

**Comment by ithewei** [comment]
[examples/http_server_test.cpp](https://github.com/ithewei/libhv/blob/master/examples/http_server_test.cpp) and [examples/httpd](https://github.com/ithewei/libhv/blob/master/examples/httpd)
