### ISSUE TITLE
关于使用hio_t中的userdata

### ISSUE THREAD

**Issue by xwb1966** [ithewei/libhv#347]
我想使用hio_t结构中的userdata（我需要让listen的io中的userdata自动传给onaccept回调中的参数io中，以便让这个io能够知道是哪个listen的io产生的），但发现没有函数可以访问这个userdata。是否有什么办法访问hio_t中的userdata，或者增加2个函数：
void hio_set_userdata(hio_t* io, void* userdata) {
    io->userdata = userdata;
}

void* hio_userdata(hio_t* io) {
    return io->userdata;
}

**Comment by ithewei** [comment]
hevent_userdata

**Comment by xwb1966** [comment]
好的，谢谢
