### ISSUE TITLE
wget例程这一行req.method = HTTP_HEAD多余

### ISSUE THREAD

**Issue by smallPlanet123** [ithewei/libhv#349]

**Comment by ithewei** [comment]
HEAD请求是为了获取文件是否在服务器上存在，以及文件大小等信息，来决定是否采取Range分片请求策略，当然你如果不想使用Range，可以直接通过GET请求下载，设置http_cb可以边接收边写到磁盘。

**Comment by smallPlanet123** [comment]
加上HTTP_HEAD就跑不通，是因为服务器不支持HTTP_HEAD请求吗

**Comment by ithewei** [comment]
打印下response，或者postman测试下是否支持HEAD请求呗
