### ISSUE TITLE
How could I integrate my event checks in the libhv event loop?

### ISSUE THREAD

**Issue by walkanywhere** [ithewei/libhv#351]
Thanks first for your great work. I like the library and been thinking about using it in my production system.

I have a scenario where I need to use a 3rd party tcp client to connect to their server, which requires me to poll the tcp client to retrieve data. May I know how I could do with libhv for this? Thanks!

Also, is it possible to register a raw socket fd to libhv, so it could help poll and notify users? 

Thanks!

**Comment by ithewei** [comment]
`hio_t* io = hio_get(loop, fd)`, then you can use hio_read, hio_write, etc.

**Comment by ithewei** [comment]
set HLOOP_FLAG_RUN_ONCE
```
hloop_t* loop = hloop_new(HLOOP_FLAG_RUN_ONCE);
while (true) { hloop_run(loop); my_client.poll(); // this could trigger my own callbacks  }
```
or use timer
```
void on_timer(htimer_t* timer) {
    my_client.poll(); // this could trigger my own callbacks
}

hloop_t* loop = hloop_new(0);
htimer_add(loop, on_timer);
hloop_run(loop);
```

**Comment by walkanywhere** [comment]
Thanks a lot for your reply. Will give it a try!

**Comment by walkanywhere** [comment]
with very simple codes above
`
auto	 s	  = gethrtime_us();
while (true)
{
	hloop_run(loop);
	auto n = gethrtime_us();
	SPDLOG_INFO("{} us", n - s);
	s = n;
}
`
a `hloop_run` takes 100200 microseconds in release mode, which is tremendous as I thought it should be less than 400 nanoseconds or even less. A QT event loop takes 700 nanoseconds in such a scenario, and I thought is big too. 

Think there must be something I missed. Or it is expected?

**Comment by ithewei** [comment]
because https://github.com/ithewei/libhv/blob/06a7b5eb512d0c256f5356424d14ad1f8d30fc3d/event/hloop.c#L18

**Comment by walkanywhere** [comment]
> Now, you can use
> 
> ```c
> while(1) { xxx; hloop_process_events(loop,1); xxx; }
> ```

Thanks for your update, but still don't think ms works for high performance systems, could you pls lower it down to the levels of ns or us?

**Comment by ithewei** [comment]
I am not going to change the precision, you can fork and modify it yourself.

**Comment by ithewei** [comment]
Try `hloop_process_events(loop,  0);`

**Comment by KBEngineLab** [comment]
> Try `hloop_process_events(loop, 0);`

@ithewei 你好，请教一下，我尝试用hloop_process_events，没有效果，process是在UE的Ticker里调用的，用法有问题吗




"""
bool NetworkInterfaceTCP::connectTo(const KBString &addr, uint16 port, InterfaceConnect *callback, int userdata) {
	reset();

	connectCB_ = callback;
	connectIP_ = addr;
	connectPort_ = port;
	connectUserdata_ = userdata;
	startTime_ = getTimeSeconds();

	Loop = std::make_shared<hv::EventLoop>();
	if (!socket_) {
		socket_ = std::make_shared<hv::TcpClient>(Loop);
	}

	int ret = socket_->createsocket(port, TCHARToANSI(*addr).c_str());
	if (ret < 0) {
		ERROR_MSG("NetworkInterfaceTCP::connectTo(): createsocket failed %d", ret);
		return false;
	}


	socket_->setConnectTimeout(30000);

	// 连接成功回调
	socket_->onConnection = [this](const hv::SocketChannelPtr& ch) {
		// printf("connectCB_: %d  %d %d\n", ch->isConnected(),ch->isClosed(),ch->isOpened());

		if (connectCB_) {
			if (ch->isConnected()) {
				INFO_MSG("NetworkInterfaceTCP::connectTo(): connect to  %s success!", ch->peeraddr().c_str());

				connectCB_->onConnectCallback(connectIP_, connectPort_, true, connectUserdata_);
				connectCB_ = nullptr;

				auto pEventData = std::make_shared<UKBEventData_onConnectionState>();
				pEventData->success = true;
				pEventData->address = KBString::Printf(KBTEXT("%s:%d"), *connectIP_, connectPort_);
				KBENGINE_EVENT_FIRE(KBEventTypes::onConnectionState, pEventData);

			}else {
				// 连接超时或者无法连接
				ERROR_MSG("NetworkInterfaceTCP::connectTo(): connect to %s timeout!", ch->peeraddr().c_str());
				connectCB_->onConnectCallback(connectIP_, connectPort_, false, connectUserdata_);
				connectCB_ = nullptr;

				auto pEventData = std::make_shared<UKBEventData_onConnectionState>();
				pEventData->success = false;
				pEventData->address = KBString::Printf(KBTEXT("%s:%d"), *connectIP_, connectPort_);
				KBENGINE_EVENT_FIRE(KBEventTypes::onConnectionState, pEventData);
			}

		}

	};


	// 数据回调
	socket_->onMessage = [this](const hv::SocketChannelPtr& ch, hv::Buffer* buf) {
		const auto* data = reinterpret_cast<const uint8_t*>(buf->data());
		size_t len = buf->size();
		pBuffer_->clear(true);
		pBuffer_->append(data, len);

		if (pFilter_) {
			pFilter_->recv(pMessageReader_,pBuffer_);
		}else {
			pMessageReader_->process(pBuffer_->data(), 0, len);
		}

	};

	// socket_->start();  // 启动 EventLoop

	socket_->startConnect();
	return true;
}


void NetworkInterfaceTCP::process()
{
	if (Loop) {
		hloop_process_events(Loop->loop(), 0);
	}
}
"""
