### ISSUE TITLE
jsonrpc框架Debug版本报10055错误

### ISSUE THREAD

**Issue by peterlinux2010** [ithewei/libhv#352]
您好，参考了您的例程《libhv教程14--200行实现一个纯C版jsonrpc框架》，做了2个控制台应用测试程序，一个服务端和一个客服端通讯，使用的是vs2013编译器，测试Release版本都是正常的，但切换到Debug版本时候，控制台报错如下，一直没研究出为啥，网络查找10055错误码说是TCP端口数不能超过5000，但我实际的端口是低于5000的。
connect: No error
on_close fd=924 error=10055

**Comment by ithewei** [comment]
I don't known.
