### ISSUE TITLE
AsyncHttpClient

### ISSUE THREAD

**Issue by ruanryq421** [ithewei/libhv#353]
同样的请求，用同步是可以得到正确回复，服务器故意给了405，回调OK,但是如果用异步，回调resp为空，这个是不是有问题？而且从代码上来看，逻辑是不是也有问题？如图
![image](https://user-images.githubusercontent.com/105113972/227341195-9fb2e9c4-d679-4548-bb88-b2253438cb3e.png)
为什么出现错识的时候先将resp置空呢？不是应该等回调处理完成之后，再清结果么?

**Comment by ithewei** [comment]
这里的errorCallback是意外断链、超时情况，HTTP返回码405也是走successCallback的
