### ISSUE TITLE
How to check if a HTTP connection is closed by client before HTTP response is sent ?

### ISSUE THREAD

**Issue by anuragvohraec** [ithewei/libhv#355]
Hi All,

I have a code something like this :
```
//query some database
httpCtx->writer->WriteBody(str1);

//query some database
httpCtx->writer->WriteBody(str2);

//query some database
httpCtx->writer->WriteBody(str3);

//and latter when all body is written : by quering different databases
//I end the connection.
httpCtx->writer->End();
```

However if a client closes the connection in between (curl the URL and press Ctrl+c), the whole application server goes down with it. How to check if the HTTP context is still fit for replying to the user. As other wise it gives me invalid read error.

**Comment by anuragvohraec** [comment]
Ok So I figured it on my own.
```
//one need to set this callback , as its called whenever TCP connection is closed by client
httpCTX->writer->onclose=[userdata](){
            //set some flag here, which you can use later 
            //and check before WriteBody on writer 
};
```

**Comment by ithewei** [comment]
Yes，you are rihgt.
register writer->onclose
or query by writer->isConnected()
or judge return value < 0 of writer->write()
