### ISSUE TITLE
How to know if TcpClient connects to a non-exist or turned down server

### ISSUE THREAD

**Issue by WorstCodeWay** [ithewei/libhv#356]
As the title says, how to check connecting to a server which is not exist or truned down?

By, return code? or some status?

Kindly for you to show some codes.

**Comment by ithewei** [comment]
onConnection => channel->isConnected() 
https://github.com/ithewei/libhv/blob/06a7b5eb512d0c256f5356424d14ad1f8d30fc3d/evpp/TcpClient_test.cpp#L35

**Comment by WorstCodeWay** [comment]
> onConnection => channel->isConnected()
> 
> https://github.com/ithewei/libhv/blob/06a7b5eb512d0c256f5356424d14ad1f8d30fc3d/evpp/TcpClient_test.cpp#L35

Yes, I notice these codes, and did that way, but it still doesn't work when connecting to a non-exist server. `onConnection` is never called? Or some mistakes I have made?
