### ISSUE TITLE
TcpClient::startConnect returns non-zero, causing EventLoopThread::stop

### ISSUE THREAD

**Issue by tenx6** [ithewei/libhv#359]
In function hio_connect, if connect return -1 or connection timeout, currently will call hio_close_async, this will cause the timer in startReconnect goto invalid.

int startReconnect() {
	if (!reconn_setting) return -1;
	if (!reconn_setting_can_retry(reconn_setting)) return -2;
	uint32_t delay = reconn_setting_calc_delay(reconn_setting);
	hlogi("reconnect... cnt=%d, delay=%d", reconn_setting->cur_retry_cnt, reconn_setting->cur_delay);
	**loop_->setTimeout(delay, [this](TimerID timerID){**
		startConnect();            // startConnect will not be called as hio_close stopped the loop
	});
	return 0;
}

**Comment by ithewei** [comment]
hio_close will not stop the loop，so I don't understand your confusion.

**Comment by tenx6** [comment]
Actually, the timer set in startReconnect will not be call because the loop has been stopped which was caused by the returned value of hio_connect. 
As we know, the TcpClient is running in EventLoopThread, there is a function named loop_thread like below:
if (pre) {
    loop_->queueInLoop([this, pre]{
        if (**pre()** != 0) {
            loop_->stop();
        }
    });
}

We can see, if pre() != 0, the loop will be stopped. So what is the pre() called? 

void start(bool wait_threads_started = true) {
        if (isRunning()) {
            TcpClientEventLoopTmpl<TSocketChannel>::start();
        } else {
            **EventLoopThread::start**(wait_threads_started, std::bind(&**TcpClientTmpl::startConnect**, this));
        }
    }

Look at this, if TcpClientTmpl::startConnect return a non-zero value, the loop in EventLoopThread will be stopped.
So will TcpClientTmpl::startConnect return non-zero value? We can see the call stack like below:
   TcpClientTmpl::startConnect -> channel->startConnect -> hio_connect(io_).

int hio_connect(hio_t* io) {
    int ret = connect(io->fd, io->peeraddr, SOCKADDR_LEN(io->peeraddr));
#ifdef OS_WIN
    **if (ret < 0** && socket_errno() != WSAEWOULDBLOCK) {
#else
    **if (ret < 0** && socket_errno() != EINPROGRESS) {
#endif
        perror("connect");
        io->error = socket_errno();
        hio_close_async(io);
        **return ret;**
    }

Now, We know if hio_connect return non-zero value, the loop will be stopped and the reconnect timer will be invalid.
