### ISSUE TITLE
c++ tcp客户端重连方法

### ISSUE THREAD

**Issue by xiaoyaodingchunqiu** [ithewei/libhv#362]
![image](https://user-images.githubusercontent.com/92872460/229011687-a9546865-c68e-4c95-9bec-24472e392f31.png)
tcp服务端调用close()方法后，客户端没法使用cli.start()方法重连，排查库代码，发现可能走到了channel->status >= SocketChannel::CONNECTING条件里面，不会调用cli.onConnection函数，是我的版本太老旧了吗
有什么比较好的方法去重连吗

**Comment by ithewei** [comment]
没有触发onConnection回调？判断了cli.createsocket的返回值吗，另外可以使用cli.setReconnect方法设置重连

**Comment by xiaoyaodingchunqiu** [comment]
使用cli.setReconnect方法设置重连会概率导致崩溃，所以我们才用的手动重连
直接调用cli.start是看不到返回值的
你是建议我们再重新创建套接字是吗，重头开始走那套流程是吗，那重新走之前，应该把cli改成什么状态呢，closed状态行嘛

**Comment by ithewei** [comment]
使用cli.setReconnect方法设置重连为什么会崩溃，崩溃在哪里，使用示例代码测试呢
[TcpClient_test.cpp](https://github.com/ithewei/libhv/blob/master/evpp/TcpClient_test.cpp)
