### ISSUE TITLE
请问一下tcpclient 或者 tcpserver ，不能同步处理消息的问题，该怎么处理？

### ISSUE THREAD

**Issue by joyhuangjunjie** [ithewei/libhv#363]
hio_write(io,"hello",7);
 hio_setcb_read(io, on_message);
  hio_read(io);
  
  源码里面都是采用回调函数，异步获取tcp返回的结果， 如果想同步等待结果，并且附带超时时间，该怎么实现？

**Comment by joyhuangjunjie** [comment]
> 你指的这个同步，阻塞当前线程？你完全可以把这个请求记录下来，定时检测它是否超时啊。

非常感谢您的回复。你说的很对 我说的就是阻塞式的获取，你说的这种方法也不是不可以，理论上也可以实现。 只是有些有些场景 就是阻塞当前线程获取回复。

**Comment by ithewei** [comment]
libhv本身是异步非阻塞IO网络库，同步阻塞IO直接使用系统套接字API就好啦，没必要使用libhv
