### ISSUE TITLE
使用vcpkg安装后的库，在调用websocket的onmessage函数过程出现读取内存地址错误，怀疑是parser被释放了,应该怎么解决？

### ISSUE THREAD

**Issue by GengineJS** [ithewei/libhv#365]
![image](https://user-images.githubusercontent.com/10766457/230869661-f5010515-30ea-4ec3-8a24-586355af47c2.png)

**Comment by ithewei** [comment]
发下你的vcpkg安装libhv命令

**Comment by GengineJS** [comment]
vcpkg install libhv:x86-windows
