### ISSUE TITLE
mqtt_client.c的 on_close是不是有问题。

### ISSUE THREAD

**Issue by Saber728Avalon** [ithewei/libhv#366]
static void on_close(hio_t* io) {
    mqtt_client_t* cli = (mqtt_client_t*)hevent_userdata(io);
    cli->connected = 0;
    if (cli->cb) {
        cli->head.type = MQTT_TYPE_DISCONNECT;
        cli->cb(cli, cli->head.type);
    }
    // reconnect
    if (cli->reconn_setting && reconn_setting_can_retry(cli->reconn_setting)) {
        uint32_t delay = reconn_setting_calc_delay(cli->reconn_setting);
        cli->reconn_timer = htimer_add(cli->loop, reconnect_timer_cb, delay, 1);
        hevent_set_userdata(cli->reconn_timer, cli);   //直接cli赋值给cli->reconn_timer 真的大丈夫吗？
    }
}

**Comment by Saber728Avalon** [comment]
我明白你这样做的目的。是要把参数传递给reconnect_timer_cb.但是如果 在timer回调完成之前，有退出操作。就会导致cli内容其实是错误的。

**Comment by ithewei** [comment]
https://github.com/ithewei/libhv/blob/f607becbaca2e93ab71e51832ea0ed6c51043725/mqtt/mqtt_client.c#L372

**Comment by Saber728Avalon** [comment]
> 

问题是，这个reconn_timer已经不是指向了timer, 去释放timer时候。其实错误的。

**Comment by Saber728Avalon** [comment]
我的建议是在htimer_s添加一个userdata参数，这样timer任何时候就可以带上一个参数了。就不用去考虑这个麻烦事情了。

**Comment by ithewei** [comment]
https://github.com/ithewei/libhv/blob/f607becbaca2e93ab71e51832ea0ed6c51043725/event/hloop.h#L79
`hevent_set_userdata(cli->reconn_timer, cli)`，就是是指把cli赋值给htimer_s的userdata，htimer_s是继承自hevent_s的，包括hevent_s的成员和宏定义实现的方法，不要代码都没看明白就来建议，我建议你debug调试下或者打印下指针值是否正确

**Comment by Saber728Avalon** [comment]
> https://github.com/ithewei/libhv/blob/f607becbaca2e93ab71e51832ea0ed6c51043725/event/hloop.h#L79
> 
> 
> `hevent_set_userdata(cli->reconn_timer, cli)`，就是是指把cli赋值给htimer_s的userdata，htimer_s是继承自hevent_s的，包括hevent_s的成员和宏定义实现的方法，我建议你debug调试下或者打印下指针值是否正确

我试试呢

**Comment by Saber728Avalon** [comment]
我仔细调试思考了,这里确实会有问题。因为reconn_timer指向的是 cli(就是mqtt_client_s).这个和你的event没有直接关系。最后你的mqtt_client_free,会释放定时器。其实那个时候，就会出错。  我的建议是你mqtt_client_free干脆不要释放定时器，反正消息队列退出时候，会自动释放这个时间，甚至你根本不用管理这个定时器。交给事件循环就好了

**Comment by ithewei** [comment]
你还是没理解htimer_s和hevent_s的继承关系，建议你看下这篇博客<https://hewei.blog.csdn.net/article/details/103903123>的c语言如何实现c++的继承一节

**Comment by Saber728Avalon** [comment]
NONONO，我觉得你没有理解我的意思。mqtt_Client_s是没有继承event的。你前面有有mqtt_clinet_s直接赋值给recon_timer,退出时候是会释放recon_timer，导致释放的其实是mqtt_client_s就会崩掉
