### ISSUE TITLE
Auto redirection that the condition is incorrect

### ISSUE THREAD

**Issue by Andy6Loda** [ithewei/libhv#369]
This http/httpdef.h  line No.98, it should be treated as a whole through parentheses
#define HTTP_STATUS_IS_REDIRECT(status)             \
    (status) == HTTP_STATUS_MOVED_PERMANENTLY   ||  \
    (status) == HTTP_STATUS_FOUND               ||  \
    (status) == HTTP_STATUS_SEE_OTHER           ||  \
    (status) == HTTP_STATUS_TEMPORARY_REDIRECT  ||  \
    (status) == HTTP_STATUS_PERMANENT_REDIRECT

because, in http/client/AsyncHttpClient.cpp line No.81 , you used &&
 if (req->redirect && HTTP_STATUS_IS_REDIRECT(resp->status_code)) {

**Comment by ithewei** [comment]
Are you interested in making a PR to fix it？

**Comment by Andy6Loda** [comment]
I just submitted a PR
