### ISSUE TITLE
请问对http2的支持怎么样？

### ISSUE THREAD

**Issue by Barenboim** [ithewei/libhv#37]
你好，看了一下代码，好像包含了http2协议的解析。因为代码量不多，想问一下是已经实现了http2的全功能支持了吗？同一连接上多个stream都可以正确被处理吗？谢谢！

**Comment by ithewei** [comment]
http2解析是用的nghttp2，能简单支持http2、grpc请求响应，http2的多stream我也没测试过，不知道怎么测。。
具体编译测试步骤README中有写，我再贴下
```
sudo apt install libnghttp2-dev # ubuntu
make clean
make WITH_NGHTTP2=yes
bin/httpd -d
bin/curl -v localhost:8080 --http2
```

**Comment by Barenboim** [comment]
好的，我研究一下！感谢回复。
