### ISSUE TITLE
关于cookie的问题点

### ISSUE THREAD

**Issue by programcj** [ithewei/libhv#374]
浏览器请求shi时的Cookie头会有很多时, Http1Parser::handle_header() 只有一个的情况.

![image](https://user-images.githubusercontent.com/24808188/234752101-d3c85826-4836-47fc-9516-124b4e5314c2.png)

![1682565736213](https://user-images.githubusercontent.com/24808188/234751545-09369839-0440-4419-845f-e157490540e7.png)

**Comment by ithewei** [comment]
为了简化使用，headers并没有使用multimap，你可以从cookies成员变量里去取
