### ISSUE TITLE
nghttp2的编译问题。

### ISSUE THREAD

**Issue by babA409866** [ithewei/libhv#375]
在CMake相关的可选参数中 没有看到指定本地的 nghttp2的路径，建议模仿curl的编译方式 。可以支持传入路径。这样mac上也能编译。 现在支持的方式好像是直接安装到系统库中。

**Comment by babA409866** [comment]
大佬可以添加 ExternalProject_Add 相关的一些写法支持设置来方便接入现有的项目中。这样更有利于推广。还有 cmake的fectch content的方式。

**Comment by ithewei** [comment]
make install目录问题，了解下cmake -DCMAKE_INSTALL_PREFIX=install_dir

**Comment by ithewei** [comment]
nghttp2路径查找问题，可以自行修改下cmake里WITH_NGHTTP2的地方，或者在自己的工程cmake里使用include_directories添加头文件搜索目录，link_directories添加库文件搜索目录
