### ISSUE TITLE
wrk和原版的性能比较

### ISSUE THREAD

**Issue by babA409866** [ithewei/libhv#377]
测试环境为docker里的 ubuntu 22.04
 ./wrk -t28 -c3000 -d7s https://www.baidu.com
和wrk原版的比较
wrk -t28 -c3000 -d7s --latency https://www.baidu.com

在同一台pc。性能原版稳定 500多条。都成功。
使用libhv编译后的wrk

./bin/wrk http://www.baidu.com -v -c 3000 -d 7s -t 28
执行结果。
Running 7s test @ http://www.baidu.com
28 threads and 3000 connections
Connect to 103.235.46.40:80 ...
GET / HTTP/1.1
Accept: */*
Connection: keep-alive
Host: www.baidu.com
User-Agent: libhv/1.3.0

all disconnected
2489 requests, 0 OK, 79MB read in 7s
Requests/sec:        0
Transfer/sec:       11MB

为什么ok的次数为0.另外效率和wrk的原版的发送的请求数也有一定差别。本机简单用多线程+curl的效率可以接近到wrk的数值。但是 libhv 从原理来说 应该也能达到差不多的测试结果才是。

**Comment by babA409866** [comment]
太赞了！

**Comment by ithewei** [comment]
http://www.baidu.com/会重定向吧，不是返回200，建议换个网址测试，最好是内网服务
