### ISSUE TITLE
TcpClient SocketChannelPtr return wrong sent size after `write` called

### ISSUE THREAD

**Issue by WorstCodeWay** [ithewei/libhv#380]
I connect a tcp server with TcpClient and send some bytes through `write` interface of SocketChannelPtr
```c++
size_t sent = channel->write(buffer, size);
```
However, I find that sent(110048) is not equal to size(1048576). Actually, on the other side of tcp server, I'm sure they are equal(both are 1048576) based on log.

Why this happens?

**Comment by ithewei** [comment]
This is normal. When the socket send buffer of system is full, it will be stored in libhv's writing queue. At this time, the return value < size is ok.
You can look at the implementation of hio_write.

**Comment by WorstCodeWay** [comment]
> This is normal. When the socket send buffer of system is full, it will be stored in libhv's writing queue. At this time, the return value < size is ok. You can look at the implementation of hio_write.

If so, how can I check if my sending mission is success or not? ps. I'm sending a large file through client.

**Comment by ithewei** [comment]
Flow control should be done when sending large data, and the write completion event should be monitored through onWriteComplete, and the next frame of data should be sent when it is writable.
The sample code can refer to `http_serve_file` in [examples/tinyhttpd.c](https://github.com/ithewei/libhv/blob/master/examples/tinyhttpd.c)
