### ISSUE TITLE
websocket wss client connection auto disconnects

### ISSUE THREAD

**Issue by newpoo** [ithewei/libhv#382]
Hi there,

The client setup code is as below:

```
   reconn_setting_t reconn;
   reconn_setting_init(&reconn);
    reconn.min_delay = 1000;
    reconn.max_delay = 10000;
    reconn.delay_policy = 2;
    client->setReconnect(&reconn);
    client->setPingInterval(60 * 1000);
    client->open(uri.c_str());
```

onclose gets called once every 3 min or so. Any ideas how to keep the connection open?

Thanks!

**Comment by ithewei** [comment]
refer to [websocket连接不久断链排查]( https://github.com/ithewei/libhv/wiki/%E4%B8%AD%E6%96%87FAQ#qwebsocket%E5%90%AF%E5%8A%A8%E4%B8%8D%E4%B9%85%E6%96%AD%E9%93%BE%E6%8E%92%E6%9F%A5)
