### ISSUE TITLE
libhv发送SMTP邮件问题

### ISSUE THREAD

**Issue by anheida** [ithewei/libhv#392]
源码protocol/smtp.c默认使用25端口，本机测试没有问题邮件能成功发出，但是云服务器一般都封禁25端口，源代码修改为SMTPS_PORT465端口，则发送失败，smtp.c第60行nrecv = recv(sockfd, buf, buflen, 0);，这里接收返回-1，自己尝试修改源码，也一直没有成功，有解决的思路吗？（本人初级小白，还望大家海涵）

**Comment by ithewei** [comment]
25端口是普通的smtp明文协议，465端口表示ssl加密后的协议smtps，实现里没有考虑smtps，你可以参考HttpClient.cpp里的做法，判断如果是走ssl加密，就调用`hssl_connect`、`hssl_read`、`hssl_write`取代原始的`connect`、`recv`、`send`

**Comment by anheida** [comment]
好的，谢谢，问题已解决。建议后期源码可以增加这一部分。

**Comment by anheida** [comment]
好的，谢谢，问题已解决。建议后期源码可以增加这一部分。
