### ISSUE TITLE
Windows DLL编译为/MT或/Mtd的时候 会出现堆异常的问题

### ISSUE THREAD

**Issue by zhaokaixs** [ithewei/libhv#394]
![image](https://github.com/ithewei/libhv/assets/7833585/17092dd9-f22b-4686-a65a-a7d491e16ec8)
![image](https://github.com/ithewei/libhv/assets/7833585/2616b562-04fc-48e2-80d1-e595b906663d)

目测是因为dll和exe用/mt的时候不是共享heap,所以接口返回stl对象时~

**Comment by ithewei** [comment]
windows使用/mt，因为跨dll使用STL对象是会有问题，建议使用/md的动态库，或者使用静态库

**Comment by zhaokaixs** [comment]
好的，已经这么做了，顺便问一下咱们测试过的openssl版本是多少，我今天用1.3.1的hv，配合使用3.1.1的openssl ，死活加载不上.crt证书，证书已经校验过没有问题了，，没啥思路了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月12日(周一) 晚上6:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ithewei/libhv] Windows DLL编译为/MT或/Mtd的时候 会出现堆异常的问题 (Issue #394)




 
windows使用/mt，因为跨dll使用STL对象是会有问题，建议使用/md的动态库，或者使用静态库

**Comment by ithewei** [comment]
openssl1.1.1x版本

**Comment by zhaokaixs** [comment]
> Reference in new
破案了，用相对路径不可以 很奇怪
![image](https://github.com/ithewei/libhv/assets/7833585/0d9265c9-68b2-44a9-9737-a3cbe499db94)
![image](https://github.com/ithewei/libhv/assets/7833585/a58afc0c-b59c-469c-b44e-a937cdf8bee7)
![image](https://github.com/ithewei/libhv/assets/7833585/241e1577-673a-453a-b4e6-6558134aa892)
![image](https://github.com/ithewei/libhv/assets/7833585/e0d714e6-34f2-459e-acc6-0ed2c0539989)
![image](https://github.com/ithewei/libhv/assets/7833585/dd4095df-d69a-420b-99dc-b0640e7ff824)

**Comment by ithewei** [comment]
你调试时的运行路径不一定是Debug目录吧

**Comment by zhaokaixs** [comment]
> 你调试时的运行路径不一定是Debug目录吧

我的错！感谢
