### ISSUE TITLE
 WebSocketServe r的 channel->Send 是服务器收到消息

### ISSUE THREAD

**Issue by tiantianaixuexi** [ithewei/libhv#395]
大佬好，我在Windows 弄了个WebSocketServer,代码是这样写的

![image](https://github.com/ithewei/libhv/assets/31758095/edf15573-e466-4e83-a946-f9859d1e6365)
![image](https://github.com/ithewei/libhv/assets/31758095/37cc108d-f942-4125-a80f-9f693e1a6d60)

为什么我这边是服务器收到这些消息呢。。。
![image](https://github.com/ithewei/libhv/assets/31758095/2589f7eb-1589-4570-a6ff-d4af38fc33dd)

客户端的Send又是正常的，服务器能收到消息

**Comment by ithewei** [comment]
是不是客户端将消息给回显了呢，可以抓下包看看

**Comment by tiantianaixuexi** [comment]
还真是这个问题，谢谢大佬

**Comment by tiantianaixuexi** [comment]
close

**Comment by tiantianaixuexi** [comment]
经过测试，问题还是能复现。尝试在 onopen的channel发送一条消息
![image](https://github.com/ithewei/libhv/assets/31758095/57b620d0-df03-4969-be08-dea240c8d1d0)
客户端连之后发送一条消息给服务器，msg:{ eventid} 这一段是客户端传的
![image](https://github.com/ithewei/libhv/assets/31758095/3bf162d7-de46-46c2-b615-055f24959fce)
test hello 是服务器端的onopen传的

**Comment by tiantianaixuexi** [comment]
客户端和服务端是分离的，这个cmd窗口只会输出Server打印的信息。
