### ISSUE TITLE
libhv的http模块如何实现类似挂起的操作？

### ISSUE THREAD

**Issue by Hankyin** [ithewei/libhv#40]
一个http请求到达服务A，服务A需要访问服务B获取数据后才能返回响应。假设服务B响应时间较长，在此期间服务A该怎么办？
如果阻塞等待B的回复，A就没法响应其他请求了，这不是我们想要的。
如果开多线程、多进程处理，这我感觉就没有使用IO多路复用的意义了。

**Comment by ithewei** [comment]
libhv中的http模块的设计理念是简单，所以没有提供出HttpResponseWriter，请求回调中是不建议做耗时操作的，会阻塞当前线程，所以是没法满足你上面的场景，这类本身既是服务端又是客户端的场景c++来做是不擅长的，其它后端语言有更成熟的框架

**Comment by ithewei** [comment]
不过后面也会考虑实现RequestCallback(const HttpRequestPtr&, const HttpResponseWriterPtr&);

**Comment by Barenboim** [comment]
我们的系统在既是服务器又是客户端的场景就解决的很好，不介意的话我贴一下地址：https://github.com/sogou/workflow
但是像http2，websocket这类问题又很难融入进来了。之前特意看了libhv这块的实现。每个系统都有侧重点，所有功能都要实现真的很难。

**Comment by ithewei** [comment]
原来是sogou的大佬，久仰大名。
是的每个库都有自己的特长，workflow我也简单看过，很优秀的库，从代码细节上就看的出来很重视性能，引入了一套任务流的概念，但使用一个库有额外的学习成本，我不认为是一件好事，ACE就是前车之鉴，我更欣赏的是golang的gin、python的requests、js的websocket，这类所见即会用的接口设计，所以libhv也在模仿实现类似接口。
c++的网络框架我认为muduo的类设计还是不错的，360的evpp也是基于libevent模仿muduo，libhv在c层面是模仿libevent/libuv，在c++层提供了类似的evpp，基于c接口的hloop或者c++的evpp，都是很好扩展实现上层应用层协议的。目前虽然只提供了http，后续websocket已经设计好了，mqtt、redis也在计划之中。
当然rpc框架个人是很难有时间和精力去完成的，贵司的srpc很赞。
我觉得我们可以有更多的技术交流，你可以通过qq群联系到我，祝好！

**Comment by Barenboim** [comment]
嗯嗯，workflow主要为性能而生，还有就是通讯计算的结合。网络这一块的实现和常见的各种event loop不太一样。学习成本其实也不高的：）最近学习libhv想往streaming引擎方面做一些东西，但要和现有的架构完美融合挺不容易的。libuv如果多提供一下实用协议，应该能吸引很多用户。之前留意这个库也是因为发现很多代码风格和我们挺接近的。个人项目做到这样真的很厉害啊。
之后多多交流哈。感谢感谢。

**Comment by Barenboim** [comment]
对了，issue这个问题其实挺重要的，因为后端服务器基本都是多路收集数据再整合的。

**Comment by aguludunu** [comment]
我也想问支不支持异步的问题，结果进来看到第一个issue就是这个，看来大伙都很关心啊

**Comment by ithewei** [comment]
已完成HttpResponseWriter异步响应，我将关闭此issue
