### ISSUE TITLE
是否支持监听同一个端口同时处理Http和WebSocket两种协议呢？

### ISSUE THREAD

**Issue by BambooMa** [ithewei/libhv#400]
目前有需要使用同一个端口处理两种协议的需求libhv可以实现这种需求吗

**Comment by ithewei** [comment]
支持，`WebSocketServer` 继承自 `HttpServer`，`registerHttpService`用于注册HTTP业务，`registerWebSocketService`用于注册WS业务，具体示例代码参考 [examples/websocker_server_test.cpp](https://github.com/ithewei/libhv/blob/master/examples/websocket_server_test.cpp)
