### ISSUE TITLE
HttpServer底层基于EventLoop，如何在HttpServer的对象中使用queueInLoop函数？

### ISSUE THREAD

**Issue by lymansome** [ithewei/libhv#403]
HttpServer底层基于EventLoop，如何在HttpServer的对象中使用queueInLoop函数，尝试采用以下写法，但是编译报错，请问正确的写法是什么？
HttpServer http_server;
http_server.queueInLoop([](){
        printf("queueInLoop tid=%ld\n", hv_gettid());
    });

**Comment by ithewei** [comment]
HttpServer底层基于EventLoop没错，一个线程对应一个EventLoop，设置了多线程就有多个EventLoop，可以在[onWorkerStart](https://github.com/ithewei/libhv/blob/582f599d0e067d2f09b1403b88c5d5ef62fceefa/http/server/HttpServer.h#L28C27-L28C40)回调或者`http handler`回调里通过`currentThreadEventLoop`获取到当前线程的EvenLoop

**Comment by lymansome** [comment]
问题解决了，感谢。
