### ISSUE TITLE
如何关闭默认的日志输出那？

### ISSUE THREAD

**Issue by messi-gzy** [ithewei/libhv#405]
Http服务端如何关闭默认的日志文件，或者修改日志输出相对位置？

**Comment by ithewei** [comment]
`hlog_disable`，阅读 [FAQ](
https://github.com/ithewei/libhv/wiki/%E4%B8%AD%E6%96%87FAQ#q%E5%A6%82%E4%BD%95%E7%A6%81%E7%94%A8libhv%E9%BB%98%E8%AE%A4%E6%97%A5%E5%BF%97)
