### ISSUE TITLE
Q: How to handle blocking operations in the http server?

### ISSUE THREAD

**Issue by overthetop** [ithewei/libhv#406]
What is the proper way to handle blocking IO in the http handlers? 
In other words is it safe to have code like this:

router.GET("/paths", [&router](HttpRequest* req, HttpResponse* resp) {
        //have your blocking database call here
        std::this_thread::sleep_for(10ms);
        //
        return resp->Json(router.Paths());
  });

**Comment by ithewei** [comment]
refer to [FAQ](https://github.com/ithewei/libhv/wiki/FAQ#q-how-to-respond-asynchronously-by-http)
```
    // sync handler: run on IO thread
    router.POST("/echo", [](HttpRequest* req, HttpResponse* resp) {
        resp->content_type = req->content_type;
        resp->body = req->body;
        return 200;
    });

    // async handler：run on hv::async GlobalThreadPool
    router.POST("/echo", [](const HttpRequestPtr& req, const HttpResponseWriterPtr& writer) {
        writer->Begin();
        writer->WriteStatus(HTTP_STATUS_OK);
        writer->WriteHeader("Content-Type", req->GetHeader("Content-Type"));
        writer->WriteBody(req->body);
        writer->End();
    });

    // The handler with HttpContext parameter is the latest wording compatible with synchronous/asynchronous handler, it is recommended to use
    // The callback function runs on the IO thread, which can be thrown into the global thread pool for processing through hv::async, or its own consumer thread/thread pool
     // HttpContext contains HttpRequest and HttpResponseWriter member variables, referring to nodejs koa provides a series of member functions for operating HttpRequest and HttpResponse, and the writing is more concise
    router.POST("/echo", [](const HttpContextPtr& ctx) {
        return ctx->send(ctx->body(), ctx->type());
    });

    router.POST("/echo", [](const HttpContextPtr& ctx) {
        // The demo is thrown into the hv::async global thread pool for processing, but it is recommended to throw it into your own consumer thread/thread pool for actual use.
        hv::async([ctx]() {
            ctx->send(ctx->body(), ctx->type());
        });
        return 0;
    });
```

**Comment by overthetop** [comment]
@ithewei Thank you for the link.
I can see that for blocking calls we should use our own thread pool instead the global thread pool. Dose that mean that libhv is using the global thread pool for some internal workings? Can you please explain in which cases we should use the global thread pool hv::async in our code?

**Comment by ithewei** [comment]
No other work except http_async_handler will run in the `hv::aysnc` global thread pool.
Some tips:
- `std::async` has different implementations under different C++ runtime libraries, some are thread pools, some are to start a new thread on the spot, and the return value will also be blocked while waiting, not recommended, you can use `hv ::async` instead (requires #include “hasync.h”), you can configure the minimum number of threads, the maximum number of threads, and the maximum idle time of the global thread pool through `hv::async::startup`, `hv:: async::cleanup` is used to destroy the global thread pool;
- Regarding the consideration of whether it needs to be thrown into the consumer thread to process the request: In a scenario where the concurrency is not high, multithreading can be satisfied by setting worker_threads. It takes more than seconds to consider throwing `HttpContextPtr` to the consumer thread pool for processing;
