### ISSUE TITLE
停止事件循环的接口

### ISSUE THREAD

**Issue by gtoo8888** [ithewei/libhv#407]
通过查看看到libhv接口列表看到，停止事件循环，仅仅只有hloop_stop这一个接口
请问是否有像libevent那样，提供了event_del这个仅仅删除事件的功能

# 参考资料
[libhv接口列表](https://blog.csdn.net/GG_SiMiDa/article/details/103976875)
[event_del](https://libevent.org/doc/event_8h.html)

**Comment by ithewei** [comment]
`hio_del`

**Comment by gtoo8888** [comment]
感谢回复
