### ISSUE TITLE
how to print `right` error message after sending data through `TcpServer::write` which returned 0 bytes

### ISSUE THREAD

**Issue by WorstCodeWay** [ithewei/libhv#408]
After TcpServer::write sending data，0 bytes are sent，and the client doesn't receive data in deed。

I want to know why this happens, so I print `errno` by `strerror(errno)`
```
  printf("%s \n", strerror(errno));
```
and shows:
```
No such file or directory
```
Which is wrong message I think, isn't it?

If so, I wonder I how to print the right error message in my case?

**Comment by ithewei** [comment]
0 is normal, indicating that the system’s sending buffer is full, but it will be saved in the write queue of libhv, and will be sent when it is writable. Refer to [FAQ](https://github.com/ithewei/libhv/wiki/%E4%B8%AD%E6%96%87FAQ#q%E6%95%B0%E6%8D%AE%E9%87%8F%E8%BF%87%E5%A4%A7%E5%8F%91%E9%80%81%E8%BF%87%E5%BF%AB%E5%AF%BC%E8%87%B4%E6%96%AD%E9%93%BE%E6%83%85%E5%86%B5%E6%8E%92%E6%9F%A5)

**Comment by WorstCodeWay** [comment]
> 
Thanks!
