### ISSUE TITLE
Cannot detect client offline state after cable is pulled out

### ISSUE THREAD

**Issue by WorstCodeWay** [ithewei/libhv#410]
Hi, I find my server cannot detect client offline state after cable, connecting client and server, is pulled out.

Expected result? If so, how can I detect that state?

**Comment by ithewei** [comment]
The TCP connection is not a physical connection, but is maintained by the kernel. The default TCP keepalive time is very long. You can keep alive and judge the connection status through the application layer heartbeat

**Comment by xs-411** [comment]
电缆拔出,不发心跳,不发数据（发了数据就需要对方确认,一直确认超时就关闭了。）,永远无法感知

**Comment by WorstCodeWay** [comment]
> The TCP connection is not a physical connection, but is maintained by the kernel. The default TCP keepalive time is very long. You can keep alive and judge the connection status through the application layer heartbeat

`HeartBeats` is  cool, and I have already implemented it. Just wondering about knowledge of low level methods.

Anyway, many thanks. @ithewei

**Comment by WorstCodeWay** [comment]
Close this thread
