### ISSUE TITLE
HTTP body is always empty on aarch64 but not on x86_64

### ISSUE THREAD

**Issue by anuragvohraec** [ithewei/libhv#418]
Hi Team,

I have created  OPENSSL+WebSocket+HTTP server based on `libhv`. 
The code is done something like this :
```
HttpService http;
http.Any(&deploymentPath[0], [](const HttpContextPtr& httpCtx){
    return myCustomHandler(httpCtx);
});

hv::WebSocketServer server;
server.https_port=4000;

//SSL configuration
hssl_ctx_opt_t param;
memset(&param, 0, sizeof(param));
param.crt_file = "path/to_cert";
param.key_file ="path/to_key;
param.endpoint = HSSL_SERVER;
if (server.newSslCtx(&param) != 0) {
    std::cout << "Cannot do SSL" << std::endl;
}
//register HTTPService
server.registerHttpService(&http);

WebSocketService ws;
//coded onmessage , onclose and other event handling code

//register web socket service
server.registerWebSocketService(&ws);

server.setThreadNum(threadCount);
server.run();
```

This code is done to handle http request in `async` fashion.
This code works as expected on `x86_64` architecture, however when running it on `aarch64` its seems to not work.
**The body is always empty** if async way is followed.

Upon debugging we found out that the connection is getting closed  (on aarch64) before seding the body.
This piece of code from `hevent.c`  seems to be not behaving as expected on `aarch64`:
```
static void __keepalive_timeout_cb(htimer_t* timer) {
    hio_t* io = (hio_t*)timer->privdata;
    uint64_t last_rw_hrtime = MAX(io->last_read_hrtime, io->last_write_hrtime);
    uint64_t inactive_ms = (io->loop->cur_hrtime - last_rw_hrtime) / 1000;

    if (inactive_ms + 100 < io->keepalive_timeout) {
        htimer_reset(io->keepalive_timer, io->keepalive_timeout - inactive_ms);
    } else {
        if (io->io_type & HIO_TYPE_SOCKET) {
            char localaddrstr[SOCKADDR_STRLEN] = {0};
            char peeraddrstr[SOCKADDR_STRLEN] = {0};
            hlogw("keepalive timeout [%s] <=> [%s]",
                    SOCKADDR_STR(io->localaddr, localaddrstr),
                    SOCKADDR_STR(io->peeraddr, peeraddrstr));
        }
        io->error = ETIMEDOUT;
        hio_close(io);
    }
}
````

Here `io->keepalive_timeout` is lesser than `inactive_ms + 100` and that is why the `hio_close(io);` gets called.
**Can any leads be provided what possibly can be done, or is misconfigured by me, to avoid this problem ?**

Thank you again for all your help.

**Comment by anuragvohraec** [comment]
Upon on further investigating I found out that in `HttpServer.cpp`, in method `on_accept`
```
static void on_accept(hio_t* io) {
//line 241
 if (service->keepalive_timeout > 0) {

        // >>>> I need to manually pass timeout here = 75000, to make this work      
       //hio_set_keepalive_timeout(io, service->keepalive_timeout);
       hio_set_keepalive_timeout(io, 75000);  
 }
}
```

The problem is with the the `keepalive_timeout` on aarch64 (Raspberry Pi 4: Alpine aarch64)
How do one set it from outside.

I tried this , but they won't work:

```
//try 1
HttpService http;
http.keepalive_timeout=75000;

http.Any(&deploymentPath[0], [](const HttpContextPtr& httpCtx){
     //try 2
    httpCtx->service->keepalive_timeout=75000;
    return myCustomHandler(httpCtx);
});


//try3
server.service->keepalive_timeout=75000;
server.setThreadNum(threadCount);
server.run();
```

But none of them seems to work.
How do one enforce this keepalive timeout setting for a server with `openssl+http+websocket` server ?

**Comment by ithewei** [comment]
```
static void on_accept(hio_t* io) {
//line 241
 if (service->keepalive_timeout > 0) {

        // >>>> I need to manually pass timeout here = 75000, to make this work      
       //hio_set_keepalive_timeout(io, service->keepalive_timeout);
       hio_set_keepalive_timeout(io, 75000);  
 }
```
The default value of HttpService::keepalive_timeout is equal to 75000, how much does it equal in your environment?
Also, do your header files and library files match?

**Comment by anuragvohraec** [comment]
> The default value of HttpService::keepalive_timeout is equal to 75000, how much does it equal in your environment? 

When I print `service-->keepalive_timeout` it comes as 127 on my Raspberry Pi (aarch64)

> Also, do your header files and library files match?
Yes I copied my headers from the `include directory

For build instruction I used (inside my Raspberry Pi):

```
mkdir build
cd build
cmake .. -DWITH_OPENSSL=ON
cmake --build .
```
Do I need to configure it first for `aarch` aarchitecture info as well, while building it ?

**Comment by anuragvohraec** [comment]
> Also, do your header files and library files match?

Ok this was the problem, i did not replaced the header files. Sorry.
I included the old header files, which was causing the issue.
Many thanks for your help.
