### ISSUE TITLE
http服务存在越权漏洞

### ISSUE THREAD

**Issue by charlielven** [ithewei/libhv#425]
https://github.com/ithewei/libhv/blob/23ed8fbe22a4b270cef70d2924bab4f3f8fff2c2/http/server/HttpHandler.cpp#L501

在c:\myweb\http.exe部署程序时候
当使用
http://192.166.20.11:8088/..\..\..\..\..\..\..\..\..\..\windows\win.ini
又或者
http://192.166.20.11:8088/windows//..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5cwindows/win.ini
地址访问时存在越权漏洞

![image](https://github.com/ithewei/libhv/assets/3304285/675bd7ae-a18e-40be-9625-f58d29111b00)

**Comment by ithewei** [comment]
改成判断
`if (req_path[0] != '/' || strstr(req_path, "/..")) || strstr(req_path, "\\.."))`
你认为如何，可以的话提个PR吧

**Comment by charlielven** [comment]
> 改成判断 `if (req_path[0] != '/' || strstr(req_path, "/..")) || strstr(req_path, "\\.."))` 你认为如何，可以的话提个PR吧

好的，经测试，使用http://127.0.0.1:8088/windows%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5cwindows/win.ini这样的路径访问也可以拦截。

**Comment by zhaokaixs** [comment]
为什么同一份程序，有的机器有这个漏洞，有的机器部署却是404
