### ISSUE TITLE
What happens when WebSocketChannelPtr.id() are all used ?

### ISSUE THREAD

**Issue by anuragvohraec** [ithewei/libhv#426]
Hi ithewei,

`WebSocketChannelPtr.id()` is a `uint32_t`, which makes its maximum value upto `4,294,967,295`.
Upon simple testing, I see that the clients to websocket server gets new ID every time, upon every connection and disconnection.

On a server running for serveral days, with thousands or may be millions of clients, if they connect and disconnect this number seems reachable.

For writing a scalable solution on libhv, I do have a couple of questions of what happens when this counter for ID reaches its max value `4,294,967,295`. Assuming only this ID count has reached max, but active clients are way less than this count.

1. Will the count start from 1  after the max count ?
2. Can there be a case where two clients can have same ID ? , 
3. or Will server will only assign those ID currently not used ?

**Comment by ithewei** [comment]
1. The count start from 0 after the max count.
2. The IDs are simply accumulated and no idle judgment is made, so it is possible that two identical IDs exist. However, after one round, I think the probability that the client in the previous round is still alive is very small.

If such an extreme situation may exist in your scenario, do not use this id as the only expression. You can use the dual method of id+fd.
