### ISSUE TITLE
Crash by memory error when getting POST multipart form data param

### ISSUE THREAD

**Issue by fifa87** [ithewei/libhv#43]
I have tried to get form data param from request on postman or other c++ codes

static int preprocessor(HttpRequest* req, HttpResponse* resp) {
req->ParseBody();

return 0;
}

router.preprocessor = preprocessor;
router.POST("/uploadReport", [&router](HttpRequest* req, HttpResponse* resp) {
std::string fileName = req->GetString("report_name") + ".png";
return req->SaveFormFile("report", fileName.c_str());
});

but server is crashed by memory error in line which gets fileName
Would you help me?
Best Regards

**Comment by ithewei** [comment]
I tried, but couldn’t reproduce the crash.

**Comment by fifa87** [comment]
staticintpreprocessor(HttpRequest*req,HttpResponse*resp){req->ParseBody();

return0;
}


router.preprocessor=preprocessor;


router.POST("/uploadReport",[](HttpRequest*req,HttpResponse*resp){
std::stringfileName=req->GetString("report_name") + ".png";


returnreq->SaveFormFile("report_file",fileName.c_str());
});
this is my code
std::stringfileName=req->GetString("report_name") + ".png";
in this line, access error


Can you send your test code?
Best Regards.






| |
JCY
|
|
fifa87@126.com
|
签名由网易邮箱大师定制
On 2/4/2021 22:12，ithewei<notifications@github.com> wrote：

I tried, but couldn’t reproduce the crash.

**Comment by fifa87** [comment]
I used msvc 2017(x86) compiler.
Can you check with this?
Best Regards.


| |
JCY
|
|
fifa87@126.com
|
签名由网易邮箱大师定制
On 2/4/2021 22:36，ithewei<notifications@github.com> wrote：

#include "hv/HttpServer.h"

int main() {
    HttpService router;
    router.preprocessor = [](HttpRequest* req, HttpResponse* resp) {
        req->ParseBody();
        return 0;
    };
    router.POST("/uploadReport", [](HttpRequest* req, HttpResponse* resp) {
        std::string filename = req->GetString("report_name") + ".png";
        req->SaveFormFile("report", filename.c_str());
        return 200;
    });

    http_server_t server;
    server.port = 1234;
    server.service = &router;
    http_server_run(&server);
    return 0;
}


build step:

make clean && make && sudo make install
g++ -std=c++11 http_server_test.cpp -o http_server_test -lhv


test step:

./http_server_test
bin/curl -v localhost:1234/uploadReport -F 'report_name=test report=@LICENSE'

**Comment by fifa87** [comment]
Good morning
I will send screenshot of crash error
this libhv is easy to use. But some problems are exists.
Can you help me to fix it?
It is a urgent task. I will wait for your response.
Best Regards.




| |
JCY
|
|
fifa87@126.com
|
签名由网易邮箱大师定制
On 2/4/2021 22:46，JCY<fifa87@126.com> wrote：
I used msvc 2017(x86) compiler.
Can you check with this?
Best Regards.


| |
JCY
|
|
fifa87@126.com
|
签名由网易邮箱大师定制
On 2/4/2021 22:36，ithewei<notifications@github.com> wrote：

#include "hv/HttpServer.h"

int main() {
    HttpService router;
    router.preprocessor = [](HttpRequest* req, HttpResponse* resp) {
        req->ParseBody();
        return 0;
    };
    router.POST("/uploadReport", [](HttpRequest* req, HttpResponse* resp) {
        std::string filename = req->GetString("report_name") + ".png";
        req->SaveFormFile("report", filename.c_str());
        return 200;
    });

    http_server_t server;
    server.port = 1234;
    server.service = &router;
    http_server_run(&server);
    return 0;
}


build step:

make clean && make && sudo make install
g++ -std=c++11 http_server_test.cpp -o http_server_test -lhv


test step:

./http_server_test
bin/curl -v localhost:1234/uploadReport -F 'report_name=test report=@LICENSE'

**Comment by fifa87** [comment]
It is not fixed yet.
do you close this issue without testing?
