### ISSUE TITLE
cpp版本的TcpClient和TcpServer版本，使用setUnpack会解包失败

### ISSUE THREAD

**Issue by charlielven** [ithewei/libhv#431]
测试程序是基于evpp/TcpClient_test.cpp和evpp/TcpServer_test.cpp修改的，

TcpServer_test.cpp在srv.start前增加
```
	static unpack_setting_t s_unpack_setting;
	s_unpack_setting.mode = UNPACK_BY_DELIMITER;
	s_unpack_setting.package_max_length = DEFAULT_PACKAGE_MAX_LENGTH;
	s_unpack_setting.delimiter_bytes = 2;
	s_unpack_setting.delimiter[0] = '\r';
	s_unpack_setting.delimiter[1] = '\n';
	srv.setUnpack(&s_unpack_setting);

	srv.start();
```
  

TcpClient_test.cpp在cli.start前增加
```
	static unpack_setting_t s_unpack_setting;
	s_unpack_setting.mode = UNPACK_BY_DELIMITER;
	s_unpack_setting.package_max_length = DEFAULT_PACKAGE_MAX_LENGTH;
	s_unpack_setting.delimiter_bytes = 2;
	s_unpack_setting.delimiter[0] = '\r';
	s_unpack_setting.delimiter[1] = '\n';
	cli.setUnpack(&s_unpack_setting);
	
	cli.start();
```

**Comment by ithewei** [comment]
发包时有加上`\r\n`发送吗，发包是需要你自己加的，上面只是拆包

**Comment by ithewei** [comment]
也就是send的地方需要你发送`send(str+"\r\n");`

**Comment by charlielven** [comment]
服务端和客户端拆包改成
static unpack_setting_t s_unpack_setting;
s_unpack_setting.package_max_length = DEFAULT_PACKAGE_MAX_LENGTH;
s_unpack_setting.fixed_length = 0;
s_unpack_setting.delimiter_bytes = 0;
s_unpack_setting.body_offset = 5;
s_unpack_setting.length_field_offset = 1;
s_unpack_setting.length_field_bytes = 4;
s_unpack_setting.length_field_coding = ENCODE_BY_BIG_ENDIAN;
s_unpack_setting.length_adjustment = 0;
cli.setUnpack(&s_unpack_setting);
cli.start();

会报错，日志中错误是
2023-09-26 13:44:13.147 ERROR package length over 2097152 bytes! [unpack.c:163:hio_unpack_by_length_field]
2023-09-26 13:44:13.148 INFO  reconnect... cnt=1, delay=1000 [TcpClient.h:164:hv::TcpClientEventLoopTmpl<class hv::SocketChannel>::startReconnect]
2023-09-26 13:44:17.146 ERROR package length over 2097152 bytes! [unpack.c:163:hio_unpack_by_length_field]
2023-09-26 13:44:17.146 INFO  reconnect... cnt=1, delay=1000 [TcpClient.h:164:hv::TcpClientEventLoopTmpl<class hv::SocketChannel>::startReconnect]

![image](https://github.com/ithewei/libhv/assets/3304285/50b99617-15fd-411f-9cbd-e0e8d2d02b80)

**Comment by charlielven** [comment]
> 也就是send的地方需要你发送`send(str+"\r\n");`

加上"\r\n"后发送成功了。

**Comment by ithewei** [comment]
> 服务端和客户端拆包改成 static unpack_setting_t s_unpack_setting; s_unpack_setting.package_max_length = DEFAULT_PACKAGE_MAX_LENGTH; s_unpack_setting.fixed_length = 0; s_unpack_setting.delimiter_bytes = 0; s_unpack_setting.body_offset = 5; s_unpack_setting.length_field_offset = 1; s_unpack_setting.length_field_bytes = 4; s_unpack_setting.length_field_coding = ENCODE_BY_BIG_ENDIAN; s_unpack_setting.length_adjustment = 0; cli.setUnpack(&s_unpack_setting); cli.start();
> 
> 会报错，日志中错误是 2023-09-26 13:44:13.147 ERROR package length over 2097152 bytes! [unpack.c:163:hio_unpack_by_length_field] 2023-09-26 13:44:13.148 INFO reconnect... cnt=1, delay=1000 [TcpClient.h:164:hv::TcpClientEventLoopTmpl::startReconnect] 2023-09-26 13:44:17.146 ERROR package length over 2097152 bytes! [unpack.c:163:hio_unpack_by_length_field] 2023-09-26 13:44:17.146 INFO reconnect... cnt=1, delay=1000 [TcpClient.h:164:hv::TcpClientEventLoopTmpl::startReconnect]
> 
> ![image](https://user-images.githubusercontent.com/3304285/270548291-50b99617-15fd-411f-9cbd-e0e8d2d02b80.png)

拆包规则要和你的自定义协议一致，主要就是包头的设定，另外注意包头里长度字段的大小端编码问题

**Comment by charlielven** [comment]
> > 服务端和客户端拆包改成 static unpack_setting_t s_unpack_setting; s_unpack_setting.package_max_length = DEFAULT_PACKAGE_MAX_LENGTH; s_unpack_setting.fixed_length = 0; s_unpack_setting.delimiter_bytes = 0; s_unpack_setting.body_offset = 5; s_unpack_setting.length_field_offset = 1; s_unpack_setting.length_field_bytes = 4; s_unpack_setting.length_field_coding = ENCODE_BY_BIG_ENDIAN; s_unpack_setting.length_adjustment = 0; cli.setUnpack(&s_unpack_setting); cli.start();
> > 会报错，日志中错误是 2023-09-26 13:44:13.147 ERROR package length over 2097152 bytes! [unpack.c:163:hio_unpack_by_length_field] 2023-09-26 13:44:13.148 INFO reconnect... cnt=1, delay=1000 [TcpClient.h:164:hv::TcpClientEventLoopTmpl::startReconnect] 2023-09-26 13:44:17.146 ERROR package length over 2097152 bytes! [unpack.c:163:hio_unpack_by_length_field] 2023-09-26 13:44:17.146 INFO reconnect... cnt=1, delay=1000 [TcpClient.h:164:hv::TcpClientEventLoopTmpl::startReconnect]
> > ![image](https://user-images.githubusercontent.com/3304285/270548291-50b99617-15fd-411f-9cbd-e0e8d2d02b80.png)
> 
> 拆包规则要和你的自定义协议一致，主要就是包头的设定，另外注意包头里长度字段的大小端编码问题

明白了，是调用send或者write写数据时候，数据头应该要自己设置。之前一直以为只有设置了setUnpack后，我就不需要关注包头信息，以为hv库会自动帮我做这事。

**Comment by ithewei** [comment]
有时包头不仅仅包含长度字段，还包含magic、版本号、消息类型等字段，hv不知道如何组包头的，所以组包是需要自己做的，拆包也只是根据分界符或者包头长度字段说明收到一包完整的包才回调给你，解决断包和粘包问题，包头也是需要自己来解读的。
