### ISSUE TITLE
http_server_stop(&server); centos7下，无法停掉http server

### ISSUE THREAD

**Issue by FanSun126** [ithewei/libhv#432]
http_server_stop(&server);在windows下可以正常退出http server，终端会打印“Memcheck => alloc:99 free:99”，程序正常退出，程序再次启动可以正常启动；
但是在centos7下无法停止http server，停止的时候终端会打印“ is already stopped Memcheck => alloc:0 free:0”，此时http server程序还在后台运行，程序再次启动时会报错“bind: Address already in use”，http server 服务无法再次启动。

**Comment by ithewei** [comment]
`is already stopped`是`hmain.c`里打印的，通过信号量通知进程退出，说明你是使用了多进程模式的。
可以先kill干净之前的进程了，再重新测试。

**Comment by FanSun126** [comment]
是这样的，我看了一下源码，问题是程序正常退出的时候只是把主进程退掉了，但是子进程都还在后台运行，有没有办法可以把子进程也退掉，我测试了killall，但是并不是每次都有效。

**Comment by ithewei** [comment]
hmain.c的signal_handler里会killall所有进程的，你看看日志里是否有`killall processes`的打印

**Comment by ithewei** [comment]
可以参考examples/httpd，
```
bin/httpd -d # 后台运行
bin/httpd -s status  #查看状态
bin/httpd -s restart -d #重启进程
bin/httpd -s stop #停止进程
```
多进程模式后台程序是这么个信号控制方式

**Comment by FanSun126** [comment]
好的，我改成了多线程模式，对我的应用也没影响，可以正常退出了，多谢了。
