### ISSUE TITLE
GetParam获取的值不正确

### ISSUE THREAD

**Issue by cmoth150415** [ithewei/libhv#434]
如下请求
GET http://192.168.1.102:20005/api/v1/vec/import/files/detail?charset=gbk&layername=&path=POI_point.shp 
调用 `auto path = ctx->request->GetParam("path");` 获取的path值是空值，查看request的query_params内容，里面的值是
`{{"charset":"gbk"},{"path=POI_poin":"POI_point.shp"}}`。但如果layername有值，那么获取的path值就是对的。
我使用的libhv tag是v1.2.5。不知道是什么原因？

**Comment by ithewei** [comment]
见https://github.com/ithewei/libhv/issues/203
在v1.3.1版本中修复
