### ISSUE TITLE
循环发送大量数据时出现程序关闭现象【write bufsize > 16777216】

### ISSUE THREAD

**Issue by HellowAmy** [ithewei/libhv#437]
我是网络编程小白，请问我如何解决客户端向服务器发送大量信息时出现的自动关闭问题。
问题描述：
我编写一个客户端程序往服务器发送文件，文件大小为1G，在循环中读数据，读到数据时发。我是在一个循环中一直读取数据并发送，服务器与此同时也可以接收到部分消息。问题出现在于当数据逐渐累加时，超出了libhv设置的16M发送缓存队列，这时程序就会自动关闭。我试图在缓冲超出8M时使用sleep函数停止发送数据，等待libhv发送缓冲器队列中的数据我再继续发送，不过测试的结果是，我等待的时间里，libhv并没有自己主动的清空发送缓存，当我的sleep函数到期时，缓冲区数据没有减少。我不知道该如何连续的发送大量数据，请指教

日志中会出现：
2023-10-02 04:42:46.903 ERROR write bufsize > 16777216, close it! [nio.c:520:hio_write]

**Comment by silentcpp** [comment]
给你个代码参考一下吧.

void ServerWidget::onUpdateFile(const QString& directory)
{
	m_update_app.mutex.lock();
	m_update_app.files = utility::getFileListBySuffixName(directory, { ".exe" });
	m_update_app.mutex.unlock();

	uint32_t size = 40960;
	std::unique_ptr<char[]> buffer(new char[size]);
	hv::packet packet;
	while (!m_quit)
	{
		while (!m_update_app.queue.isEmpty())
		{
			m_update_app.mutex.lock();
			auto& pair = m_update_app.queue.first();
			bool exist = m_update_app.files.contains(pair.url);
			m_update_app.mutex.unlock();
			auto&& fileName = Q_TO_S_STR(QFileInfo(pair.url).fileName());

			if (!exist)
			{
			file_is_not_exist:
				hv::json json;
				json[command_code_key] = command_recv_file_response;
				json[error_code_key] = tcp_update_directory_not_exist_latest_version_file;
				json[error_string_key] = "更新文件不存在";
				packet.append(json).pack();
				pair.channel->write(packet.data(), packet.size());
			}
			else
			{
				FILE* file = fopen(Q_TO_LC_STR(pair.url), "rb");
				if (!file)
				{
					goto file_is_not_exist;
				}

				fseek(file, SEEK_SET, SEEK_END);
				int64_t fileSize = _ftelli64(file);
				fseek(file, SEEK_SET, SEEK_SET);

				while (!feof(file))
				{
					uint32_t once = fread(buffer.get(), 1, size, file);
					hv::json json;
					json[command_code_key] = command_recv_file_response;
					json[error_code_key] = tcp_ok;
					json[error_string_key] = "ok";
					json["file_name"] = fileName;
					json["file_size"] = fileSize;
					json["file_feof"] = static_cast<bool>(feof(file));
					json["data_size"] = once;

					packet.append(json).append(buffer.get(), once).pack();

					//如果写入队列已满会导致客户端掉线,此处需要等待
				wait_write_complete:
					if (!pair.channel->isWriteComplete())
					{
						if (!pair.channel->isOpened())
						{
							break;
						}
						Sleep(1);
						goto wait_write_complete;
					}

					if (pair.channel->write(packet.data(), packet.size()) < 0)
					{
						break;
					}
				}
				fclose(file);
			}

			m_update_app.mutex.lock();
			m_update_app.queue.removeFirst();
			m_update_app.mutex.unlock();
		}
		std_sleep_milliseconds(100);
	}
}

**Comment by silentcpp** [comment]
给你个demo参考一下.


void ServerWidget::onUpdateFile(const QString& directory)
{
	m_update_app.mutex.lock();
	m_update_app.files = utility::getFileListBySuffixName(directory, { ".exe" });
	m_update_app.mutex.unlock();

	uint32_t size = 40960;
	std::unique_ptr<char[]> buffer(new char[size]);
	hv::packet packet;
	while (!m_quit)
	{
		while (!m_update_app.queue.isEmpty())
		{
			m_update_app.mutex.lock();
			auto& pair = m_update_app.queue.first();
			bool exist = m_update_app.files.contains(pair.url);
			m_update_app.mutex.unlock();
			auto&& fileName = Q_TO_S_STR(QFileInfo(pair.url).fileName());

			if (!exist)
			{
			file_is_not_exist:
				hv::json json;
				json[command_code_key] = command_recv_file_response;
				json[error_code_key] = tcp_update_directory_not_exist_latest_version_file;
				json[error_string_key] = "更新文件不存在";
				packet.append(json).pack();
				pair.channel->write(packet.data(), packet.size());
			}
			else
			{
				FILE* file = fopen(Q_TO_LC_STR(pair.url), "rb");
				if (!file)
				{
					goto file_is_not_exist;
				}

				fseek(file, SEEK_SET, SEEK_END);
				int64_t fileSize = _ftelli64(file);
				fseek(file, SEEK_SET, SEEK_SET);

				while (!feof(file))
				{
					uint32_t once = fread(buffer.get(), 1, size, file);
					hv::json json;
					json[command_code_key] = command_recv_file_response;
					json[error_code_key] = tcp_ok;
					json[error_string_key] = "ok";
					json["file_name"] = fileName;
					json["file_size"] = fileSize;
					json["file_feof"] = static_cast<bool>(feof(file));
					json["data_size"] = once;

					packet.append(json).append(buffer.get(), once).pack();

					//如果写入队列已满会导致客户端掉线,此处需要等待
				wait_write_complete:
					if (!pair.channel->isWriteComplete())
					{
						if (!pair.channel->isOpened())
						{
							break;
						}
						Sleep(1);
						goto wait_write_complete;
					}

					if (pair.channel->write(packet.data(), packet.size()) < 0)
					{
						break;
					}
				}
				fclose(file);
			}

			m_update_app.mutex.lock();
			m_update_app.queue.removeFirst();
			m_update_app.mutex.unlock();
		}
		std_sleep_milliseconds(100);
	}
}

**Comment by silentcpp** [comment]
给你个例子参考一下

void ServerWidget::onUpdateFile(const QString& directory)
{
	m_update_app.mutex.lock();
	m_update_app.files = utility::getFileListBySuffixName(directory, { ".exe" });
	m_update_app.mutex.unlock();
	uint32_t size = 40960;
	std::unique_ptr<char[]> buffer(new char[size]);
	hv::packet packet;
	while (!m_quit)
	{
		while (!m_update_app.queue.isEmpty())
		{
			m_update_app.mutex.lock();
			auto& pair = m_update_app.queue.first();
			bool exist = m_update_app.files.contains(pair.url);
			m_update_app.mutex.unlock();
			auto&& fileName = Q_TO_S_STR(QFileInfo(pair.url).fileName());

			if (!exist)
			{
			file_is_not_exist:
				hv::json json;
				json[command_code_key] = command_recv_file_response;
				json[error_code_key] = tcp_update_directory_not_exist_latest_version_file;
				json[error_string_key] = "更新文件不存在";
				packet.append(json).pack();
				pair.channel->write(packet.data(), packet.size());
			}
			else
			{
				FILE* file = fopen(Q_TO_LC_STR(pair.url), "rb");
				if (!file)
				{
					goto file_is_not_exist;
				}

				fseek(file, SEEK_SET, SEEK_END);
				int64_t fileSize = _ftelli64(file);
				fseek(file, SEEK_SET, SEEK_SET);

				while (!feof(file))
				{
					uint32_t once = fread(buffer.get(), 1, size, file);
					hv::json json;
					json[command_code_key] = command_recv_file_response;
					json[error_code_key] = tcp_ok;
					json[error_string_key] = "ok";
					json["file_name"] = fileName;
					json["file_size"] = fileSize;
					json["file_feof"] = static_cast<bool>(feof(file));
					json["data_size"] = once;

					packet.append(json).append(buffer.get(), once).pack();

					//如果写入队列已满会导致客户端掉线,此处需要等待
				wait_write_complete:
					if (!pair.channel->isWriteComplete())
					{
						if (!pair.channel->isOpened())
						{
							break;
						}
						Sleep(1);
						goto wait_write_complete;
					}

					if (pair.channel->write(packet.data(), packet.size()) < 0)
					{
						break;
					}
				}
				fclose(file);
			}
			m_update_app.mutex.lock();
			m_update_app.queue.removeFirst();
			m_update_app.mutex.unlock();
		}
		std_sleep_milliseconds(100);
	}
}

**Comment by HellowAmy** [comment]
非常感谢 @XinMIng 提供的参考代码。
   在提出这个问题的时候，我使用的是伪代码部分的循环发送，目的是快速发送出大体积的数据，并不希望使用延时发送，因为想吃满网络，不想错过延时的发送时机以提高速度。我使用writeBufsize()检查缓存是否到达高压线，如果触发高压线则等待libhv发送完成。不过我多次测试发现，一旦进入了writeBufsize()检测高压线的循环之后，就出不来了，我打印了writeBufsize()的值一直保持不变，死循环。这个问题不知道是什么引发的，与我预想的等待发送结果有偏差（不知道是否与开发环境有关：虚拟机Debian12 + Qt6Widget客户端）。不知道为什么数据进入libhv的发送缓存区之后不会被发送出去，我试图调用send函数发送空数据触发缓冲区，不过没有效果。
   我没有深入了解为什么缓冲区的数据没有被发送，而是采用了分段触发的方式发送数据，利用libhv中channel类提供的onWriteComplete()写入回调检查数据是否发送完成，来触发分段数据发送。我在下面附上分段触发的代码，希望有类似需求且碰到同样的问题时提供参考。

下面附上分段触发代码和失败的例子-伪代码两段代码：
   


   //== 分段触发代码 ==
//== 发送部分 == 
  //打开文件
                fs_status *st = &it->second;
[chat格式记录.txt](https://github.com/ithewei/libhv/files/12795296/chat.txt)

                st->swap_id = id;

                bool ok = _swap_fs.open_file_send(id,st->filename,func_send);
                vlogi("open:" $(id) $(ok));

                if(ok)
                {
                    //启动异步发送
                    hv::Buffer buf;
                    _wc.get_wc()->onWriteComplete(_wc.get_wc()->channel,&buf);
                }
//== 发送部分 == 

//== 触发部分 ==
    typedef std::shared_ptr<hv::WebSocketChannel> TSocketChannelPtr;
    _wc.get_wc()->onWriteComplete = [=](const TSocketChannelPtr& channel, hv::Buffer*) {

        //发送提示：利用ping/pong出发write发送回调，控制发送文件流量
        if(channel->isWriteComplete()
            && _map_upload_status.size() > 0)
        {
            for(auto it = _map_upload_status.begin();it != _map_upload_status.end();it++)
            {
                fs_status *st = &it->second;
                int64 id = st->swap_id;

                if(st->state == e_pause || st->state == e_first)
                {
                    //写入文件
                    bool is_end = false;
                    st->state = e_sending;
                    bool ok = _swap_fs.add_data_send(id,is_end);
                    st->state = e_pause;

                    //关闭文件
                    if(is_end || ok == false)
                    {
                        st->state = e_end;
                        _swap_fs.close_file_send(id);
                        _map_upload_status.erase(it);
                    }
                }
            }
        }
    };
//== 触发部分 ==


//== 文件读写类 ==
typedef std::function<bool(int64 id,const string &data)> Tfn_send_cb;

//!
//! 类说明： 提供发送与接收网络传输文件的读写管理，支持多文件多文件多线程
//!             利用唯一 ID 绑定文件流
//!
class swap_files
{
public:
    struct fs_recv
    {
        fs_recv(int64 n1,int64 n2,string n3,shared_ptr<fstream> n4)
            : count_recv(n1),length_max(n2),filename(n3),sp_fs(n4) {}

        int64 count_recv;           //累加接收
        int64 length_max;           //文件长度
        string filename;            //文件名称
        shared_ptr<fstream> sp_fs;  //写入句柄
    };

    struct fs_send
    {
        fs_send(int64 n1,int64 n2,string n3,shared_ptr<fstream> n4,Tfn_send_cb n5)
            : count_send(n1),length_max(n2),filename(n3),sp_fs(n4),fn_send_cb(n5) {}

        int64 count_send;           //累加发送
        int64 length_max;           //文件长度
        string filename;            //文件名称
        shared_ptr<fstream> sp_fs;  //读取句柄

        //发送回调：自定义发送文件
        //参数：[id: 唯一id，用于定位写入流] [data: 读取的数据]
        //返回值：true时继续发送，false时终止发送，需要重新调用发送函数
        //typedef std::function<bool(int64 id,const string &data)> Tfn_send_cb;
        Tfn_send_cb fn_send_cb;
    };

public:
    swap_files() {}

    static bool is_file(const string &path)
    {  return std::filesystem::is_regular_file(path); }

    static bool is_exists(const string &path)
    { return std::filesystem::exists(path); }

    static bool remove_file(const string &path)
    { return std::filesystem::remove(path); }

    static int64 get_file_size(const string &path)
    { return std::filesystem::file_size(path); }

    static string get_filename_none(const string &path)
    {
        std::filesystem::path p = path;
        return p.stem();
    }

    static string get_filename(const string &path)
    {
        std::filesystem::path p = path;
        return p.filename();
    }

    static string get_extension(const string &path)
    {
        std::filesystem::path p = path;
        return p.extension();
    }

    static bool is_can_read(const string &path)
    {
        typedef std::filesystem::perms perms;
        namespace fs = std::filesystem;
        if((fs::status(path).permissions() & perms::owner_read) != perms::none) return true;
        return false;
    }

    static string make_none_repeat_file(const string &in_path,const string &in_filename)
    {
        string filename;
        string abs_file = in_path+"/"+in_filename;
        if(is_exists(abs_file))
        {
            string file_none = get_filename_none(in_filename);
            file_none += "_";
            filename = file_none + get_extension(in_filename);
        }
        else return in_filename;
        return make_none_repeat_file(in_path,filename);
    }


    //== 发送函数 ：多次完成 ==
    bool open_file_send(int64 id,const string &filename,Tfn_send_cb fn_send_cb)
    {
        std::unique_lock<std::mutex> lock(_mut_send);
        if(_map_send.find(id) != _map_send.end()) return false;

        shared_ptr sp_fs = std::make_shared<fstream>(filename,std::ios::in | std::ios::binary);
        if(sp_fs->is_open())
        {
            _map_send.emplace(id,std::make_shared<fs_send>(0, get_file_size(filename), filename,sp_fs,fn_send_cb));
            return true;
        }
        else return false;
    }

    bool add_data_send(int64 id,bool &is_send)
    {
        auto it =_map_send.find(id);
        if(it != _map_send.end())
        {
            auto sp_send = it->second;

            char buf[1024];
            while(sp_send->sp_fs->eof() == false)
            {
                {
                    std::unique_lock<std::mutex> lock(_mut_send);
                    sp_send->sp_fs->read(buf,sizeof(buf));
                }
                size_t size_read = sp_send->sp_fs->gcount();
                sp_send->count_send += size_read;

                is_send = sp_send->fn_send_cb(id,string(buf,size_read));
                if(is_send == false) break;
            }
        }
        else return false;

        return true;
    }

    void close_file_send(int64 id)
    {
        std::unique_lock<std::mutex> lock(_mut_send);
        auto it = _map_send.find(id);
        if(it != _map_send.end())
        {
            auto sp_send = it->second;
            sp_send->sp_fs->close();
        }
    }
    //== 发送函数 ：多次完成 ==



    //== 接收函数 ：多次完成 ==
    bool open_file_recv(int64 id,int64 length_max, const string &filename)
    {
        std::unique_lock<std::mutex> lock(_mut_recv);
        if(_map_recv.find(id) != _map_recv.end()) return false;

        shared_ptr sp_fs = std::make_shared<fstream>(filename,std::ios::out | std::ios::binary);
        if(sp_fs->is_open())
        {
            _map_recv.emplace(id,std::make_shared<fs_recv>(0, length_max, filename,sp_fs));
            return true;
        }
        else return false;
    }

    bool add_data_recv(int64 id,const string &data)
    {
        auto it = _map_recv.find(id);
        if(it != _map_recv.end())
        {
            auto sp_send = it->second;
            {
                std::unique_lock<std::mutex> lock(_mut_recv);
                sp_send->sp_fs->write(data.c_str(),data.size());
            }
            bool ok = sp_send->sp_fs->good();
            if(ok) sp_send->count_recv += data.size();
            return ok;
        }
        else return false;
    }

    void close_file_recv(int64 id)
    {
        std::unique_lock<std::mutex> lock(_mut_recv);
        auto it = _map_recv.find(id);
        if(it != _map_recv.end())
        {
            auto sp_send = it->second;
            sp_send->sp_fs->close();
        }
    }
    //== 接收函数 ：多次完成 ==

    std::shared_ptr<fs_recv> find_fs_recv(int64 id)
    {
        auto it = _map_recv.find(id);
        if(it != _map_recv.end())
        { return it->second; }
        else return nullptr;
    }

    std::shared_ptr<fs_send> find_fs_send(int64 id)
    {
        auto it = _map_send.find(id);
        if(it != _map_send.end())
        { return it->second; }
        else return nullptr;
    }

protected:
    mutex _mut_recv;
    mutex _mut_send;
    map<int64,std::shared_ptr<fs_recv>> _map_recv;
    map<int64,std::shared_ptr<fs_send>> _map_send;
};

#endif // SWAP_FILES_H
//== 文件读写
[swap_files.txt](https://github.com/ithewei/libhv/files/12795287/swap_files.txt)
类 ==
   //== 分段触发代码 ==

   
    //== 失败的例子-伪代码 ==
    #define WRITE_BUFSIZE_HIGH_WATER    (1U << 23)  // 8M

    //外部发送函数
    auto fn_send = [=](int64 id,const string &data) {
        if(hv_channel->isConnected() == false) return false;

        //发送，检测到高压线是暂停
        hv_send(id,data);
        if(hv_channel->writeBufsize() >= WRITE_BUFSIZE_HIGH_WATER)
        {
            while(true)
            {
                if(hv_channel->isWriteComplete()) return break;
            }
        }
        return true;
    };

    //读文件
    auto fn_upload = [](std::function<bool(int64 id,const string &data)> fn_send ,int64 id,string filename){
        bool is_finish = false;
        fstream fs(filename);
        if(fs.is_open())
        {

            char buf[1024];
            while(fs.eof() == false)
            {
                fs.read(buf,sizeof(buf));
                int size_read = fs.gcount();
                is_finish = fn_send(id,string(buf,size_read));
                if(is_finish == false) break;
            }
            fs.close();
        }
        return is_finish;
    };

    //调用
[swap_files.txt](https://github.com/ithewei/libhv/files/12795289/swap_files.txt)

    fn_upload(fn_send,id,filename);
    //== 失败的例子-伪代码 ==

**Comment by silentcpp** [comment]
你说的“目的是快速发送出大体积的数据，并不希望使用延时发送，因为想吃满网络，不想错过延时的发送时机以提高速度”。

发送队列已经满了则证明网络带宽已经跑满了。。。

**Comment by xs-411** [comment]
在实际的业务中,如果遇到一次需要write很多数据,难道还要单独搞一个线程去写？如果在io回调的时候去处理的话，会阻塞IO啊。

**Comment by ithewei** [comment]
`channel->write`（c接口即`hio_write`）是非阻塞的（事件循环异步编程里所有的一切都要求是非阻塞的），且多线程安全的。
发送大数据时应该做流控，通过`onWriteComplete`监听写完成事件，在可写时再发送下一帧数据。
具体示例代码可参考 [examples/tinyhttpd.c](https://github.com/ithewei/libhv/blob/master/examples/tinyhttpd.c) 中的 http_serve_file。

**Comment by HellowAmy** [comment]
我发现如果要跑满宽带还开启了ping/pong的话，服务器写入会因为暴栈无法发送出pong，客户端即使正在接收服务器的数据，但是因为ping/pong超时客户端会自动断开连接。只能做流控回应，或者在数据流中手动穿插ping/pong信息
