### ISSUE TITLE
是否可以不要回调？

### ISSUE THREAD

**Issue by baidwwy** [ithewei/libhv#438]
就是lua没法做回调
主动向io获取是否有连接
是否有数据

**Comment by xs-411** [comment]
lua也可以绑定函数啊,回调为啥没法做？

**Comment by ithewei** [comment]
非阻塞IO就是处处回调，没有回调那就是同步阻塞IO了，或者使用了协程语法。另外lua里支持函数作为参数传递。

**Comment by baidwwy** [comment]
> 非阻塞IO就是处处回调，没有回调那就是同步阻塞IO了，或者使用了协程语法。另外lua里支持函数作为参数传递。

我的程序是纯Lua的，进入Lua后就是死循环了，内容都是从Lua下C拉取，不能直接CALL Lua,这样的话，那我收到消息只能COPY一份了，等Lua拉
