### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by fifa87** [ithewei/libhv#44]
write access violation exception error
(throw exception from _Mtx_lockX)

in the following codes:

 HV_MEMCHECK;

 HttpService router;
http_server_t server;
server.port = 8081;
server.service = &router;

 http_server_run(&server);

I have built libhv in MSVC 2017 x64.

your last commit is worse than previous commit.
I hope you upload new commit after test is done.
I will give up to use this library.

**Comment by ithewei** [comment]
You should first check whether it is caused by a mismatch between the header file and the library file, or run httpd to test.

**Comment by fifa87** [comment]
If header and library files are mismatch, it can't be built.
building is done successfully.
run time error is occur.
on previous commit, no this error


| |
JCY
|
|
fifa87@126.com
|
签名由网易邮箱大师定制
On 2/22/2021 17:54，ithewei<notifications@github.com> wrote：

You should first check whether it is caused by a mismatch between the header file and the library file, or run httpd to test.

**Comment by fifa87** [comment]
I had built in qt creator. but it occurs runtime error. i can't know the reason yet.
I tried to build it in visual studio. after all it has been succeed.
I will use it in visual studio.

**Comment by ithewei** [comment]
Add or delete structure fields, only replacing library files, can also be compiled, but it may cause unknown memory errors. Therefore, it is recommended to clean up the environment to ensure that the header files and library files match.
