### ISSUE TITLE
Wanna customize content_type HttpMessage::Data(void *data, int len,)

### ISSUE THREAD

**Issue by sea-kg** [ithewei/libhv#441]
![изображение](https://github.com/ithewei/libhv/assets/1695720/c1bc64e3-fc67-41c4-8ceb-8040e23fe035)

Please add new argument in `HttpMessage::Data`
```
HttpMessage::Data(void *data, int len, bool nocopy = true, content_type = APPLICATION_OCTET_STREAM)
```

Form HttpMessage.h
```
...
   int Data(void* data, int len, bool nocopy = true) {
        content_type = APPLICATION_OCTET_STREAM;
        if (nocopy) {
            content = data;
            content_length = len;
        } else {
            content_length = body.size();
            body.resize(content_length + len);
            memcpy((void*)(body.data() + content_length), data, len);
            content_length += len;
        }
        return 200;
    }
...
```

I have binary data in memory and wanna send them without unpack to file system.

**Comment by ithewei** [comment]
You can set content_type after call HttpMessage::Data() function.

**Comment by sea-kg** [comment]
Thanks for the your answer! I just patched function Data in copied version of sources code.

![изображение](https://github.com/ithewei/libhv/assets/1695720/1b180a91-a80f-4cc7-b7b4-25f95a3a8e03)
![изображение](https://github.com/ithewei/libhv/assets/1695720/12ba096d-5aad-46ff-ab2b-e44a66d631bd)

But your variant is better. Thanks for your project!
