### ISSUE TITLE
HttpServer的Handler问题请教

### ISSUE THREAD

**Issue by hdcscy** [ithewei/libhv#444]
监控静态资源，可以用Service对象的Static函数实现。
其中，Service有staticHandler成员用来自定义handler对静态资源的处理，这很棒。
handler的定义有几种：

// NOTE: http_sync_handler run on IO thread
typedef std::function<int(HttpRequest* req, HttpResponse* resp)>                            http_sync_handler;

// NOTE: http_async_handler run on hv::async threadpool
typedef std::function<void(const HttpRequestPtr& req, const HttpResponseWriterPtr& writer)> http_async_handler;

// NOTE: http_ctx_handler run on IO thread, you can easily post HttpContextPtr to your consumer thread for processing.
typedef std::function<int(const HttpContextPtr& ctx)>                                       http_ctx_handler;

// NOTE: http_state_handler run on IO thread
typedef std::function<int(const HttpContextPtr& ctx, http_parser_state state, const char* data, size_t size)> http_state_handler;

均未发现可以获取request ssl信息的地方。
因此，若服务器想通过证书或者公钥去验证客户端身份，则无法实现。
请问下作者老大，handler中有无其他方式获取request ssl信息？

**Comment by ithewei** [comment]
设置verify_peer=1就会自动验证对端证书的

**Comment by hdcscy** [comment]
> 设置verify_peer=1就会自动验证对端证书的

感谢老大回复。
“自动验证对端证书”指的是验证身份还是指验证证书的有效性？
比如说客户端内置的证书是固定的，服务器不希望有人伪造证书（例如防各类抓包工具等），所以才验证客户端的证书信息。

**Comment by ithewei** [comment]
实际也是调用了openssl，具体实现你可以看下ssl/openssl.c，如果需要拿到ssl证书内容，你需要自己去修改源码了

**Comment by hdcscy** [comment]
> 实际也是调用了openssl，具体实现你可以看下ssl/openssl.c，如果需要拿到ssl证书内容，你需要自己去修改源码了

OK的，只能改源码了。许可方面有什么需要注意的吗？

**Comment by ithewei** [comment]
遵循LICENSE就行
