### ISSUE TITLE
TcpServer send one time, multiple `onWriteComplete` triggered

### ISSUE THREAD

**Issue by WorstCodeWay** [ithewei/libhv#446]
As title, `onWriteComplete` of TcpServer is triggered multiple times when sending a large buffer data.

Is that designed?

Sending 2908730 bytes one time, but `onWriteComplete` is called 14 times, and sum of bytes is equal to total bytes, as following:
```
[D][VT][28446][2023/10/19 17:25:09:279] [TcpJsonPacket] Protocal json data <2908730|2908706>.
[D][VT][28446][2023/10/19 17:25:09:284] [TcpServers] Send data completed <0.0.0.0_20013|110048>.
[D][VT][28440][2023/10/19 17:25:09:286] [TcpServers] Send data completed <0.0.0.0_20013|105704>.
[D][VT][28440][2023/10/19 17:25:09:288] [TcpServers] Send data completed <0.0.0.0_20013|234576>.
[D][VT][28440][2023/10/19 17:25:09:289] [TcpServers] Send data completed <0.0.0.0_20013|195480>.
[D][VT][28440][2023/10/19 17:25:09:291] [TcpServers] Send data completed <0.0.0.0_20013|195480>.
[D][VT][28440][2023/10/19 17:25:09:292] [TcpServers] Send data completed <0.0.0.0_20013|130320>.
[D][VT][28440][2023/10/19 17:25:09:294] [TcpServers] Send data completed <0.0.0.0_20013|260640>.
[D][VT][28440][2023/10/19 17:25:09:296] [TcpServers] Send data completed <0.0.0.0_20013|195480>.
[D][VT][28440][2023/10/19 17:25:09:297] [TcpServers] Send data completed <0.0.0.0_20013|195480>.
[D][VT][28440][2023/10/19 17:25:09:299] [TcpServers] Send data completed <0.0.0.0_20013|260640>.
[D][VT][28440][2023/10/19 17:25:09:301] [TcpServers] Send data completed <0.0.0.0_20013|260640>.
[D][VT][28440][2023/10/19 17:25:09:302] [TcpServers] Send data completed <0.0.0.0_20013|260640>.
[D][VT][28440][2023/10/19 17:25:09:307] [TcpServers] Send data completed <0.0.0.0_20013|260640>.
[D][VT][28440][2023/10/19 17:25:09:309] [TcpServers] Send data completed <0.0.0.0_20013|242962>.
```

Is it possible `onWriteComplete` is called one time no matter after sending how many bytes?

**Comment by ithewei** [comment]
The design is like this. Once sent, it will be called back immediately.

**Comment by WorstCodeWay** [comment]
> The design is like this. Once sent, it will be called back immediately.

If you not mind me to confirm following:

> Do you mean `onWriteComplete ` is called multiple times although sending one frame only is designed. Such like, I send 2908730 bytes one time, but `onWriteComplete` can be called about 14 times, and once time with small amount bytes, 110048, 105704, 234576 and so on. While sum of them is 2908730.

**Comment by ithewei** [comment]
Yes, sending may trigger onWriteComplete once or multiple times. You can count the number of bytes sent by yourself, or call isWriteComplete to determine whether the sending has been completed.

**Comment by WorstCodeWay** [comment]
> Yes, sending may trigger onWriteComplete once or multiple times. You can count the number of bytes sent by yourself, or call isWriteComplete to determine whether the sending has been completed.

OK. Maybe we can just trigger once when sending done due to we already have the `isWriteComplete ` logic. That should be better, right?
