### ISSUE TITLE
Why does async_handler not support interceptors

### ISSUE THREAD

**Issue by wang-yong-jie** [ithewei/libhv#447]
请问HttpService支持前置拦截器吗，我只看到有中间件的实现，当时无法通过中间件去实现前置拦截的效果

**Comment by wang-yong-jie** [comment]
![image](https://github.com/ithewei/libhv/assets/55249325/5827df07-2015-4575-9525-d5533906ab82)

**Comment by ithewei** [comment]
HttpService::preprocessor前置处理器、或者HttpService::Use(middleware)中间件方式，都可以实现前置拦截。
当然preprocessor和middleware本身是不支持异步handler的。
