### ISSUE TITLE
consul的示例没有写Tags的部分

### ISSUE THREAD

**Issue by dzming-git** [ithewei/libhv#448]

**Comment by ithewei** [comment]
示例代码，自己根据json内容加不是很简单的事

**Comment by dzming-git** [comment]
> 示例代码，自己根据json内容加不是很简单的事

抱歉，我没有说明清楚，我自然知道是很简单的事情，只是看您concil.cpp里面的注释里面发送的报文写了Tags，但代码里没写，以为是您不小心遗漏了，造成了误解，不好意思
