### ISSUE TITLE
使用mingw810_64编译1.3.2版本出现问题

### ISSUE THREAD

**Issue by aron566** [ithewei/libhv#456]
^
[ 29%] Building C object CMakeFiles/hv.dir/http/wsdef.c.obj
[ 29%] Building CXX object CMakeFiles/hv.dir/http/server/FileCache.cpp.obj
[ 30%] Building CXX object CMakeFiles/hv.dir/http/server/HttpHandler.cpp.obj
[ 30%] Building CXX object CMakeFiles/hv.dir/http/server/HttpMiddleware.cpp.obj
[ 31%] Building CXX object CMakeFiles/hv.dir/http/server/HttpResponseWriter.cpp.obj
[ 31%] Building CXX object CMakeFiles/hv.dir/http/server/HttpServer.cpp.obj
[ 32%] Building CXX object CMakeFiles/hv.dir/http/server/HttpService.cpp.obj
[ 33%] Building CXX object CMakeFiles/hv.dir/http/server/http_page.cpp.obj
[ 33%] Building CXX object CMakeFiles/hv.dir/http/client/AsyncHttpClient.cpp.obj
[ 34%] Building CXX object CMakeFiles/hv.dir/http/client/HttpClient.cpp.obj
[ 34%] Building CXX object CMakeFiles/hv.dir/http/client/WebSocketClient.cpp.obj
[ 35%] Linking CXX shared library bin\libhv.dll
CMakeFiles\hv.dir/objects.a(wepoll.c.obj):wepoll.c:(.text+0x1f10): undefined reference to `InterlockedAdd'
CMakeFiles\hv.dir/objects.a(wepoll.c.obj):wepoll.c:(.text+0x1f2e): undefined reference to `InterlockedAdd'
CMakeFiles\hv.dir/objects.a(wepoll.c.obj):wepoll.c:(.text+0x1f60): undefined reference to `InterlockedAdd'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [CMakeFiles\hv.dir\build.make:1170: bin/libhv.dll] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:152: CMakeFiles/hv.dir/all] Error 2
mingw32-make: *** [Makefile:135: all] Error 2

**Comment by ithewei** [comment]
InterlockedAdd应该是kernel32里面的，可以试试显式在cmake里添加-lkernel32
