### ISSUE TITLE
libhv support the signal event

### ISSUE THREAD

**Issue by Huangxiaodui** [ithewei/libhv#459]
We wish to use the event function of libhv to replace libevent in the openEuler community. However, during verification, we found that the signal event is missing in the event function, so we hope to add the event function of signal.
If possible, can we promote libhv in the openEuler community together, such as migrating the mirror repository on Gitee to the openEuler community repository?

**Comment by ithewei** [comment]
Welcome to promote libhv in the openEuler community and migrate the mirror repository on Gitee to the openEuler community repository.

**Comment by ithewei** [comment]
Thanks, I have implement signal event, just refer to https://github.com/ithewei/libhv/commit/6ad0d72530ae5c2b8d24c5823169954b8f82993c
