### ISSUE TITLE
https服务器的教程

### ISSUE THREAD

**Issue by hddhdwhdd** [ithewei/libhv#461]
请问有https服务器编写的例子吗

**Comment by ithewei** [comment]
[examples/http_server_test.cpp](https://github.com/ithewei/libhv/blob/master/examples/http_server_test.cpp) TEST_HTTPS

**Comment by hnustxiaoj** [comment]
你好，请问下，最新的libhv不提供C语言方式运行https服务了吗？

**Comment by ithewei** [comment]
c语言版本的http服务参考[examples/tinyhttpd.c](https://github.com/ithewei/libhv/blob/master/examples/tinyhttpd.c)
