### ISSUE TITLE
hv_strncat 和 strncat的size_t n 的用法不太一样

### ISSUE THREAD

**Issue by spiderpigpig** [ithewei/libhv#464]
strncat(char *dest,char *src, int n); 
strncat 的参数 n 是字符串src的开头拷贝n 个字符到dest字符串尾部

char* hv_strncat(char* dest, const char* src, size_t n);
hv_strncat 的参数 n 我看您的用法是传dest的sizeof(dest)

这两个用法不一样, 传相同参数得到的结果也可能不同(hv_strncpy也存在相同情况), 请问是故意这样写的吗?

**Comment by ithewei** [comment]
和原有的strncat、strncpy关于参数三的解读确实不同，hv_strncat、hv_strncpy是为了确保缓存区不溢出

**Comment by spiderpigpig** [comment]
> 和原有的strncat、strncpy关于参数三的解读确实不同，hv_strncat、hv_strncpy是为了确保缓存区不溢出

感谢您的解答
