### ISSUE TITLE
windows平台，编译选项打开mqtt，但编译出来的hv-static.lib库用dumpbin查看符号表，看不到mqtt的c语言版本的函数实现

### ISSUE THREAD

**Issue by ThomasVon2021** [ithewei/libhv#466]
PS D:\code\libhv-master\out\build\x64-Debug\lib> dumpbin /symbols .\hv_static.lib |sls mqtt

00B 00000000 SECT4  notype ()    External     | mqtt_head_pack
00C 000000A0 SECT4  notype ()    External     | mqtt_head_unpack
016 00000000 SECT5  notype       Static       | $unwind$mqtt_head_pack
019 00000000 SECT6  notype       Static       | $pdata$mqtt_head_pack
01C 00000000 SECT7  notype       Static       | mqtt_head_unpack$rtcName$0
01D 00000010 SECT7  notype       Static       | mqtt_head_unpack$rtcVarDesc
01E 00000050 SECT7  notype       Static       | mqtt_head_unpack$rtcFrameData
01F 00000008 SECT5  notype       Static       | $unwind$mqtt_head_unpack
020 0000000C SECT6  notype       Static       | $pdata$mqtt_head_unpack
00B 00000000 SECT4  notype ()    Static       | mqtt_estimate_length
00C 00000000 UNDEF  notype ()    External     | mqtt_head_pack
00D 00000000 UNDEF  notype ()    External     | mqtt_head_unpack
02E 000001C0 SECT4  notype ()    External     | mqtt_client_new
02F 00000270 SECT4  notype ()    External     | mqtt_client_run
030 000002B0 SECT4  notype ()    External     | mqtt_client_stop
031 000002F0 SECT4  notype ()    External     | mqtt_client_free
032 00000400 SECT4  notype ()    External     | mqtt_client_set_id
033 00000450 SECT4  notype ()    External     | mqtt_client_set_will
034 000004D0 SECT4  notype ()    External     | mqtt_client_set_auth
035 00000550 SECT4  notype ()    External     | mqtt_client_set_callback
036 00000580 SECT4  notype ()    External     | mqtt_client_set_userdata
037 000005B0 SECT4  notype ()    External     | mqtt_client_get_userdata
038 000005E0 SECT4  notype ()    External     | mqtt_client_get_last_error
039 00000610 SECT4  notype ()    External     | mqtt_client_set_ssl_ctx
03A 00000640 SECT4  notype ()    External     | mqtt_client_new_ssl_ctx
03B 000006B0 SECT4  notype ()    External     | mqtt_client_set_reconnect
03C 00000760 SECT4  notype ()    External     | mqtt_client_reconnect
03D 000007B0 SECT4  notype ()    External     | mqtt_client_set_connect_timeout
03E 000007E0 SECT4  notype ()    External     | mqtt_client_connect
03F 00000950 SECT4  notype ()    External     | mqtt_client_is_connected
040 000009C0 SECT4  notype ()    External     | mqtt_client_disconnect
041 00000A30 SECT4  notype ()    External     | mqtt_client_publish
042 00000E80 SECT4  notype ()    External     | mqtt_client_subscribe
043 00001190 SECT4  notype ()    External     | mqtt_client_unsubscribe
04A 00001470 SECT4  notype ()    Static       | mqtt_next_mid
04B 000014A0 SECT4  notype ()    Static       | mqtt_client_send
04C 00001510 SECT4  notype ()    Static       | mqtt_send_head
04D 00001600 SECT4  notype ()    Static       | mqtt_send_head_with_mid
04E 00001760 SECT4  notype ()    Static       | mqtt_send_ping
04F 00001840 SECT4  notype ()    Static       | mqtt_send_pong
050 00001870 SECT4  notype ()    Static       | mqtt_send_disconnect
051 000018A0 SECT4  notype ()    Static       | mqtt_client_login
081 00000000 SECT5  notype       Static       | $unwind$mqtt_estimate_length
084 00000000 SECT6  notype       Static       | $pdata$mqtt_estimate_length
08B 00000020 SECT5  notype       Static       | $unwind$mqtt_client_new
08C 00000030 SECT6  notype       Static       | $pdata$mqtt_client_new
08D 00000028 SECT5  notype       Static       | $unwind$mqtt_client_run
08E 0000003C SECT6  notype       Static       | $pdata$mqtt_client_run
08F 00000030 SECT5  notype       Static       | $unwind$mqtt_client_stop
090 00000048 SECT6  notype       Static       | $pdata$mqtt_client_stop
091 00000038 SECT5  notype       Static       | $unwind$mqtt_client_free
092 00000054 SECT6  notype       Static       | $pdata$mqtt_client_free
093 00000040 SECT5  notype       Static       | $unwind$mqtt_client_set_id
094 00000060 SECT6  notype       Static       | $pdata$mqtt_client_set_id
095 00000048 SECT5  notype       Static       | $unwind$mqtt_client_set_will
096 0000006C SECT6  notype       Static       | $pdata$mqtt_client_set_will
097 00000050 SECT5  notype       Static       | $unwind$mqtt_client_set_auth
098 00000078 SECT6  notype       Static       | $pdata$mqtt_client_set_auth
099 00000058 SECT5  notype       Static       | $unwind$mqtt_client_set_callback
09A 00000084 SECT6  notype       Static       | $pdata$mqtt_client_set_callback
09B 00000060 SECT5  notype       Static       | $unwind$mqtt_client_set_userdata
09C 00000090 SECT6  notype       Static       | $pdata$mqtt_client_set_userdata
09D 00000068 SECT5  notype       Static       | $unwind$mqtt_client_get_userdata
09E 0000009C SECT6  notype       Static       | $pdata$mqtt_client_get_userdata
09F 00000070 SECT5  notype       Static       | $unwind$mqtt_client_get_last_error
0A0 000000A8 SECT6  notype       Static       | $pdata$mqtt_client_get_last_error
0A1 00000078 SECT5  notype       Static       | $unwind$mqtt_client_set_ssl_ctx
0A2 000000B4 SECT6  notype       Static       | $pdata$mqtt_client_set_ssl_ctx
0A3 00000080 SECT5  notype       Static       | $unwind$mqtt_client_new_ssl_ctx
0A4 000000C0 SECT6  notype       Static       | $pdata$mqtt_client_new_ssl_ctx
0A5 00000088 SECT5  notype       Static       | $unwind$mqtt_client_set_reconnect
0A6 000000CC SECT6  notype       Static       | $pdata$mqtt_client_set_reconnect
0A7 00000094 SECT5  notype       Static       | $unwind$mqtt_client_reconnect
0A8 000000D8 SECT6  notype       Static       | $pdata$mqtt_client_reconnect
0A9 0000009C SECT5  notype       Static       | $unwind$mqtt_client_set_connect_timeout
0AA 000000E4 SECT6  notype       Static       | $pdata$mqtt_client_set_connect_timeout
0AB 000000A4 SECT5  notype       Static       | $unwind$mqtt_client_connect
0AC 000000F0 SECT6  notype       Static       | $pdata$mqtt_client_connect
0AD 000000AC SECT5  notype       Static       | $unwind$mqtt_client_is_connected
0AE 000000FC SECT6  notype       Static       | $pdata$mqtt_client_is_connected
0AF 000000B4 SECT5  notype       Static       | $unwind$mqtt_client_disconnect
0B0 00000108 SECT6  notype       Static       | $pdata$mqtt_client_disconnect
0B3 00000000 SECT7  notype       Static       | mqtt_client_publish$rtcName$0
0B4 00000008 SECT7  notype       Static       | mqtt_client_publish$rtcName$1
0B5 00000030 SECT7  notype       Static       | mqtt_client_publish$rtcVarDesc
0B6 00000018 SECT7  notype       Static       | mqtt_client_publish$rtcFrameData
0B7 000000BC SECT5  notype       Static       | $unwind$mqtt_client_publish
0B8 00000114 SECT6  notype       Static       | $pdata$mqtt_client_publish
0BC 00000028 SECT7  notype       Static       | mqtt_client_subscribe$rtcName$0
0BD 000000B0 SECT7  notype       Static       | mqtt_client_subscribe$rtcName$1
0BE 000000C0 SECT7  notype       Static       | mqtt_client_subscribe$rtcVarDesc
0BF 00000140 SECT7  notype       Static       | mqtt_client_subscribe$rtcFrameData
0C0 000000D0 SECT5  notype       Static       | $unwind$mqtt_client_subscribe
0C1 00000120 SECT6  notype       Static       | $pdata$mqtt_client_subscribe
0C3 00000150 SECT7  notype       Static       | mqtt_client_unsubscribe$rtcName$0
0C4 00000158 SECT7  notype       Static       | mqtt_client_unsubscribe$rtcName$1
0C5 00000180 SECT7  notype       Static       | mqtt_client_unsubscribe$rtcVarDesc
0C6 00000168 SECT7  notype       Static       | mqtt_client_unsubscribe$rtcFrameData
0C7 000000E4 SECT5  notype       Static       | $unwind$mqtt_client_unsubscribe
0C8 0000012C SECT6  notype       Static       | $pdata$mqtt_client_unsubscribe
0CA 000000F8 SECT5  notype       Static       | $unwind$mqtt_next_mid
0CB 00000138 SECT6  notype       Static       | $pdata$mqtt_next_mid
0CC 00000100 SECT5  notype       Static       | $unwind$mqtt_client_send
0CD 00000144 SECT6  notype       Static       | $pdata$mqtt_client_send
0CE 00000178 SECT7  notype       Static       | mqtt_send_head$rtcName$0
0CF 00000200 SECT7  notype       Static       | mqtt_send_head$rtcName$1
0D0 00000210 SECT7  notype       Static       | mqtt_send_head$rtcVarDesc
0D1 00000290 SECT7  notype       Static       | mqtt_send_head$rtcFrameData
0D2 00000108 SECT5  notype       Static       | $unwind$mqtt_send_head
0D3 00000150 SECT6  notype       Static       | $pdata$mqtt_send_head
0D5 00000208 SECT7  notype       Static       | mqtt_send_head_with_mid$rtcName$0
0D6 000002A0 SECT7  notype       Static       | mqtt_send_head_with_mid$rtcName$1
0D7 000002B0 SECT7  notype       Static       | mqtt_send_head_with_mid$rtcVarDesc
0D8 00000330 SECT7  notype       Static       | mqtt_send_head_with_mid$rtcFrameData
0D9 00000118 SECT5  notype       Static       | $unwind$mqtt_send_head_with_mid
0DA 0000015C SECT6  notype       Static       | $pdata$mqtt_send_head_with_mid
0DC 0000012C SECT5  notype       Static       | $unwind$mqtt_send_ping
0DD 00000168 SECT6  notype       Static       | $pdata$mqtt_send_ping
0DE 00000134 SECT5  notype       Static       | $unwind$mqtt_send_pong
0DF 00000174 SECT6  notype       Static       | $pdata$mqtt_send_pong
0E0 0000013C SECT5  notype       Static       | $unwind$mqtt_send_disconnect
0E1 00000180 SECT6  notype       Static       | $pdata$mqtt_send_disconnect
0E2 000002A8 SECT7  notype       Static       | mqtt_client_login$rtcName$0
0E3 00000340 SECT7  notype       Static       | mqtt_client_login$rtcName$1
0E4 00000350 SECT7  notype       Static       | mqtt_client_login$rtcVarDesc
0E5 000003D0 SECT7  notype       Static       | mqtt_client_login$rtcFrameData
0E6 00000144 SECT5  notype       Static       | $unwind$mqtt_client_login
0E7 0000018C SECT6  notype       Static       | $pdata$mqtt_client_login
0F3 00000000 SECT9  notype       Static       | ?s_mid@?1??mqtt_next_mid@@9@9 (`mqtt_next_mid'::`2'::s_mid)
119 00000008 SECT9  notype       Static       | ?mqtt_unpack_setting@?1??on_connect@@9@9 (`on_connect'::`2'::mqtt_unpac
k_setting)

**Comment by ithewei** [comment]
你图里打印的External | mqtt_client_new，不就是mqtt的c接口吗

**Comment by ThomasVon2021** [comment]
External 表示在这个静态库里只有申明，没有实现，连接的时候会报找不到实现

**Comment by ithewei** [comment]
windows下链接libhv静态库，需要加HV_STATICLIB预编译宏，这个你加了吗

**Comment by ThomasVon2021** [comment]
是指我在其它项目里用静态库连接的时候，也要加HV_STATICLIB宏，而不是在libhv编译静态库的时候？libhv的cmakelists我看是有此定义的：
```
if(BUILD_STATIC)
    add_library(hv_static STATIC ${LIBHV_SRCS})
    target_compile_definitions(hv_static PUBLIC HV_STATICLIB)
    target_include_directories(hv_static PRIVATE ${LIBHV_SRCDIRS}
        INTERFACE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include> $<INSTALL_INTERFACE:include>)
    target_link_libraries(hv_static ${LIBS})
    install(TARGETS hv_static
        EXPORT libhvConfig
        ARCHIVE DESTINATION lib)
    add_custom_target(libhv_static DEPENDS hv_static)
endif()
```

**Comment by ithewei** [comment]
是的，使用的项目里需要加，见FAQ：https://github.com/ithewei/libhv/wiki/%E4%B8%AD%E6%96%87FAQ#qwindows%E4%B8%8B%E9%93%BE%E6%8E%A5%E4%B8%8D%E8%BF%87

**Comment by ThomasVon2021** [comment]
今天确认后给你回复，谢谢

**Comment by ThomasVon2021** [comment]
ok了，谢谢
