### ISSUE TITLE
WebSocketServer对象，如果客户端长时间没数据通信，且没有发送心跳会被踢掉吗？

### ISSUE THREAD

**Issue by liutt1312** [ithewei/libhv#467]
WebSocketServer对象，如果客户端长时间没数据通信，且没有发送心跳会被踢掉吗？

会出现客户端连接之后不发数据1分钟之后，断链的情况

**Comment by ithewei** [comment]
先看看FAQ：https://github.com/ithewei/libhv/wiki/%E4%B8%AD%E6%96%87FAQ#qwebsocket%E5%90%AF%E5%8A%A8%E4%B8%8D%E4%B9%85%E6%96%AD%E9%93%BE%E6%8E%92%E6%9F%A5
另外，可以抓包看看哪端主动断开的
