### ISSUE TITLE
采用clang+lld编译链接时出错 ld.lld: error: duplicate symbol

### ISSUE THREAD

**Issue by ivan-lee-16** [ithewei/libhv#478]
配置：

clang
-rtlib=compiler-rt
-stdlib=libc++
-unwindlib=libunwind
-fuse-ld=lld

报错： 

ld.lld: error: duplicate symbol: std::get_terminate()
>>> defined at cxa_handlers.cpp.o:(std::get_terminate()) in archive /lib/x86_64-linux-gnu/libc++.a
>>> defined at eh_terminate.o:(.text._ZSt13get_terminatev+0x0) in archive /usr/bin/../lib/gcc/x86_64-linux-gnu/13/libstdc++.a
......
ld.lld: error: duplicate symbol: std::exception::~exception()
>>> defined at stdlib_exception.cpp.o:(std::exception::~exception()) in archive /lib/x86_64-linux-gnu/libc++.a
>>> defined at eh_exception.o:(.text._ZNSt9exceptionD2Ev+0x0) in archive /usr/bin/../lib/gcc/x86_64-linux-gnu/13/libstdc++.a
.....

先用clang+lld配置单独编译libhv为静态库.a，然后在工程中引用它，就会报这个错误了，用gcc+ld是正常的。

目前看到的都是集中在异常处理方面的，而没有采用libhv的工程不会报这个错误，暂时认为与工程配置无关。

**Comment by ithewei** [comment]
gpt给你的解答：
重复定义问题的解决方法之一是确保只使用一个 C++ 标准库，而不是混合使用。根据您的配置，您正在同时使用 libc++ 和 libstdc++，这可能导致冲突。您可以尝试以下步骤来解决该问题：

确定您想要使用的 C++ 标准库。是 libc++ 还是 libstdc++？

在编译和链接命令中，仅指定您要使用的 C++ 标准库选项。删除其中一个标准库选项，例如 -stdlib=libstdc++ 或 -stdlib=libc++。

如果您选择使用 libc++，请确保删除 -stdlib=libstdc++，并确保 libc++ 库可用。

如果您选择使用 libstdc++，请删除 -stdlib=libc++。

如果您仍然遇到重复定义的错误，请检查您的链接命令中是否存在其他重复的库或符号定义。

可能存在多个库文件提供了相同的符号定义，您可能需要根据您的需求调整链接命令，确保只包含需要的库文件。
