### ISSUE TITLE
VS+vcpkg+cmake集成环境不能直接使用包的问题

### ISSUE THREAD

**Issue by WindSnowLi** [ithewei/libhv#50]
1. 在VS普通C/C++项目中，使用```vcpkg```下载安装后可以直接使用。
2. 在VS创建的```cmake```项目中，不能直接使用```cmake```的指令```find_package```去添加```vcpkg```安装的包，需要手动用```include_directories```和其他的一些```cmake```指令去添加头文件和库才能够正常使用。
---
希望能简化```cmake + vcpkg```工程中的使用。

**Comment by shihlonchen** [comment]
請問這個問題解決了嗎？目前使用cmake依然無法用find_package添加工程。

**Comment by WindSnowLi** [comment]
我后来采用的是手动添加了库的所在目录并手动连接解决的获取Outlook for Android发件人: ***@***.*** ***@***.***> 代表 shihlonchen ***@***.***>发送时间: 2022年6月1日星期三 14:08收件人: ithewei/libhv ***@***.***>抄送: WindSnowLi ***@***.***>; Author ***@***.***>主题: Re: [ithewei/libhv] VS+vcpkg+cmake集成环境不能直接使用包的问题 (#50)

請問這個問題解決了嗎？目前使用cmake依然無法用find_package添加工程。

**Comment by shihlonchen** [comment]
我是使用FetchContent之後自己在CMAKE_MODULE_PATH裡面自己編寫Findlibhv.cmake來支援find_package，vcpkg我就放棄了，可能要去share資料夾下面新增相對應的libhvConfig.cmake。另外最新的cmake底下有libhvConfig.cmake ，但是release版最新的我抓下來沒看到，大概是最近增加的，我等下一版release再來看看，也許把cmake資料夾新增到module path裡就可以使用。
