### ISSUE TITLE
Error when Linking WebSocket Client Example with libhv_static Library

### ISSUE THREAD

**Issue by tkarthikan** [ithewei/libhv#500]
When attempting to build the WebSocket client [example](https://github.com/ithewei/libhv#websocket-client) and linking it with the `libhv_static` library, I encounter the following error:

ld: Undefined symbols:
  _CFArrayCreate, referenced from:
      _hssl_init in libhv_static.a[10](appletls.c.o)
  _CFRelease, referenced from:
      _hssl_ctx_free in libhv_static.a[10](appletls.c.o)
      _hssl_free in libhv_static.a[10](appletls.c.o)
      _hssl_init in libhv_static.a[10](appletls.c.o)
  _SSLClose, referenced from:
      _hssl_close in libhv_static.a[10](appletls.c.o)
  _SSLCreateContext, referenced from:
      _hssl_init in libhv_static.a[10](appletls.c.o)
  _SSLGetNumberSupportedCiphers, referenced from:
      _hssl_init in libhv_static.a[10](appletls.c.o)
  _SSLGetSupportedCiphers, referenced from:
      _hssl_init in libhv_static.a[10](appletls.c.o)
  _SSLHandshake, referenced from:
      _hssl_accept in libhv_static.a[10](appletls.c.o)
      _hssl_connect in libhv_static.a[10](appletls.c.o)
  _SSLRead, referenced from:
      _hssl_read in libhv_static.a[10](appletls.c.o)
  _SSLSetCertificate, referenced from:
      _hssl_init in libhv_static.a[10](appletls.c.o)
  _SSLSetConnection, referenced from:
      _hssl_init in libhv_static.a[10](appletls.c.o)
  _SSLSetEnabledCiphers, referenced from:
      _hssl_init in libhv_static.a[10](appletls.c.o)
  _SSLSetIOFuncs, referenced from:
      _hssl_init in libhv_static.a[10](appletls.c.o)
  _SSLSetPeerDomainName, referenced from:
      _hssl_set_sni_hostname in libhv_static.a[10](appletls.c.o)
  _SSLSetProtocolVersionMin, referenced from:
      _hssl_init in libhv_static.a[10](appletls.c.o)
  _SSLSetSessionOption, referenced from:
      _hssl_init in libhv_static.a[10](appletls.c.o)
  _SSLWrite, referenced from:
      _hssl_write in libhv_static.a[10](appletls.c.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/test.dir/build.make:98: test] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/test.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

**Comment by ithewei** [comment]
这些是apple系统库本身的符号，链库需要加-framework CoreFoundation -framework Security
