### ISSUE TITLE
http post请求

### ISSUE THREAD

**Issue by iaiaiq** [ithewei/libhv#502]
code(c++):
 hv::HttpClient* cli = new hv::HttpClient;
 cli->sendAsync(req, [=](const HttpResponsePtr& resp) {});

日志报错:
WARN  connfd=2444 connect error: :1041 [nio.c:226:nio_connect]

平台:
w32

描述:
返回的resp为空，日志输出连接失败，请教下这是什么原因导致的

**Comment by ithewei** [comment]
在herr.h里可以查到错误码的定义，1041是SSL_CTX创建失败了，你用的是默认的windows schannel，还是openssl

**Comment by iaiaiq** [comment]
> 在herr.h里可以查到错误码的定义，1041是SSL_CTX创建失败了，你用的是默认的windows schannel，还是openssl



> 在herr.h里可以查到错误码的定义，1041是SSL_CTX创建失败了，你用的是默认的windows schannel，还是openssl

openssl

**Comment by iaiaiq** [comment]
最开始使用的release带调试信息的版本，用了仓库上下载的openssl的库会报错，最后重新生成了不带调试信息的release版本，就可以正常发请求出去了
