### ISSUE TITLE
 Consider Supporting Bazel Build System

### ISSUE THREAD

**Issue by Edward-Elric233** [ithewei/libhv#506]
Hello, I am wondering if you have considered supporting the Bazel build system for libhv. Compared to CMake and Make, Bazel is more modern, supports incremental builds, and is simpler to use.

I have personally tried using Bazel to build libhv on Linux: https://github.com/Edward-Elric233/libhv/tree/feature/bazel. The compilation is successful, including the examples. I copied the executables to the bin directory and ran getting_started.sh, which worked as expected.

To use libhv  with Bazel, we only need to add the git repository to our WORKSPACE file and add the deps field in our cc_binary rule. There's no need for a complex compilation and installation process. Here's a demo of how it works: https://github.com/Edward-Elric233/libhv-bazel-test.

If you are open to the idea, I would be happy to submit a pull request to add Bazel support to the project.

**Comment by ithewei** [comment]
Very happy for you to submit a pull request to add Bazel support for libhv.

**Comment by Edward-Elric233** [comment]
Thank you for your positive response and for being open to the idea of adding Bazel support to libhv. I greatly appreciate the opportunity to contribute to this project.

I will work on preparing a pull request with the necessary changes and will make sure to follow the project's coding style and contribution guidelines.
