### ISSUE TITLE
HTTP SERVER 无法正确获取host和url

### ISSUE THREAD

**Issue by ChunSource** [ithewei/libhv#51]
![image](https://user-images.githubusercontent.com/26129811/111777271-0b69a900-88ee-11eb-9890-3342b7913a2e.png)

**Comment by ithewei** [comment]
`HttpRequest::host`是用于解析url得到的，HTTP头部里的Host应该通过`GetHeader("Host")`去拿

**Comment by ChunSource** [comment]
那请问要是报文没有host呢，怎么获取URL里面的域名

**Comment by ithewei** [comment]
HTTP请求行path里一般就不带host信息，如简单的GET / HTTP/1.1，这时必定会有Host头
如果path是完整URL的，解析出来的host也是有的
