### ISSUE TITLE
libhv的GetCookie问题

### ISSUE THREAD

**Issue by beanflame** [ithewei/libhv#516]
Cookie : "a=beanflame; b=hello"

"a=beanflame; b=hello" 

GetCookie("a") 输出：beanflame
GetCookie("b") 输出：
GetCookie("b")的输出都是空白，是分析问题

GetCookie分析不了，再有问题这样

libhv的GetCookie问题

**Comment by ithewei** [comment]
带多个name=value的，可以通过遍历cookies的kv查找
