### ISSUE TITLE
c++的TcpServer.h和TcpClient.h能否增加心跳接口

### ISSUE THREAD

**Issue by cjl3230** [ithewei/libhv#521]
首先感谢作者提供了那么强大的网络库,使用的相当顺手且高效
另外 能不能在c++的tcp接口代码中(TcpServer.h和TcpClient.h)增加对应的心跳机制的接口,方便调用

**Comment by ithewei** [comment]
有的，`SocketChannel::setHeartbeat`

**Comment by ithewei** [comment]
另外你也可以使用`setInterval`自己起定时器去发送心跳包

**Comment by cjl3230** [comment]
test的cpp里面能否增加一下心跳的示例. 这样就不用每次都有人来问了, 我开始就是因为没有找到接口, 以为cpp不支持该功能
