### ISSUE TITLE
能同时支持部署web静态资源吗？

### ISSUE THREAD

**Issue by 0x1306a94** [ithewei/libhv#527]
我想在开发板上面使用libhv提供API 以及web sever。
API 已经跑通了，我改如何配置 网页打包的静态资源呢？

**Comment by ithewei** [comment]
https://github.com/ithewei/libhv/blob/v1.3.2/docs/cn/HttpServer.md?plain=1#L48

**Comment by 0x1306a94** [comment]
<img width="773" alt="image" src="https://github.com/ithewei/libhv/assets/14822396/8cbed43e-4759-4e9a-9062-49419d6a8e24">
<img width="730" alt="image" src="https://github.com/ithewei/libhv/assets/14822396/8577d1ba-36b9-4244-99f4-d20ea2a8305e">
<img width="903" alt="image" src="https://github.com/ithewei/libhv/assets/14822396/7186ccc2-2539-4cf9-87ab-595080f5efd1">
* 是需要把每个子集目录也要添加映射吗? @ithewei

**Comment by 0x1306a94** [comment]
@ithewei 我改成设置 document_root 了，就对了

**Comment by ithewei** [comment]
设置ducument_root和通过Static("/",  path) 效果是一样的
https://github.com/ithewei/libhv/blob/dd2bb958f9ef41265c66c27d3ff499993a634812/http/server/HttpServer.cpp#L131

**Comment by 0x1306a94** [comment]
@ithewei 嗯呢。之前404是被SEAndroid权限拒绝了，补上权限后就对了。
