### ISSUE TITLE
web server handshake error

### ISSUE THREAD

**Issue by KARTES25** [ithewei/libhv#537]
net::ERR_SSL_BAD_RECORD_MAC_ALERT

OPENSSL_VERSION = 1.0.2l

web server has launched with option (worker_threads = 8)

at the page loading stage, after several page refresh calls, the server generates the error SSL_ERROR_BAD_MAC_ALERT

![image](https://github.com/ithewei/libhv/assets/47715030/6dde564b-1533-4fd4-8d3c-f0bf56afd41c)

**Comment by komnotmr** [comment]
I got the same issue. 
Reproducing:
1. Put to static folder my SPA (about 20 items - fonts, js bundles, icons)
2. Compile server WITH_OPENSSL
3. Launch server (httpd example) with1 process and 8 threads
4. Hold ctrl+R in browser (chrome/mozilla) for simulate much requests to static and dynamic routes
5. Get bad mac alert error in browser

I suppose, there is mistake in nio.c which corrupts openssl ctx buffer. But i'm not shure

**Comment by ithewei** [comment]
> I got the same issue. Reproducing:
> 
> 1. Put to static folder my SPA (about 20 items - fonts, js bundles, icons)
> 2. Compile server WITH_OPENSSL
> 3. Launch server (httpd example) with1 process and 8 threads
> 4. Hold ctrl+R in browser (chrome/mozilla) for simulate much requests to static and dynamic routes
> 5. Get bad mac alert error in browser
> 
> I suppose, there is mistake in nio.c which corrupts openssl ctx buffer. But i'm not shure

Also openssl version < 1.1.0?
I test like this, but no question.
Launch server (httpd example) with1 process and 8 threads
```
wrk -c 100 https://127.0.0.1:8443/
ab -n 1000 https://127.0.0.1:8443/
```

**Comment by komnotmr** [comment]
Hi! I've tryied both 1.1.1 and 3 versions. Results on the screenshot
![image](https://github.com/ithewei/libhv/assets/20460576/e9711d63-f2ce-4d3e-af17-a59279d6e047)

With this versions server works more robust and processing all my requests from browser without issues.
