### ISSUE TITLE
MQTT客户端自动重连会失败

### ISSUE THREAD

**Issue by zhxin999** [ithewei/libhv#538]
1. 测试的mqqt服务端为mochi
2. 如果服务端先启动，libhv的mqtt客户端后启动，一切正常
3. 如果libhv的mqtt客户端先启动，服务端后启动，mqtt连接会失败，持续报错error="protocol violation: qos out of range"

**Comment by ithewei** [comment]
没有环境复现，如发现问题可重新打开。
