### ISSUE TITLE
支持0长度的UDP包  support 0-length UDP packet

### ISSUE THREAD

**Issue by kahotv** [ithewei/libhv#541]
UDP协议本身是支持0长度UDP包的，且我在工作中踩到过这个坑。
测试发现udp_echo_server.c不能收到0长度的UDP包，希望能支持一下，感谢！

**Comment by xs-411** [comment]
0长度的udp包，是指接收端不知道长度吗？

**Comment by kahotv** [comment]
> 0长度的udp包，是指接收端不知道长度吗？

字面意义的0长度
sendto(0, "", 0, 0, &addr, sizeof(addr));

**Comment by xs-411** [comment]
> > 0长度的udp包，是指接收端不知道长度吗？
> 
> 字面意义的0长度，这样发给接收端，接收端echo没任何打印 sendto(fd, "", 0, 0, &addr, sizeof(addr));

我知道你的意思了,就是发送0数据。

**Comment by flx413** [comment]
发送0字节udp的意义是什么？

**Comment by kahotv** [comment]
> 发送0字节udp的意义是什么？


不知道，我就是个做代理的，别的程序要发0长度包我也得老老实实转发

**Comment by House-Men** [comment]
https://github.com/House-Men/libhv/commit/144a64b1c397da93cae318e6f96974511e17a4a7
参考这个修改项 只需改nio.c 三个地方就可以支持0字节了
