### ISSUE TITLE
部分日志宏与wireshark重定义

### ISSUE THREAD

**Issue by SuperBigYB** [ithewei/libhv#544]
我在我的项目中使用了libhv和libwireshark-dev, 发现编译时LOG_LEVEL_DEBUG等宏命名冲突, 详见<https://github.com/wireshark/wireshark/blob/master/include/ws_log_defs.h>第62行和<https://github.com/ithewei/libhv/blob/master/base/hlog.h>第50行, 建议libhv日志宏加上前缀"HV_".

**Comment by ithewei** [comment]
因为以前有很多项目在用了，现在不太好动头文件接口，你可以自己fork个维护，或者不要同时包含两者的日志头文件
