### ISSUE TITLE
我希望在HttpServer的事件循环开始之前, 可以得到这个loop对象.

### ISSUE THREAD

**Issue by warm-dawn** [ithewei/libhv#55]
因为我要给它设定定时器.
但是目前的代码是将整个创建到run的过程, 都是将它保护起来了的.
希望可以提供接口
在run之前让我可以给它增加一些事件.

**Comment by ithewei** [comment]
不太清楚你的业务场景为什么需要获取到loop对象？
HttpServer的设计就没打算暴露IO线程使用的EventLoop，这样很危险，一旦用户添加的事件回调里有阻塞操作或者其它不可预料的错误用法，就会影响到IO线程，建议另外创建EventLoopThread去做自己想做的事。

**Comment by warm-dawn** [comment]
原来你们理解的封装就是自我阉割是吗.

**Comment by ithewei** [comment]
在回调线程里通过tlsEventLoop可以获取到EventLoop对象，参考[httpd/handler.h](https://github.com/ithewei/libhv/blob/master/examples/httpd/handler.h)里setTimeout的使用，不打算暴露。
如无其他问题，我将关闭此issue
