### ISSUE TITLE
在windows服务模式下https无法正常建立连接的问题

### ISSUE THREAD

**Issue by KivinChiu** [ithewei/libhv#550]
我使用示例中的httpd代码，在其中加入了windows服务的代码（未改动其它，仅加入了响应服务控制），启用openssl库（1.1.1w和3.2.1都试过），无论编译为32位还是64位，在windows中双击程序运行，可以正常访问https端口，但只要以服务模式启动，就无法访问https，显示此网站无法提供安全连接127.0.0.1 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH，断点显示SSL_accept返回失败，代码为1。问题非常奇怪。我甚至试过，以其它服务来调用这个程序，仍是这个结果，我怀疑是否编译的程序中只要以服务模式（即SYSTEM账户）运行，openssl就会受到影响，或者在异步非阻塞网络里，服务模式有兼容性问题，这涉及底层了，请求各位了解的大佬帮助。

**Comment by House-Men** [comment]
有可能是不同运行环境产生的相对路径问题，因为你在Win32系统服务启动的程序运行目录通常为C:\Windows\System32，可以试试-c 指定绝对路径httpd.conf以及SSL证书相关文件路径配置成绝对路径，或者入口处获取程序所在目录后手动设置运行目录，但推荐的做法是win32数据目录采用%localappdata%\myapp，unix数据目录采用%home%/.myapp

**Comment by KivinChiu** [comment]
> 有可能是不同运行环境产生的相对路径问题，因为你在Win32系统服务启动的程序运行目录通常为C:\Windows\System32，可以试试-c 指定绝对路径httpd.conf以及SSL证书相关文件路径配置成绝对路径，或者入口处获取程序所在目录后手动设置运行目录，但推荐的做法是win32数据目录采用%localappdata%\myapp，unix数据目录采用$home/.myapp

感谢回复，问题已经解决，就是运行目录的问题。程序入口处设定使用SetCurrentDirectory当前程序目录，问题解决。
