### ISSUE TITLE
HttpHandler::Reset() 里面, 使用了空指针造成崩溃

### ISSUE THREAD

**Issue by YuriArthas** [ithewei/libhv#560]
![image](https://github.com/ithewei/libhv/assets/10540752/c07ccc15-34f2-45d5-8812-4a6c8f206668)

我的程序崩溃在了最后一行**InitRequest**

看代码是因为前面req->reset()后, 再次使用了这个req

**Comment by ithewei** [comment]
req->Reset()是HttpRequest类的Reset方法，不是req.reset()智能指针的重置，是不影响req.get()获取到裸指针的，你可以发下堆栈，一起分析下。

**Comment by SuperBigYB** [comment]
@ithewei 
崩溃堆栈:
```
SEGV on unknown address 0x000000000000 
HttpHandler::Reset HttpHandler.cpp:124
HttpHandler::onMessageComplete HttpHandler.cpp:334
operator() HttpHandler.cpp:102
Http1Parser::invokeHttpCb Http1Parser.h:130
on_message_complete Http1Parser.cpp:136
http_parser_execute http_parser.c:1839
Http1Parser::FeedRecvData Http1Parser.h:53
HttpHandler::FeedRecvData HttpHandler.cpp:712
on_recv HttpServer.cpp:30
hio_read_cb hevent.c:405
hio_handle_read hevent.c:372
__read_cb nio.c:48
nio_read nio.c:336
hio_handle_events nio.c:414
hloop_process_pendings hloop.c:122
hloop_process_events hloop.c:185
hloop_run hloop.c:477
hv::EventLoop::run EventLoop.h:54
loop_thread HttpServer.cpp:158
http_server_run HttpServer.cpp:222
hv::HttpServer::run HttpServer.h:143
main httpd.cpp:350
```
复现方法: 
运行样例中的httpd`./httpd -p 80`
然后运行`curl --http2 http://127.0.0.1`
控制台输出`Please recompile WITH_NGHTTP2!
Segmentation fault (core dumped)`

版本: hv 1.3.2

环境: Ubuntu22

**Comment by xiaohuih** [comment]
![image](https://github.com/ithewei/libhv/assets/3311600/1853c10f-2f6e-4f4b-be52-7d99b5c2a983)
![image](https://github.com/ithewei/libhv/assets/3311600/ba93b57b-434e-422f-9ac4-3da49ec6bfe4)
是有问题

**Comment by sc-bai** [comment]
![image](https://github.com/user-attachments/assets/3fc72d56-31f5-4a05-8fef-c2bf18e34389)
demo崩溃 有遇到过的没

**Comment by sc-bai** [comment]
![image](https://github.com/user-attachments/assets/eb70acdf-be80-467f-a799-ab6bbffaed46)
