### ISSUE TITLE
cross-compile android error

### ISSUE THREAD

**Issue by mecca1980** [ithewei/libhv#565]
按照build.md的交叉编译android的操作, 在msys2里用ndk-r21e交叉编译报错:

mec@DESKTOP-OQPH0MQ MSYS /c/work/mycode/libhv-master/build
$ export ANDROID_NDK_ROOT=/c/tool/android-ndk-r21e

mec@DESKTOP-OQPH0MQ MSYS /c/work/mycode/libhv-master/build
$ cmake .. -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-21

CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_C_COMPILER:
    /c/tool/android-ndk-r21e/toolchains/llvm/prebuilt/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_CXX_COMPILER:

   /c/tool/android-ndk-r21e/toolchains/llvm/prebuilt/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!

**Comment by ithewei** [comment]
上面错误提示很清楚吧
```
/c/tool/android-ndk-r21e/toolchains/llvm/prebuilt/bin/clang++

is not a full path to an existing compiler tool.
```
/c/这种应该是msys2里路径的写法，你可以试试在PowerShell里执行，不在msys2的shell里执行。
