### ISSUE TITLE
How to upgrade non-TLS connection to TLS connection?

### ISSUE THREAD

**Issue by tpisto** [ithewei/libhv#57]
Hi! How it would be possible with this library to upgrade non-TLS connection to TLS connection? For example MySQL and PostgreSQL would need first to negotiate with non-encrypted messages and after that start the TLS

With PostgreSQL connection the TLS initialization goes: https://www.postgresql.org/docs/8.4/protocol-flow.html. "To initiate an SSL-encrypted connection, the frontend initially sends an SSLRequest message rather than a StartupMessage. The server then responds with a single byte containing S or N, indicating that it is willing or unwilling to perform SSL, respectively."

With MySQL the case is just the same, you start with unencrypted communication: https://dev.mysql.com/doc/internals/en/ssl.html
https://dev.mysql.com/doc/internals/en/ssl-handshake.html
https://mariadb.com/kb/en/connection/

Thank you for all the help!

**Comment by ithewei** [comment]
Are you planning to use libhv to implement the mysql/pgsql communication protocol? I'm glad to see someone try this.

The hio_enable_ssl() api is provided in hloop.h, but the default step is TCP connect => SSL handshark => hconnect_cb,
maybe you can refer to ssl_client_handshark/ssl_server_handshark in [nio.c](https://github.com/ithewei/libhv/blob/master/event/nio.c) to implement TCP connect => hconnect_cb => sql SSLRequest => SSL handshark.

Best wishes!

**Comment by tpisto** [comment]
Thank you for the references!
