### ISSUE TITLE
httpclient下载文件失败

### ISSUE THREAD

**Issue by sunsonzh** [ithewei/libhv#571]
cmake编译的lib库
request请求网页正常，用samples里面wget的代码，下载文件失败
linux测试
![image](https://github.com/ithewei/libhv/assets/6812003/bd168418-0464-4c09-908f-cd01c32b642e

windows测试
![image](https://github.com/ithewei/libhv/assets/6812003/6c4a475b-881f-4ebf-9e01-b23bf01886ed)
另外windows下不能加载静态库编译，
![image](https://github.com/ithewei/libhv/assets/6812003/786f63d7-dbd6-4e45-8f6b-dcf60a2c7813)

**Comment by ithewei** [comment]
1、服务端不支持HEAD请求导致的吗？
2、加`HV_STATIC_LIB`预编译宏，见[FAQ](https://github.com/ithewei/libhv/wiki/%E4%B8%AD%E6%96%87FAQ#2%E9%9D%99%E6%80%81%E5%BA%93%E5%A3%B0%E6%98%8E%E5%AE%8Fhv_staticlib--%E9%9D%99%E6%80%81%E5%BA%93hv_staticlib)

**Comment by sunsonzh** [comment]
服务端是支持HEAD请求的，虽然content-length 返回的是0，但不应该报错,而且我有尝试去掉 HEAD功能，一样下载失败
![image](https://github.com/ithewei/libhv/assets/6812003/ee90849a-9cbf-4791-a4ed-9c6f3a668793)
我后面是用requests::downloadFile代替HttpClient, 可以正常下载文件

cmake编译我不知道HV_STATIC_LIB这个宏应该加在哪里，
我看CMakeLists.txt文件里面应该是已经定义了HV_STATICLIB这个宏参数的，这个参数不起作用吗？

**Comment by ithewei** [comment]
不是编译libhv时添加`HV_STATIC_LIB `，是你在windows上使用libhv静态库时需要添加预编译宏`HV_STATIC_LIB`

**Comment by sunsonzh** [comment]
![image](https://github.com/ithewei/libhv/assets/6812003/3ecc9eab-7462-40de-95bc-7b57e5d1473e)
我这里加了 HV_STATIC_LIB  宏，用静态库还是无法编译，动态库就能正常编译

**Comment by ithewei** [comment]
手误了，是HV_STATICLIB，不是HV_STATIC_LIB

**Comment by sunsonzh** [comment]
添加宏HV_STATICLIB，静态库调用可以了

但是下载还是有问题，这是我写的代码，wget函数，可以从samples里面复制过来的

![image](https://github.com/ithewei/libhv/assets/6812003/0e4da827-0fcb-434b-8ffa-3ab10d9fc1cd)
![image](https://github.com/ithewei/libhv/assets/6812003/cbd3574d-715c-44f0-89f0-be6cdc682df8)
![image](https://github.com/ithewei/libhv/assets/6812003/3780a08b-c7b9-4942-94c9-ef02c4f7c700)

**Comment by ithewei** [comment]
wget里有好几处request error打印，加点打印看看具体是哪里报错呗

**Comment by sunsonzh** [comment]
跟踪调试之后，现在可以了，是我在移除HEAD功能代码时，漏掉了给 req.url赋值， 感谢@ithewei 耐心的指点!
