### ISSUE TITLE
 make install will complain error for no-root user  for "ldconfig 2>/dev/null" need root permission 

### ISSUE THREAD

**Issue by cagev** [ithewei/libhv#572]
when make install using no-root user to user dir.  

ldconfig 2>/dev/null
make: [Makefile:97: install] Error 1 (ignored)
make install done.

**Comment by ithewei** [comment]
```
./configure
make
sudo make install
```

**Comment by cagev** [comment]
yes , I know how to compile and install , but I don't want to install it to system directory.  The installation will fail for a regular user as I neither have root access nor the necessary permissions. I think it's not necessary to execute the command "ldconfig".

**Comment by ithewei** [comment]
```
-ldconfig 2>/dev/null
make: [Makefile:97: install] Error 1 (ignored)
```
The error is ignored if you have no access.
