### ISSUE TITLE
关于基于TcpClient/TcpServer创建出的额外端口作用？

### ISSUE THREAD

**Issue by charlielven** [ithewei/libhv#574]
服务器端代码大致如下
hv::TcpServer   tcpSvr;
tcpSvr.createsocket(8888, "0.0.0.0");

客户端代码大致如下
hv::TcpClient    tcpCli;
tcpCli.createsocket(8888, "127.0.0.1");

然后通过tcp连接工具查看，发现client/server均有除了和8888端口关联以外，还有些额外端口的开销，这些端口是做什么作用的，能否关闭掉？

libhv版本：v1.3.2

![image](https://github.com/ithewei/libhv/assets/3304285/a088c560-86da-4ff9-81a9-02244cdbeecf)

**Comment by ithewei** [comment]
为了eventloop间通信，linux下用的eventfd所以没有额外端口，windows下没有eventfd，用的Socketpair，所以会有个内部连接

**Comment by xs-411** [comment]
> 为了eventloop间通信，linux下用的eventfd所以没有额外端口，windows下没有eventfd，用的Socketpair，所以会有个内部连接

为什么eventloop之间需要通信?

**Comment by ithewei** [comment]
> > 为了eventloop间通信，linux下用的eventfd所以没有额外端口，windows下没有eventfd，用的Socketpair，所以会有个内部连接
> 
> 为什么eventloop之间需要通信?

外部线程向eventloop投递自定义事件，见接口`hloop_post_event`

**Comment by charlielven** [comment]
感谢解答
