### ISSUE TITLE
hv线程模型的疑惑

### ISSUE THREAD

**Issue by xs-411** [ithewei/libhv#576]

**Comment by xs-411** [comment]
验证接收连接速度的场景:
场景1
1.主线程负责accept,然后丢弃
2.工作线程while(true) {sleep(1)}
3w连接并发,需要5-7秒.
场景2 
1.主线程负责accept,然后丢弃
3w连接并发,只需要2-3秒.

那也就是说单进程,单线程的性能才是最好. hv为什么不选择多进程呢？

**Comment by ithewei** [comment]
可以看看这篇博客：https://hewei.blog.csdn.net/article/details/120366024

**Comment by xs-411** [comment]
大佬,我其实有一个疑问,为什么一个进程开了两个线程,哪怕另外一个线程,什么都不做,都会拖慢性能。

**Comment by xs-411** [comment]
> 可以看看这篇博客：https://hewei.blog.csdn.net/article/details/120366024 你上面只测试了accept，实际是需要根据自己的场景选择合适的的多线程/多进程模式，只能说nginx的业务更适合多进程模式

我非常期待你的回复。

**Comment by ithewei** [comment]
> 大佬,我其实有一个疑问,为什么一个进程开了两个线程,哪怕另外一个线程,什么都不做,都会拖慢性能。

如果另外一个线程只是sleep，理论上不会占有太多CPU时间片，你可以再多测试下

**Comment by xs-411** [comment]
我已经验证过很多次了,并以交由技术总监验证,结果是一样的.但是找不到原因。

**Comment by xs-411** [comment]
无解。
