### ISSUE TITLE
加上-DWITH_OPENSSL=ON，使用cmake编译，提示ssl ca_file verify failed!

### ISSUE THREAD

**Issue by wesigj** [ithewei/libhv#58]
```
mkdir build

cd build

cmake .. -DWITH_OPENSSL=ON

cmake --build .

```

使用上面的cmake编译之后
`./examples/bin/httpd 
`
Load confile [/home/lyh/http/libhv/build/etc/httpd.conf] failed: 1030

将/etc/httpd.conf复制到该路径下可以解决

然后出现
`ssl ca_file verify failed!
`
请问我已经打开了-DWITH_OPENSSL=ON，为什么还是显示ssl ca_file verify failed!?

我关闭-DWITH_OPENSSL=OFF的时候，能够正常启动
`./examples/bin/httpd 
`

**Comment by ithewei** [comment]
开启ssl是需要证书的，你可以看下httpd.conf配置文件，看看放证书的cert文件夹有没有放到正确路径

**Comment by wesigj** [comment]
thank you very much!
我明白了这个使用方法了
要在libhv目录下，使用下面的命令启动httpd
`./build/examples/bin/httpd
`
依赖于etc和cert两个文件夹下面的配置文件

**Comment by wesigj** [comment]
thank you very much!
我明白了这个使用方法了
要在libhv目录下，使用下面的命令启动httpd
`./build/examples/bin/httpd
`
依赖于etc和文件cert两个文件夹下面的配置

**Comment by wesigj** [comment]
thank you very much!
我明白了这个使用方法了
要在libhv目录下，使用下面的命令启动httpd
`./build/examples/bin/httpd
`
依赖于etc和文件cert两个文件夹下面的配置
