### ISSUE TITLE
ptotorpc 服务端发送消息可以头和消息体分开发送吗

### ISSUE THREAD

**Issue by moujunqiang** [ithewei/libhv#588]
您好，请教一个问题。tcpservice 在发送消息的时候可以先发送header再发送body吗 我这样使得导致客户端收不到onmessage回调，还是必须把header和body封包之后一块发送

**Comment by ithewei** [comment]
TCP是流式协议，分多少包发送都是正确情况，对方应该根据应用层协议进行组包拆包

**Comment by jixhua** [comment]
> 您好，请教一个问题。tcpservice 在发送消息的时候可以先发送header再发送body吗 我这样使得导致客户端收不到onmessage回调，还是必须把header和body封包之后一块发送

刚好用了一下ptotorpc，你可以理解为 [ header + body ]  才是一条完整的消息，header 主要是用来拆包和标识协议的，接收端拿到数据后自己去掉 header 就行，你要是不用自动拆包功能，就可以不加 header

**Comment by xs-411** [comment]
> > 您好，请教一个问题。tcpservice 在发送消息的时候可以先发送header再发送body吗 我这样使得导致客户端收不到onmessage回调，还是必须把header和body封包之后一块发送
> 
> 刚好用了一下ptotorpc，你可以理解为 [ header + body ] 才是一条完整的消息，header 主要是用来拆包和标识协议的，接收端拿到数据后自己去掉 header 就行，你要是不用自动拆包功能，就可以不加 header

我有一个疑问,ptotorpc是同步非阻塞吗?

**Comment by jixhua** [comment]
ptotorpc 的 onMessage 是跑在事件循环中，可以看事件循环章节的介绍，one loop per thread，多个连接tcp连接共用一个io线程，是否阻塞取决于你怎么处理消息，onMessage 中你要是执行一个耗时操作，它就会阻塞当前事件循环（线程），浅薄理解，不知道是否正确

**Comment by xs-411** [comment]
> ptotorpc 的 onMessage 是跑在事件循环中，可以看事件循环章节的介绍，one loop per thread，多个tcp连接共用一个io线程，是否阻塞取决于你怎么处理消息，onMessage 中你要是执行一个耗时操作，它就会阻塞当前事件循环（线程），浅薄理解，不知道是否正确

我说的发送请求,等待响应写同步的代码,执行的是异步非阻塞IO.也可以说是协程.感受不到异步回调。
