### ISSUE TITLE
windows下不能使用cmake链接动态库hv.dll

### ISSUE THREAD

**Issue by wrxhardworking** [ithewei/libhv#590]
真让人费解，链接报错信息：E:\libhv\hv\bin\hv.dll : fatal error LNK1107: 文件无效或损坏: 无法在 0x388 处读取 [D:\c++projet\test_libhv\cmake-build-debug-msvc64\test_libhv.vcxproj]

**Comment by ithewei** [comment]
编译问题推荐到QQ技术群里求助吧
