### ISSUE TITLE
Source directory is modified during CMake configuration

### ISSUE THREAD

**Issue by ungive** [ithewei/libhv#591]
This is nothing big, but when configuring the project with CMake, the source directory is modified, which shows changes to stage in my git status message and in my editor, which is a bit annoying. This line in CMakeLists.txt is the reason:

https://github.com/ithewei/libhv/blob/8c67e056f63c6cb4f9476d5904bef5ef9f350f12/CMakeLists.txt#L89

My suggestion is to either write the output to the CMake binary directory and add the output directory to the include path or add hconfig.h to .gitignore.

**Comment by ithewei** [comment]
hconfig.h in .gitignore
