### ISSUE TITLE
htimer crash

### ISSUE THREAD

**Issue by adubovikov** [ithewei/libhv#593]
Hello everyone,

If I add more then 8500 timers, it crashes and generate a coredump. (the number is not static, sometimes the ammount of timers ~ 12K)

```
#0  0x00007f2e0a984b25 in heap_insert () from ....
#1  0x00007f2e0a987326 in htimer_add () from ....

```
Do you have any limit how many timers I can add/keep ? Should I increase the buffer size ?

Regards,
Alexandr

**Comment by ithewei** [comment]
No limit. Do you add the timer in the thread where the loop is located?
