### ISSUE TITLE
tcp client tcp_client_run直接就阻塞了，导致我的程序也卡主了，如何不阻塞？

### ISSUE THREAD

**Issue by xinsuinizhuan** [ithewei/libhv#594]
我参考tcp_client_test.c，写了一个tcp client客户端，一初始化tcp连接，我的程序就卡主了，一看tcp_client_run直接阻塞卡柱了，导致我的程序也阻塞进行不下去了。如何让它不阻塞？我注释掉tcp_client_run，但是就没法用了。

**Comment by xinsuinizhuan** [comment]
我可能同时启动多个tcp连接，但是这第一个就直接卡住了，程序也没法进行了。

**Comment by ithewei** [comment]
hloop_run就是个事件循环，需要占用一个线程，你可以额外创建一个线程去运行tcp_client_run

**Comment by xinsuinizhuan** [comment]
哦哦。感谢，单独了一个线程，可以了。

**Comment by baidwwy** [comment]
> hloop_run就是个事件循环，需要占用一个线程，你可以额外创建一个线程去运行tcp_client_run

单线程怎么办，我游戏用，有自己的循环，有没有类似once，或者nowait

**Comment by jixhua** [comment]
> > hloop_run就是个事件循环，需要占用一个线程，你可以额外创建一个线程去运行tcp_client_run
> 
> 单线程怎么办，我游戏用，有自己的循环，有没有类似once，或者nowait

在单独的此线程中运行 tcp_client 后把连接句柄传到你的循环中，或者可以参考 libhv C++版本的 TcpClient，非阻塞连接

**Comment by ithewei** [comment]
> > hloop_run就是个事件循环，需要占用一个线程，你可以额外创建一个线程去运行tcp_client_run
> 
> 单线程怎么办，我游戏用，有自己的循环，有没有类似once，或者nowait

hloop_run有HLOOP_FLAG_RUN_ONCE，只跑一次循环，或者你可以在自己的循环里跑hloop_process_events
