### ISSUE TITLE
日志文件保留固定天数

### ISSUE THREAD

**Issue by xufeihello** [ithewei/libhv#598]
程序中使用如下代码创建日志：
    hlog_set_file("./log/http_server.log");
    hlog_set_max_filesize(1024 * 1024 * 100); // 100M
    hlog_set_remain_days(3);                 // 3days
但是，程序运行后，会生成如下的日志文件
http_server.20240724.log
http_server.20240725.log
http_server.20240726.log

这样的话，程序每天启动，都会生成一个新的文件（日志被自动加上日期），为了防止无数日志文件撑爆存储（可能导致宕机），需要删除之前的文件，比如3天前的都删除：
使用 hlog_set_remain_days(3);
能达到预期的效果吗？谢谢！

**Comment by ithewei** [comment]
hlog_set_remain_days的作用就是这个，会自动删除之前的日志文件的

**Comment by xufeihello** [comment]
好的，谢谢。我以为hlog_set_remain_days(3)是保留相同文件名3天呢。
