### ISSUE TITLE
currentThreadEventLoop与实际所需EventLoopPtr矛盾

### ISSUE THREAD

**Issue by House-Men** [ithewei/libhv#603]
启动了一个httpServer接口服务，在某个接口内需要开启一个UdpClient，而不期望单独创建新的线程EventLoop，期望沿用httpServer的线程EventLoop，问题在于只能通过currentThreadEventLoop获取到纯指针而无法获取到httpServer原本的当前EventLoopPtr智能指针，而UdpClient以及其他许多对象的构造参数基本都是EventLoopPtr智能指针，如果将currentThreadEventLoop重新包裹在std::shared_ptr又将会出现使用结束后引用计数归零提前释放currentThreadEventLoop从而破坏httpServer原本的指针，最终陷入纯指针参数和智能指针参数的矛盾。

**Comment by ithewei** [comment]
可以看出你研究和使用libhv还挺深的，想在一个EventLoop里同时实现多个服务端/客户端。
这里我简单介绍下吧，HttpServer为了支持多进程模式，所以并未直接继承TcpServer，而是直接基于EventLoop实现的，隐藏在了HttpServerPrivdata内部，也是不鼓励外部复用HttpServer内部的EventLoop，避免阻塞或者影响HTTP服务。
不过你既然想复用内部的EventLoop，那我提供一个HttpServer::loop()接口能返回内部的EventLoopPtr吧，你看看满足你的需求了吗？
