### ISSUE TITLE
建议添加自定义拆包

### ISSUE THREAD

**Issue by baidwwy** [ithewei/libhv#605]
https://github.com/ithewei/libhv/blob/d7fd5451a788525a49bd7889580479c644e6feda/event/hloop.h#L487
添加一个USER

https://github.com/ithewei/libhv/blob/d7fd5451a788525a49bd7889580479c644e6feda/event/hloop.h#L501
添加一个void*

**Comment by baidwwy** [comment]
现在hevent_userdata就可以实现，unpack_mode_e设置0
但是不够直观

**Comment by ithewei** [comment]
不设置拆包，不就是自行拆包了

**Comment by baidwwy** [comment]
不设置拆包的话，就要自己搞缓存了啊，(我还没有看源码，猜的)

**Comment by ithewei** [comment]
是的，需要自己缓存，不过自定义拆包，需要暴露内部readbuf的head、tail移动，以及buffer扩容

**Comment by baidwwy** [comment]
看了httpd，应该可以用 hio_readbytes实现？我试试
