### ISSUE TITLE
windows中文路径，浏览器访问404，有什么好的解决方式吗

### ISSUE THREAD

**Issue by liutt1312** [ithewei/libhv#609]

**Comment by House-Men** [comment]
![image](https://github.com/user-attachments/assets/3fc6098e-0859-43e0-a105-94ddc99bcd4a)
https://github.com/ithewei/libhv/commit/6900f97a50d8cc64ea8504ff2e85aa8d2b422dcd
这个提交后的版本可以支持中文

**Comment by liutt1312** [comment]
好的
