### ISSUE TITLE
can not connect to https://fapi.binance.com

### ISSUE THREAD

**Issue by sjyMystery** [ithewei/libhv#61]

**Comment by sjyMystery** [comment]
![image](https://user-images.githubusercontent.com/12916017/120075405-ae4f5800-c0d3-11eb-8f45-956995e23b9d.png)

一会儿行 一会儿不行 
感觉不像是binance的服务器的问题。。

**Comment by ithewei** [comment]
我看了fapi.binance.com的IP在美国，需要使用vpn才能访问，所以极有可能是网络问题，
你可以在libhv的curl不行时，也试试系统的curl

**Comment by sjyMystery** [comment]
我的机器放在东京aws（ 这个域名套了cdn的，它的物理位置在东京的aws)
我刚试了试， 用ms的cpprestsdk就没这个问题。。（ 以及我尝试了正常的curl 也没问题）。。
然后libhv是一会儿行一会儿不行*（很迷惑）

**Comment by sjyMystery** [comment]
感觉应该是ssl的问题

**Comment by ithewei** [comment]
这个问题解决了吗？

**Comment by sjyMystery** [comment]
still not... 我暂时没空去试你说的解决方案，于是混搭了另外一个http库。。
