### ISSUE TITLE
求助实现一个简单的web界面

### ISSUE THREAD

**Issue by MyNewFlint** [ithewei/libhv#617]
希望用这个库开发arm上的web管理界面，参考了http_server_test.cpp，但是没有找到的哪里可以调用 index.html文件的接口，麻烦指导一下，非常感谢

**Comment by ithewei** [comment]
比如你的`index.html`文件是放在`/var/www/html/`目录，你可以设置
```
HttpService::Static("/", "/var/www/html/")
```
然后通过浏览器访问`http://ip:port`/即可访问`index.html`

**Comment by MyNewFlint** [comment]
谢谢指导，使用你的方法，可以实现了，接下去就是优化代码了，非常感谢，谢谢
