### ISSUE TITLE
SSL BUG

### ISSUE THREAD

**Issue by baidwwy** [ithewei/libhv#618]
开启OPENSSL后
客户端不开启SSL，也会有onConnection消息
第1次连接，先是成功然后断开

假如我设置了重连
就不断开了
channel->isConnected() 返回true,但是假的，数据发不出去

使用的是TcpClient.cpp

**Comment by ithewei** [comment]
这不是bug，是正常表现，SSL是基于TCP协议之上的，SSL握手发生在TCP连接上以后，TCP连接上表示服务端口是通的，但是并不知道对方是否要求SSL握手，需要客户端发起SSL握手，发送其它的内容，只会导致SSL服务端识别到不是SSL握手消息，就会关闭连接。

**Comment by baidwwy** [comment]
重点是后面。。。。重连之后，不会再断开了，显示是成功的

**Comment by ithewei** [comment]
服务端会等待客户端握手，客户端随便发送一个不是握手的消息，服务端才会断开连接。你使用系统自带的nc程序去连接SSL服务，一样的。

**Comment by baidwwy** [comment]
GET
