### ISSUE TITLE
期望能够在 SocketChannelPtr 中添加一个 void* 指针，用于提供反射信息。

### ISSUE THREAD

**Issue by dianjixz** [ithewei/libhv#621]
因为 libhv 的 SocketChannelPtr 是回调给出的，经常要进行两端对接，如果能在 SocketChannelPtr 中提供一个 void* 提供一个反射参数，感觉编程的难度大大降低，而且不用再很费劲的去做 SocketChannelPtr 匹配了。期望能够实现这个需求。

**Comment by dianjixz** [comment]
一个简单的改动，https://github.com/ithewei/libhv/pull/622#issue-2518763581，也许有更好的实现，期望早日能够使用。

**Comment by dianjixz** [comment]
TcpServer::foreachChannel 不应该是线程安全的吗？我使用过程中，出现了段错误，只能靠加锁来完成资源保护了。

**Comment by ithewei** [comment]
> 一个简单的改动，[https://github.com/ithewei/libhv/pull/622#issue-2518763581，也许有更好的实现，期望早日能够使用。](https://github.com/ithewei/libhv/pull/622#issue-2518763581%EF%BC%8C%E4%B9%9F%E8%AE%B8%E6%9C%89%E6%9B%B4%E5%A5%BD%E7%9A%84%E5%AE%9E%E7%8E%B0%EF%BC%8C%E6%9C%9F%E6%9C%9B%E6%97%A9%E6%97%A5%E8%83%BD%E5%A4%9F%E4%BD%BF%E7%94%A8%E3%80%82)

Channel::setContext 和 Channel::setContextPtr 就是用来实现绑定上下文的

**Comment by ithewei** [comment]
> TcpServer::foreachChannel 不应该是线程安全的吗？我使用过程中，出现了段错误，只能靠加锁来完成资源保护了。

foreachChannel内部是有加锁的

**Comment by dianjixz** [comment]
foreachChannel 的线程安全问题，还不清楚，在 foreachChannel 期间操作私有数据时，出现了段错误，我手动加了锁就好了。foreachChannel在另一个线程中使用，私有数据在onConnection中申请和释放，在onMessage更改。如果foreachChannel是线程安全的话，应该不会在 foreachChannel 的回调期间发生私有数据的段错误问题吧。这个段错误发生的概率很低，目前就发生了一次。

一直以为 Context 内部在使用，所以没敢用。

**Comment by dianjixz** [comment]
看了代码
```c++
    int foreachChannel(std::function<void(const TSocketChannelPtr& channel)> fn) {
        std::lock_guard<std::mutex> locker(mutex_);
        for (auto& pair : channels) {
            fn(pair.second);
        }
        return channels.size();
    }
```
中 mutex_ 貌似并没有锁到 onMessage，onConnection 。- . -

**Comment by ithewei** [comment]
这样的mutex_只是对channels容器的保护
