### ISSUE TITLE
tcp client 自动重连过程中 删除client会出现段错误

### ISSUE THREAD

**Issue by hh-kai** [ithewei/libhv#624]
![image](https://github.com/user-attachments/assets/88914a5f-991b-4b31-b035-93304b821e35)
step1:     

    auto loop_thread = std::make_shared<EventLoopThread>();
    loop_thread->start();
    loop_thread 会一直存在 直到整个程序退出

step2: 

     _tcp_cli = new TcpClient(loop_thread);
     _tcp_conn_fd = _tcp_cli->createsocket(remote_port, remote_host);
        reconn_setting_t reconn;
        reconn_setting_init(&reconn);
        reconn.min_delay = 1000;
        reconn.max_delay = 10000;
        reconn.delay_policy = 2;
        _tcp_cli->setReconnect(&reconn);

step3: 在析构函数中调用 

    if (_tcp_conn_fd > 0) {
        _tcp_cli->stop();
        delete _tcp_cli;
        _tcp_cli = nullptr;
    }
这样尝试去连接一个不存在的tcp server 会一直重连 这时候移除该客户端就有可能出现上面的段错误

在使用过程中 有什么需要注意的地方吗 比如创建或者移除  例子中大多只有创建 而且我看了  上面的关闭操作都是safe-thread的

**Comment by ithewei** [comment]
TcpClient对象还被EventLoopThread所使用期间，不能在其它线程里删除，可以使用TcpClient::deleleInLoop()在loop线程里安全被删除

**Comment by hh-kai** [comment]
> TcpClient对象还被EventLoopThread所使用期间，不能在其它线程里删除，可以使用TcpClient::deleleInLoop()在loop线程里安全被删除

我想在析构的时候安全的删除client
这里有TcpClient::stop() 还有 TcpClient::closesocket() 
我这样使用
_tcp_cli->stop();
_tcp_cli->deleleInLoop();
还是怎么做比较好

**Comment by hh-kai** [comment]
![image](https://github.com/user-attachments/assets/06b0083d-53b0-4121-9b08-2dd8ec374969)
析构里面
![image](https://github.com/user-attachments/assets/6d1f79bb-8249-4e30-ba6e-b84e1e763525)

还是会出现闪退 提示ontimer  自动重连里面的？

**Comment by ithewei** [comment]
设置了重连定时器，TcpClient的生命周期需要至少维持到onclose回调触发后，那就需要外部线程先closesocket，然后在onclose回调里去delete this（获取deleteInLoop也可以）了

**Comment by hh-kai** [comment]
> 设置了重连定时器，TcpClient的生命周期需要至少维持到onclose回调触发后，那就需要外部线程先closesocket，然后在onclose回调里去delete this（或者deleteInLoop也可以）

是这样吗？
![image](https://github.com/user-attachments/assets/1ffec19c-3db8-4440-b566-dd4107ebb49d)
然后在析构里面调用closesocket()

**Comment by ithewei** [comment]
TcpClient::onConnection里面使用isConnected判断连接还是断连，不是重写channel的onclose

**Comment by hh-kai** [comment]
![image](https://github.com/user-attachments/assets/f31b90d8-ba7c-4b73-a0b7-1e84a4afc630)
![image](https://github.com/user-attachments/assets/32850a7e-4fb0-4d99-ab84-6f587d9240a6)
有判断是否连接
出现问题的是添加了reconn时没有连接的时候做销毁动作
onConnection没有触发的时候销毁

**Comment by hh-kai** [comment]
> TcpClient::onConnection里面使用isConnected判断连接还是断连，不是重写channel的onclose

使用的过程是 tcp client去连接一个网络中不存在的ip 这样会一直尝试重连
这时候销毁tcp client 可能就会出现闪退

**Comment by ithewei** [comment]
外部线程设置一个标志表示需要销毁，然后closesocket，loop线程里在onConnection后通过isConnected判断已断连，且标志为需要销毁就调用delete this自行销毁

**Comment by ithewei** [comment]
没有标志的话，你也没法判断是重连失败，还是主动closesocket后需要销毁的情况

**Comment by hh-kai** [comment]
> 没有标志的话，你也没法判断是重连失败，还是主动closesocket后需要销毁的情况

在调用析构之前调用
![image](https://github.com/user-attachments/assets/b8deed54-1896-409b-ab3b-2fbee4499fe8)

然后onConnection中添加
![image](https://github.com/user-attachments/assets/fe721507-76c9-4479-b20e-7c5e5dced779)
