### ISSUE TITLE
json处理怎么换一个库来处理。

### ISSUE THREAD

**Issue by mrclassfree** [ithewei/libhv#627]
nlohmann::json  这个库对中文支持不好，接口使用方式也不好用，还不如cpprest的JSON类好用，我想在源代码中替换另外一个JSON类，哪位大神知道该怎么操作?

**Comment by ithewei** [comment]
通过req->body或者resp->body拿到原始的字符串数据，使用自己喜欢的json库解析生成即可

**Comment by newpc6** [comment]
可以试试 xpack::json

![image](https://github.com/user-attachments/assets/f1b56345-45ac-4f6e-84a2-855cb751b19a)
