### ISSUE TITLE
libhv使用http模块时无法添加定时器或者在EventLoop添加立即执行的回调，也无法获取到hloop_t。是否有计划添加呢？

### ISSUE THREAD

**Issue by TonyBeen** [ithewei/libhv#629]

**Comment by ithewei** [comment]
HttpServer::run后通过HttpServer::loop()接口可以获取到内部的EventLoopPtr，或者可以在onWorkerStart里通过currentThreadEventLoop获取

**Comment by ithewei** [comment]
如果是在HTTP回调里更简单，可以直接通过hv::setTimeout或者hv::setInterval设置定时器

**Comment by TonyBeen** [comment]
谢谢，改完后忘记关了
![A08AA738764B67ADA7AF03A006C4F48C](https://github.com/user-attachments/assets/9da4fc48-dfbd-4639-aa72-6dbd9f3f7d55)
