### ISSUE TITLE
Feature requested: Websocket support open with params

### ISSUE THREAD

**Issue by qZhang88** [ithewei/libhv#632]
The open function of WebSocketClient does not support param, could that be supported? I think the change is small.

change function definition from 

```C++
int open(const char* url, const http_headers& headers = DefaultHeaders);
```

to

```C++
int open(const char* url,
         const http_headers& headers = DefaultHeaders,
         const QueryParams& params = QueryParams());
```

update implementation with one line, just set query_params before  ParseUrl

```C++
+    http_req_->query_params = params;
     http_req_->ParseUrl();
```

**Comment by ithewei** [comment]
可以通过setHttpRequest接口来设置http_req_的

**Comment by qZhang88** [comment]
明白。嗯，不过我是直接把param拼接到url，也是一样的。

**Comment by ithewei** [comment]
> 明白。嗯，不过我是直接把param拼接到url，也是一样的。

是的，也是可以的
