### ISSUE TITLE
mqtt client，内存泄漏问题

### ISSUE THREAD

**Issue by MyNewFlint** [ithewei/libhv#639]
你好，我编译example文件夹下的mqtt/mqtt_client_test.cpp 例子，在main函数开始加入宏 HV_MEMCHECK; 程序正常跑起来了，收发mqtt消息都是对的，但是我用 ctrl+c结束进程，打印信息  Memcheck => alloc:16 free:5  ，能帮忙看看这是哪里没有释放资源吗

**Comment by ithewei** [comment]
用ctrl-c结束进程，很多释放操作都没有调用，你需要确保mqtt_client_free被调用

**Comment by MyNewFlint** [comment]
谢谢指导！我在程序退出的地方，调用类似这样的函数  s_cli.~MqttClient();   这样就正常了 Memcheck => alloc:16 free:16
