### ISSUE TITLE
Guide to new users about SSL/TLS.

### ISSUE THREAD

**Issue by sjyMystery** [ithewei/libhv#64]
下面两点可能需要加进文档。。
1. ssl的编译方式不是很友好，至少新手一上来并不知道怎么使用
2. libhv.so install到/usr/local/lib/ 的话，似乎很多系统的默认加载路径没有这个，就很尴尬。。。

**Comment by ithewei** [comment]
1、README.md为了避免篇幅过长，所以没有介绍SSL，SSL编译可在[BUILD.md](https://github.com/ithewei/libhv/blob/master/BUILD.md)中找到，更具体介绍见[FAQ](https://github.com/ithewei/libhv/wiki/FAQ)
2、一遍源码编译方式的默认安装路径就是`/usr/local`，其它开源库也一样，可以通过`./configure --prefix=/usr`改变安装目录

**Comment by sjyMystery** [comment]
但是作为新的用户的话感觉很不友好哇，要不考虑在README.md里加点信息？
