### ISSUE TITLE
pttOs\src\hv\base\hatomic.h:21: error: C1083: 无法打开包括文件: “stdatomic.h”: No such file or directory

### ISSUE THREAD

**Issue by pangdashou** [ithewei/libhv#7]
QT:Qt Creator 4.7.2 MSVC2015 64位，编译包错。这个是什么原因？

**Comment by ithewei** [comment]
cmake重新生成hconfig.h了吗，见HAVE_STDATOMIC_H

**Comment by pangdashou** [comment]
想起来了，没有更新

**Comment by ithewei** [comment]
MSVC没有stdatomic.h，最新代码hplatform.h中已重新定义#define HAVE_STDATOMIC_H 0，使用默认的hconfig.h也能编译过
