### ISSUE TITLE
The problem with Buildroot and cross-compilation

### ISSUE THREAD

**Issue by ZigFisher** [ithewei/libhv#76]
Good afternoon colleagues !

Today I tried to connect the excellent libhv library to my project [OpenIPC](https://github.com/OpenIPC) on video cameras assembled in Buildroot. 
Unfortunately, I managed to do this after some effort. 
I had to make a dirty insert, since the parameters of the cross-compiler were not passed.
Please correct me if there is another and more beautiful method.

Thanks.

My patch here - https://github.com/OpenIPC/openipc-2.1/blob/master/general/package/libhv/01_dirty_method.patch

**Comment by ithewei** [comment]
I am glad that you use libhv in your project.
About cross-compilation please refer to [BUILD.md](https://github.com/ithewei/libhv/blob/master/BUILD.md).
For example CC=arm-linux-gnueabi-gcc
1、use Makefile
```
make libhv CROSS_COMPILE=arm-linux-gnueabi-
```
or
```
make libhv CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++
```
2、use CMake
```
cmake . -DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabi-g++
cmake --build . --target libhv libhv_static
```

**Comment by ZigFisher** [comment]
Thank you so much for your very quick response, sir !
Of course, your method is beautiful and elegant.
However, it is not universal, if we use a compilation package for another architecture, for example, mips.
I'm still looking for a universal solution.. such as, for example, my patch-crutch.
Maybe I need to take some variables from Buildroot. I'll read the documentation.
Thank you again for the answer

**Comment by ZigFisher** [comment]
Yes, this should help solve my problem. 
I will write about the results here..

```
LIBHV_TOOLS_MAKE_OPTS = \
    CROSS_COMPILE="$(TARGET_CROSS)"
```
