### ISSUE TITLE
使用hio_t htimer_t出现不完全类型错误

### ISSUE THREAD

**Issue by ToxicCloud** [ithewei/libhv#81]
在使用libhv时，如果使用到hio_t或者htimer_t，编译器会给出 ”对不完全类型非法操作“ 的错误，如下：

![深度截图_plasmashell_20210727195619](https://user-images.githubusercontent.com/60279276/127150507-b2776d30-cb39-4ba2-b565-bcc169d7ec82.png)

 hio_t和htimer_t 定义都是在hevent.h头文件里面，但是编译后没有hevent.h头文件，而只是在hloop.h里面用typedef进行了前置声明，不知道是不是因为这个原因导致的还是我本身编译的就有问题，hloop_t定义也是在hevent.h，但是使用hloop_t不会出现这个情况！

**Comment by ithewei** [comment]
使用函数即可
io->loop => hevent_loop(io)
io->fd => hio_fd(io)
io->userdata => hevent_userdata(io)

**Comment by ToxicCloud** [comment]
好的，我试试
