### ISSUE TITLE
http_server_run运行中会出现coredump

### ISSUE THREAD

**Issue by liangjw-editor** [ithewei/libhv#82]
本地回环有客户端间歇性的发送http请求，然后在未知原因下此函数会奔溃，core dump信息如下
![image](https://user-images.githubusercontent.com/77035264/127442244-a79b00a0-e8d5-4767-a78f-c2bbc00509fc.png)

**Comment by liangjw-editor** [comment]
为了不阻塞住其他业务，我是用pthread_create来创建了一个线程来运行http_server_run

**Comment by ithewei** [comment]
v1.1.1以前的版本修过一个类似bug，先确保使用最新master代码做的测试吗

**Comment by ithewei** [comment]
> 为了不阻塞住其他业务，我是用pthread_create来创建了一个线程来运行http_server_run

有更简单的方法
http_server_run(&srv, 0); 第二个参数置0，内部就会自己起线程，不会占用当前线程的

**Comment by liangjw-editor** [comment]
> > 为了不再次住其他业务，我是用pthread_create来创建一个线程来运行http_server_run
> 
> 有更简单的方法
> http_server_run(&srv, 0); 第二个参数置0，内部就有自己的主题，不会占用当前线程的

好的，之前测试是v1.1.0版本的，我现在更新到最新版本试一下
