### ISSUE TITLE
websocket 连接中断

### ISSUE THREAD

**Issue by only-zzx** [ithewei/libhv#83]
**c++导入libhv库开启websocket的服务端，导入python的websockets库作为客户端
可以连接传递信息，但是连接超过十秒，c++服务端就会中断连接，print：onclose
ps：c++作客户端，py做服务端。可以持续通讯**

py代码：

> 
    #一直发消息
    async def send_msg(websocket): 
        message_train="training"  
        while True:
            time.sleep(5)
            await websocket.send(message_train)    
        await websocket.close(reason="user exit")
        return 0 
    #连接
    async def main_logic():
        async with websockets.connect('ws://172.17.7.99:9888',ping_interval=None) as websocket:
            await send_msg(websocket)
    #main
    asyncio.get_event_loop().run_until_complete(main_logic())
报错：
ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by ithewei** [comment]
![image](https://user-images.githubusercontent.com/26049660/127471823-316ef8c8-8938-4c06-b357-a1b1f104a896.png)
ni你看日志打印里有这行吗，服务端每10s会发一个ping心跳，如果客户端没有响应pong帧，服务端会断开连接的

**Comment by only-zzx** [comment]
感谢，应该是客户端ping应答失败的问题。
websockets的库的ping应答是封装好的。不太好改，之前python代码也只是设置ping_interval=None，去掉了心跳检测。
请问libhv库开启websocket的服务端能关掉心跳检测吗？需要设置哪个参数？

**Comment by ithewei** [comment]
已暴露出ping_interval，设置为0，即可关闭ping/pong心跳检测

**Comment by only-zzx** [comment]
感谢，已解决！
