### ISSUE TITLE
HttpServer跨域问题

### ISSUE THREAD

**Issue by toskeyfine** [ithewei/libhv#87]
我在response的headers中增加了Access-Control-Allow-Origin：* （KV形式），但依旧请求跨域？

**Comment by ithewei** [comment]
有些跨域不是简单的加Access-Control-Allow-Origin就行了，可能还需要响应OPTIONS，加Access-Control-Allow-Methods、Access-Control-Allow-Headers等相关头，建议根据CORS报错对应处理，具体可参考
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS
