### ISSUE TITLE
linux如何使用静态库

### ISSUE THREAD

**Issue by ThereChave** [ithewei/libhv#93]
使用makefile会使用静态库，但是cmake时，example里面链接的是动态库，如何更改链接静态库？

**Comment by ithewei** [comment]
`cmake -DBUILD_SHARED=OFF -DBUILD_STATIC=ON`可以配置只生成静态库

**Comment by ThereChave** [comment]
这个程序里面链接的还是动态库，只是生成不生成静态库，就是比如那个example中的http_server_test，使用静态库链接

**Comment by ithewei** [comment]
在动静态库同时存在的情况下，gcc是会优先链接动态库的，如果在动态库存在情况下要链接静态库是需要显示设置-Wl，-Bstatic这样的标识的，同时链接静态库需要显示链接其依赖的库，当然这些都是链库的知识，不是该库的讨论范畴
