### ISSUE TITLE
feature: support boringssl

### ISSUE THREAD

**Issue by meet-ai** [ithewei/libhv#94]

**Comment by ithewei** [comment]
Boringssl and openssl are compatible, you can install boringssl and `./configure --with-openssl`

**Comment by fuxiaohei** [comment]
it occurs errors when ld libcrypto from boringssl:

```
duplicate symbol '_SHA1' in:
    ../../thirdparty/libhv/lib/libhv.a(sha1.c.o)
    ../../thirdparty/boringssl/lib/libcrypto.a(bcm.c.o)
```

duplicate symbol is from https://github.com/google/boringssl/blob/master/crypto/fipsmodule/bcm.c, not existing in openssl
