### ISSUE TITLE
用Timing wheel实现心跳会不会更好

### ISSUE THREAD

**Issue by lanyeeee** [ithewei/libhv#95]
看了源码，libhv心跳的实现应该是给连接对应的EventLoop里设置一个无限循环的timer，定时回调注册的函数，这样一来1000个连接就要添加1000个心跳的timer
假设遇到一个很坏的情况：
每个连接刚好都是间隔1ms连进来，然后设置心跳
**也就是说，EventLoop里注册了1000个间隔为1ms的timer**
那么即使什么都不干epoll也每隔1ms就触发一次，然后回调心跳函数
这显然是很糟糕的

https://www.cnblogs.com/Solstice/archive/2011/05/04/2036983.html
这里有一种心跳的实现方案，我觉得很不错，能保证即使遇到我说的情况epoll也不会频繁触发
而且效率上应该也比用timer高

我自己的实现方案是每个EventLoop都拥有一个自己的Timing wheel，然后像文章里说的的那样管理Timing wheel，我自己用起来到目前都还没问题，希望对你有所帮助

**Comment by ithewei** [comment]
Good suggestion!
时间轮、红黑树、小根堆都是定时器的一些经典实现，libevent/libuv/libhv中都采用了小根堆，nginx采用了红黑树，时间轮更适合粒度比较粗、定时器数量比较多的场景，比如上面你提到的服务端连接数很多时的心跳定时器。

上面你提到了目前最坏的情况，每1ms就会调用一次epoll，实测下来也并不会影响性能，对于CPU来说1ms是很长的，不过这里确实是个可以优化的地方，我会提个commit，在添加定时器时将粒度控制到100ms，也是不错的优化，如果你已经实现时间轮方式，欢迎提PR贡献。

**Comment by lanyeeee** [comment]
谢谢你的肯定，可惜我的实现里时间轮用的std::deque，而libhv是一个支持C的库，需要一套C和C++都兼容的方案。我几乎没写过C，就不添乱了
